### ISSUE TITLE
[PhoneInput] Type to search not working

### ISSUE THREAD

**Issue by houmark** [uber/baseweb#1462]
## Current Behavior

When opening the phone input one would expect it being possible to type either part of the country name or the dial code to filter or be moved to the best match. Though, typing does nothing.

## Expected Behavior

Typing should either filter or move the user to the nearest match for added usability. This list is LONG and scrolling through the list is exhausting.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v7.8.0  |
| React   |   16.8.6      |
| browser |   Chrome 75.x      |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by houmark** [comment]
So after submitting this I saw a very fresh [blog post](https://baseweb.design/blog/phone-input/) about this exact field. Quoting from that post:
> Of course, because there are almost 300 country codes to choose from, we want our list to be filterable. Typing in your country name should quickly filter the list down to something more manageable. Sometimes country names can vary slightly so it is helpful to use fuzzy filtering for our list rather than following the default browser select filtering behavior. This means a user can open the dropdown, type america and quickly select United States of America.

So it seems it's been on the radar when developing this component, but neither of the included examples actually has the filtering working. Weird?

**Comment by gergelyke** [comment]
Hi @houmark !

Thanks for bringing this up! This is something we want to address soon and is on our roadmap.

**Comment by houmark** [comment]
> Of course, because there are almost 300 country codes to choose from, we want our list to be filterable. Typing in your country name should quickly filter the list down to something more manageable. Sometimes country names can vary slightly so it is helpful to use fuzzy filtering for our list rather than following the default browser select filtering behavior. This means a user can open the dropdown, type america and quickly select United States of America.
> 
> Thankfully, Base Web’s default Select component has fuzzy filtering and keyboard accessibility built in!

@gergelyke I appreciate you guys putting all these components out for the world to use as open source, but I think you should be more careful about announcing so proud features that are not present in the current released version in the future. It confuses us, developers, trying to use the components, and I would personally appreciate a more honest approach where you acknowledge in the blog post that, this feature is not yet ready, but that it's something you want to address in soon.

I tried this component with the `disabled` property and while it does make the text field itself disabled, the flag/country dropdown is still clickable and opens up, though it's not possible to change the country. Should I report that in a new bug?

**Comment by gergelyke** [comment]
that makes perfect sense - we should have communicated more clearly on what is still needs to be done

if you could create a bug ticket, that would help us better track it! thank you

**Comment by houmark** [comment]
Thanks for your feedback Gergely! I appreciate it.

The disabled issue is now submitted in #1483

**Comment by qqingvarqq** [comment]
@gergelyke  I would be implementing this feature `Make a list of countries to be filterable` if no one working on it already.

**Comment by jh3y** [comment]
@qqingvarqq Please assign this issue to yourself if you've begun working on it 👍

**Comment by qqingvarqq** [comment]
@jh3y if I can, I would, but it seems only project members have permission to assign issues.

**Comment by jh3y** [comment]
@qqingvarqq Sorted 👍

**Comment by houmark** [comment]
PR still awaiting approval and merge, hope that happens soon... please remove stale tag.

**Comment by gergelyke** [comment]
this was fixed in a previous release
