### ISSUE TITLE
Popover incorrect behavior when a component inside content is focused

### ISSUE THREAD

**Issue by qqingvarqq** [uber/baseweb#1807]
## Reproducible example
[Codesandbox url](https://codesandbox.io/s/popover-opens-on-click-9hsdb?module=/example.js)
## Current Behavior
When we open Popover and set focus on any inner components, (only when mounting component) Scroll position of the body changed (scroll goes up), but if we set focus anytime later everything is ok.
## Expected Behavior
When we open Popover and set focus on any inner components, the body scroll position should not be changed.

## Your Environment
| Tech    | Version |
| ------- | ------- |
| Base UI |8.16.6  |
| React   |16.8.6|
| browser |Chrome 76 (it's not related to a specific browser)|

- [X] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by makkBit** [comment]
Hi ! working on this..

**Comment by makkBit** [comment]
Scroll on focus is default behaviour. 
This can be prevent by passing object to `focus()`
```
ref.current.focus({
  preventSroll: true
});
```
or by explicity scrolling to current x and y position on focus
```
let x = window.scrollX, y = window.scrollY;
ref.current.focus();
window.scrollTo(x, y);
```

Please correct me if I am wrong.
@gergelyke

**Comment by gergelyke** [comment]
I tend to agree with @makkBit - this doesn't seem like a bug in Base Web

**Comment by qqingvarqq** [comment]
Hi @makkBit
Could you provide code sandbox example, where this problem fixed, unfortunately for me, this solution does not work? 
```
ref.current.focus({
  preventSroll: true
});
```
I briefly looked at this problem, and find out that for some reason Popover rendered in a wrong place on the initial render. It rendered from 
initial position
```
{
bottom: -1332
height: 100
left: 0
right: 200
top: -1432
width: 200
x: 0
y: -1432
}
```
to 
```
transform: translate3d(0px, -16px, 0px); //wrong position
```
but when you close Popover and press open button again everything works correct
It rendered from
```
{
bottom: 637
height: 100
left: 586
right: 786
top: 537
width: 200
x: 586
y: 537
}
```
to 
```
transform: translate3d(586px, 1793px, 0px);
```
which is correct.
(to see this behavior just put debugger in useEffect on initial render, you get similar numbers)
So that seems, that it is a bug in Base Web?
