### ISSUE TITLE
[Select] Improve generality of Select

### ISSUE THREAD

**Issue by btford** [uber/baseweb#1821]
Let's look at an example use of of `Select` to illustrate a problem.

Say I have an array of objects like this that I'd like to use in my `Select` component:

```js
const locations = [
  {id: 4, info: {city: 'San Francisco', state: 'CA', someHash: '123' } }
  {id: 5, info: {city: 'San Francisco', state: 'CA', someHash: '456' } }
]
```

I want to display the items, combining together `city` and `state`, and pass along `someHash` to my onChange event handler whenever it changes. So I write this in my app:

```js
const SelectLocation = ({onChange}) => {
  const options = locations.map(location => 
         ({ label: location.info.city + ', ' + location.info.state , value: location.id }));

  return (<Select 
      options={options}
      labelKey="label"
      valueKey="value"
      onChange={ ({value}) => locations.find(location => location.id === value).someHash }
      />);
}
```

Because `Select` needs a flat object to read the `labelKey` and `valueKey` from, I've added an O(n) operation and to create a new array of objects in each render. And because we only pass the value, I now have to do an O(n) lookup to find my object. (Actually, it looks like `Select` passes the whole object. But the types for the component do not reflect this.)

In fact, this is an issue any time you want to show a select of nested objects, or objects without certain existing properties!

How can we improve this? Let's make Select totally agnostic to what the user passes in.

```js
const SelectLocation2 = ({onChange}) => (
<Select
  options={locations}
  label={location => location.info.name + ', ' + location.info.state}
  onChange={(location) => onChange(location.info.someHash)} />)
```

Not we only have to call the label fn when we actually render that option. `Select` can also cache the results of this fn as a possible performance improvement.

Currently, the type of Select's Props is:

```js
export type OptionT = $ReadOnly<{
  id?: string | number,
  label?: React.Node,
  ...
}>;

type PropsT = {
  onChange: ({value:  OptionT}) => mixed, 
  options: $ReadOnlyArray<OptionT>,
  value: OptionT,
  valueKey: string,
  labelKey: string
}
```

Even if `Select` can currently accept objects of any type, Flow will give us the wrong object shape.

The type for `Select` should be this (note the type param for `Option` rather than a hard-coded shape):

```js
type PropsT<Option> = {
  onChange: ({value:  Option}) => mixed,
  label: Option => React.Node,
  options: $ReadOnlyArray<Option>,
  value: Option
}
```

Implementing this would be a breaking change, but you could make upgrading easier by providing a façade like this:

```js
type LegacyPropsT<Option: {}> = {
  options: $ReadOnlyArray<Option>,
  valueKey: $Keys<Option>,
  labelKey: $Keys<Option>,
  onChange: ({value: Option}) => mixed
}
const LegacySelect = <Option: {}>({options, id, label}: LegacyPropsT<Option>) => {
  return <NewSelect 
    id={p => p[id]}
    label{p => p[label]} />
}
```

We can even improve the accuracy of the types of the legacy wrapper by making it parametric, restricting `valueKey` and `labelKey` to the keys that exist on `options`

This is a problem with `Select`, but it's also a problem for any other Base Web component that takes in a list of options. This same pattern (making the list of `options` parametric) would improve these components as well.

This API has a couple other benefits, notably solving some issues with how `StatefulSelect` deals with mapping the `initialState` `value` to an option. The new type of `StatefulSelect`'s props could be:

```js
type NewStatefulSelectProps<Option> = {
  label: Option => React.Node,
  initialState: { value: Option },
  ....
}
```

We can deal with the identity of the `option` directly rather than have to map back and forth between `option` and `valueKey`.

I want to get some feedback on this proposed API change, but I'd be happy to help make these changes if we can agree that they're beneficial.

**Edit**: I see newer versions of baseweb's `Select` have `getOptionLabel` and `getOptionValue`, which are sort of in the correct spirit, but also have overly-specialized types. So maybe this issue should be about fixing the types, and removing `valueKey` and `labelKey` (since they artificially restrict the option param, and cause the mapping issue for `StatefulSelect`).

**Comment by nadiia** [comment]
@btford Thank you for bringing up the issue!
Here is a solution example to the first part of this issue https://codesandbox.io/embed/select-basic-usage-ftz3c . You don't need to remap the options list and can render custom label based on any prop of the option. The `labelKey` should be only used in a simple case where one would want to use a single prop value as a label. So to handle your case you just need to use `getValueLabel` and `getOptionLabel` props that accept a custom function that gets the option as an argument. 
We could probably further improve it and accept a chain of props for the `valueKey` like `info.someHash` to point to a nested prop unique value. 
I agree regarding the second part of your question - improve typing. Would you be open to putting a PR for it?

**Comment by btford** [comment]
Thanks for the response Nadia!

> We could probably further improve it and accept a chain of props for the valueKey like info.someHash to point to a nested prop unique value.

I think this is a bad idea– you lose type safety, and you end up encoding semantic issues in strings. You're also adding more bytes for an option that not everyone needs. I'm not sure how sensitive your team is to keeping these components lean, but I think it's important for shared components.

Using `getOptionLabel` and `getValueLabel` solves part of the issue, but not the issue of `onChange` not knowing the type of the option it receives, nor the issue of `StatefulSelect`'s initialValue not mapping correctly. I'm trying to illustrate a conceptual issue here– rather than focus on a primitive `value` to represent selected state, `Select` should focus on the identity of one of the objects passed in as an `option`. I suspect there are more symptoms of this same problem, and that we can solve them all at once with this change!

If the types are going to be accurate, I think you should ideally remove `labelKey` and `valueKey` in favor of just `getOptionLabel` `getValueLabel`. Alternatively, you can leave them for backwards compatibility, but weaken the guarantees of the type system when using this API .

> I agree regarding the second part of your question - improve typing. Would you be open to putting a PR for it?

I'm happy to put together a PR for this, but to be clear, there will also necessarily be changes to the runtime to ensure that the type information is correct, and that we address #1827 (something I think is intimately related to this issue). If that's alright, I can start on a PR and we can have a more concrete discussion there.

**Comment by nadiia** [comment]
@btford The `onChange`'s type looks like this currently:
```
onChange: (params: {
  value: ValueT,
  option: ?OptionT,
  type: ChangeActionT,
}) => mixed,
```
So it get's the current value, ref to the latest option that was added or deleted, and the change type. Is `option` in here what you'll need?

**Comment by btford** [comment]
Err, kind of. I suppose what I'm asking is that we entirely drop `value` as a concept and only have the `OptionT`, and that `OptionT` be parametric rather than static. If you have an `OptionT` you can always derive `ValueT`. There's no reason `Select` needs to have this additional responsibility.

I think we're starting to get in the weeds here a bit. It's probably easier to continue the conversation over a concrete diff.

Why don't I start something to illustrate what I'm getting at first, then we can determine if the direction is right before I invest the time to completely finish it?

**Comment by nadiia** [comment]
We'd need `valueT` for the multi-select.

**Comment by btford** [comment]
Oh, hmm. That does make things more difficult. I didn't realize multi-select and select where implemented within the same component.

If the types are going to be correct, multi-select needs to be a completely distinct component. In one case, you probably want `onChange` to receive a parametric `OptionT | null`, and on the other it should receive `$ReadOnlyArray<OptionT>`, where an empty selection is an empty array.

It's a bit strange to me that these are the same component– the implementation shares some code and layout between single and multi-select, but every consumer of just one mode for select is paying the byte cost for a set of behaviors they aren't using.

Again, I realize this would be a significant breaking change. To ease adoption, you can provide a weakly-typed facade that switches between the two modes.

**Comment by Firenze11** [comment]
Right now `options` is only limited to list of objects:
`options nullable $ReadOnlyArray<$ReadOnly<object>> = []`
Would be valuable to allow directly passing list of strings or numbers to it, to prevent having to converting string/number representation back to objects during usage.

**Comment by btford** [comment]
This is not stale! I have a PR incoming

**Comment by gergelyke** [comment]
Closing for now - please feel free to reopen if you plan to work on this! :)

For reference, we've split the Select component since the creation of this ticket, and added a warning for value prop misuse: https://github.com/uber/baseweb/commit/1e6d1276645523b5e2020297668194f83cc551d5
