### ISSUE TITLE
[Menu] Fixes and TODOs

### ISSUE THREAD

**Issue by abmai** [uber/baseweb#185]
* [x] Remove/rename `mapStyletronProps`
* [x] Add condensed styles
* [x] a11y check-thru
* [x] Better management of `key`
* [ ] Pass-thru on-click handlers for stateless `Menu`
* [x] Trigger event listeners only on focus
* [ ] Add `isLoading` state with a spinner view
* [x] Add `noResults` state with a 'No results' default message

**Comment by chasestarr** [comment]
added event listeners on focus here: https://github.com/uber-web/baseui/pull/1016

**Comment by chasestarr** [comment]
Going to close this issue since it's been sitting around for a while with no progress on the remaining points. We can start a new task for adding a loading state if it's requested
