### ISSUE TITLE
commit message lint provides no resolution information

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#1866]
when a contributor's commit message does not pass validation, the  help message does not provide useful information. it says that you need a subject and type, without explaining what those are.

`fix(component-name): the thing i did`

**Comment by kahwee** [comment]
We can integrate [Danger JS](https://danger.systems/js/) which has BuildKite support however it lints PRs instead. Sample [danger file](https://github.com/facebook/react-native/blob/master/bots/dangerfile.js) from react-native.

**Comment by chasestarr** [comment]
I think danger js looks interesting, but seems to be doing more than we need. Maybe we can look to it in the future if it's called for
