### ISSUE TITLE
[Datepicker] 'Composed range pickers' example displays default range mask

### ISSUE THREAD

**Issue by choyongjoon** [uber/baseweb#1971]
https://baseweb.design/components/datepicker/#composed-range-pickers

'Composed range pickers' uses custom `formatDisplayValue` to display the two dates separately. But cuurently the input displays default range mask. 

## Current Behavior

The Start Date shows `2019/04/01 -     /  /  `
The End Date shows `2019/04/10 -     /  /  `

## Expected Behavior

The Start Date shows `2019/04/01`
The End Date shows `2019/04/10`

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.5.2  |
| React   |         |
| browser | Firefox 70.0b8 |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
this was fixed in an earlier commit
