### ISSUE TITLE
[Select] SelectArrow overrides not applied

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#2073]
## Current Behavior

See [here](https://baseweb.design/components/select/?code=import%20*%20as%20React%20from%20"react"%3B%0Aimport%20%7B%20Select%20%7D%20from%20"baseui%2Fselect"%3B%0A%0Aexport%20default%20()%20%3D>%20%7B%0A%20%20const%20%5Bvalue%2C%20setValue%5D%20%3D%20React.useState(%5B%5D)%3B%0A%20%20return%20(%0A%20%20%20%20<Select%0A%20%20%20%20%20%20options%3D%7B%5B%0A%20%20%20%20%20%20%20%20%7B%20label%3A%20"AliceBlue"%2C%20id%3A%20"%23F0F8FF"%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%20label%3A%20"AntiqueWhite"%2C%20id%3A%20"%23FAEBD7"%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%20label%3A%20"Aqua"%2C%20id%3A%20"%2300FFFF"%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%20label%3A%20"Aquamarine"%2C%20id%3A%20"%237FFFD4"%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%20label%3A%20"Azure"%2C%20id%3A%20"%23F0FFFF"%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%20label%3A%20"Beige"%2C%20id%3A%20"%23F5F5DC"%20%7D%0A%20%20%20%20%20%20%5D%7D%0A%20%20%20%20%20%20value%3D%7Bvalue%7D%0A%20%20%20%20%20%20placeholder%3D"Select%20color"%0A%20%20%20%20%20%20onChange%3D%7Bparams%20%3D>%20setValue(params.value)%7D%0A%20%20%20%20%20%20overrides%3D%7B%7B%0A%20%20%20%20%20%20%20%20SelectArrow%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20style%3A%20(%7B%20%24theme%20%7D)%20%3D>%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20outline%3A%20%60%24%7B%24theme.colors.warning200%7D%20solid%60%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20backgroundColor%3A%20%24theme.colors.warning200%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%7D%0A%20%20%20%20%2F>%0A%20%20)%3B%0A%7D) for reproduction in yard

## Expected Behavior

I can replace the component or style it from overrides.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.7.1  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by csinge-uber** [comment]
Following the override documentation and styling tab - The select arrow components can't be styled using the same method as the other overrides. I think its important to keep the overrides consistent with overridable components.

@chasestarr has provided a workaround for now

```
SelectArrow: {
          // component: props => {
          //   return <div>hello</div>;
          // },
          props: {
            // color: "green",
            style: {
              color: "blue"
            },
          }
        }
      }}
```

**Comment by csinge-uber** [comment]
It also appears other Icon overrides are not working

Looking through the code, I suspect the problem is because its not passing through the overrides to the Icons.
