### ISSUE TITLE
Provide the ability toggle the selected overlay in the styling tool

### ISSUE THREAD

**Issue by csinge-uber** [uber/baseweb#2074]
My team finds the Styled Overrides tab really useful, the only issue is you can't deselect the last components overlay that you were overriding. Could you provide the ability to turn this on and off so that you can see your freshly styled component in all its glory.

**Comment by chasestarr** [comment]
Given the example below, Is the suggestion that after `Root` is open clicking on `Input` should remove the overlay from `Root`?

<img width="726" alt="Screen Shot 2019-10-11 at 10 27 00 AM" src="https://user-images.githubusercontent.com/5317799/66671863-d265d900-ec11-11e9-835a-bb5d91de1b9f.png">

**Comment by csinge-uber** [comment]
That part appears to work. I would actually like to turn off the overlay
completely when I am styling a component.

For example, the overlay is an orange color, if I change the background
from grey to white it's hard to tell if the change was applied.

**Comment by chasestarr** [comment]
what happens when you click 'empty'? is that what you intend?

**Comment by csinge-uber** [comment]
Yes, empty has the right effect. Some of the confusion was on me I would
often click into the Root then start editing another component.

Happy to close this request
