### ISSUE TITLE
Accordion overrides not working

### ISSUE THREAD

**Issue by antoniott15** [uber/baseweb#2077]
Examples of accordion in base UI web are incorrect or overrides on accordion are not working.

I'm trying to override the background color of the content and don't work for me, in the example given should work.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v8.11.0  |
| React   | 16.8.6 |
| browser |  Chrome   |

- [ X] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
@antoniott15 - please fork a codesandbox, and provide a repro
