### ISSUE TITLE
[ButtonGroup] cannot differentiate between checkbox mode select/hover/focus state

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#2100]
## Current Behavior

View [this](https://baseweb.design/components/button-group/#checkbox-mode) `ButtonGroup` example.
- Click the middle button to 'deselect' it
- Notice that the middle button's color does not change
- Hover over right button
- Notice that the right button's color matches the previously 'deselected' middle button
- Click on the right button to 'select' it
- Notice that the middle button changes color

## Expected Behavior

I believe both focus and hover states can apply the same background color. Selected needs to be different than the focus/hover color so visual feedback is provided to deselected buttons

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.8.0  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.
- somewhat similar to previous issue: https://github.com/uber/baseweb/issues/1222

**Comment by chasestarr** [comment]
Note: this only applies to the light theme

**Comment by sandgraham** [comment]
I think the v9 gray changes are compounded with the odd legacy behavior in #1222. after you click a button it is focused- which when the focus state is the same as selected makes it seem like you didn't actually click it. click again and it is selected again 😠 

Prob need to add some more differentiation between the states.

**Comment by foodforarabbit** [comment]
This is an easy fix but the hard part is deciding what colours should go where. Is there a style guide we can reference?

**Comment by sandgraham** [comment]
@foodforarabbit Prob best thing is to create a PR with a potential (non-breaking) update and share with us/design to get feedback rather than wait for design to update this.

For a styleguide, you can look in Figma at Base specs/documentation (especially on tokens) or just pull from the [colors available on our theme](https://baseweb.design/guides/theming/#colors).
