### ISSUE TITLE
[Menu] Add recommended Home/End key actions

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#2113]
## Feature description

as described in this issue: https://github.com/uber/baseweb/issues/2029, the baseui menu does not accept home/end keys to navigate the options. Recommended interaction is detailed here: https://w3c.github.io/aria-practices/#Listbox

TLDR:
- Home press highlights the first menu option.
- End press highlights the last menu option

**Comment by chasestarr** [comment]
maybe something like, (shift + up/down) would be similarly appropriate for quick navigation?

**Comment by rbrishabh** [comment]
Hey @chasestarr! I would like to look into this! :)

**Comment by chasestarr** [comment]
Let's only implement the home/end at the moment. Save shift modifier for later

**Comment by rbrishabh** [comment]
Sorry for the delay! Working on this today!

**Comment by rohitb4** [comment]
Can I look into this issue? @chasestarr

**Comment by chasestarr** [comment]
@rohitb4 I would wait a day or two to see if @rbrishabh is still looking into it, but after that I imagine it's fine

**Comment by rohitb4** [comment]
@chasestarr can I look into this issue now?

**Comment by rbrishabh** [comment]
Hey @rohit012 ! You can ake this up!

I have been really busy with other ones! This one is all yours! ;)
