### ISSUE TITLE
Slider rtl=true track issue

### ISSUE THREAD

**Issue by vik-buchinski** [uber/baseweb#2180]
The slider's pin goes to the 2 positions to the right when I click on it. 

Example: https://codesandbox.io/s/slider-598fq
Video: https://drive.google.com/file/d/1NMgXhTh4O631dQyss7t5azt5UoBXQRz8/view?usp=sharing

## Current Behavior
The slider's pin goes to the 2 positions to the right when I click on it.

## Expected Behavior

Slider's track goes to exact position where the user clicked.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.11.0  |
| React   |     16.8.6   |
| browser |  Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)   |
| OS | MacOS  Mojave 10.14.6 |

**Comment by gergelyke** [comment]
Hi @vik-buchinski - it seems like once you apply the `dir="rtl"` attribute to the body, it works. In codesandbox, that part is missing. Also, if you try the documentation site in the RTL mode, that works too (the upper right paragraph icon).

Have you tried it in your app?

**Comment by vik-buchinski** [comment]
@gergelyke 
> Hi @vik-buchinski - it seems like once you apply the `dir="rtl"` attribute to the body, it works. In codesandbox, that part is missing. Also, if you try the documentation site in the RTL mode, that works too (the upper right paragraph icon).
> 
> Have you tried it in your app?

> In codesandbox, that part is missing.
Sorry, but it is not missing, it is there, please look at the index.html.
Also, I tried to reproduse the issue on the website, and it also seems like there. Seems like it somehow around min/max/step values.
Video: https://drive.google.com/file/d/1QkzR3UB0N5EqprrWOUsOQJ1If11CzfE_/view?usp=sharing

**Comment by gergelyke** [comment]
Okay, I see - the issue arise when there are min values defined - I'll look into this today

**Comment by gergelyke** [comment]
@vik-buchinski I have a PR up that fixes it: https://github.com/tajo/react-range/pull/48
