### ISSUE TITLE
Create a `base16` baseweb theme definition

### ISSUE THREAD

**Issue by NameFILIP** [uber/baseweb#2201]
It would be nice to have a `base16` theme definition somewhere since it is a popular theming standard. 

Use-case: I want to use a `react-json-tree` which uses `base16` format for theming: https://github.com/reduxjs/redux-devtools/tree/master/packages/react-json-tree#theming.

Base16 description - http://chriskempson.com/projects/base16/

**Comment by gergelyke** [comment]
Closing this - we'll reopen if more people start asking for this
