### ISSUE TITLE
[Datepicker] delete all text does not trigger onChange

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#2205]
https://codesandbox.io/s/datepicker-ujmts

## Current Behavior

highlight all text in input
press backspace/delete
onChange is not called

## Expected Behavior

following the above repro steps, I expect onchange to be called. value to be determined

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.12.0  |

**Comment by MusaBajwa** [comment]
May I work on this if possible.

**Comment by gergelyke** [comment]
Yes, thank you @MusaBajwa  - I'll just assign the ticket to you
