### ISSUE TITLE
Regression: Modal closes when an open Select is going outside the Modal

### ISSUE THREAD

**Issue by houmark** [uber/baseweb#2224]
## Current Behavior
When a Select is inside a small Modal, and you open and click an option, the Modal closes unexpectedly. I believe this is a regression introduced in 9.13.0 potentially from #2206.

The demo on the Baseweb website has this behavior as well:
https://baseweb.design/components/select/#select-in-a-modal-dialog

The 9.12.0 demo does not have this behavior:
https://v9-12-0.baseweb.design/components/select/#select-in-a-modal-dialog

## Expected Behavior
To stay open.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.13.0  |
| React   |   16.11.0      |
| browser |    Chrome 78     |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by houmark** [comment]
@gergelyke Not sure how bad the bug was which was fixed and introduced the regression, but this one seems to be a bigger issue, so if there's no easy fix, maybe the other bugfix should be reverted?

**Comment by gergelyke** [comment]
@houmark - exactly what we are doing right now :) @nadiia will revert this, and we'll release a patch shortly

**Comment by houmark** [comment]
Great! I was just a bit confused by the "help wanted" tag, which made it seem like it may not become fixed or the regression reverted.
