### ISSUE TITLE
Make it possible to jump "show password icon" on password fields

### ISSUE THREAD

**Issue by houmark** [uber/baseweb#2257]
## Feature description

I've been looking but can't seem to find any option to override and show `tabIndex="-1"` on the "show password" icon when a field is type password.

In a normal form flow the user will fill in fields and hit tab to move to the next field, but when you have a password field it will jump to icon and hitting the wrong key after that will accidentally show your password, which is optimal.

This gets even worse if you have password and repeat password right after each other because you have to double-skip a lot.

I personally think these buttons/enhancers should be skipped by default and require tab/click, but I understand that you may want to keep it as now for usability + backward compatibility, but if it would be possible to override or set as an option on the password field, I'd be great.

Unrelated, I'd love to somehow try out fixes but 1) I have very limited time in TypeScript and 2) I am also missing a guide on how to best work on a fork of Baseweb locally etc (which commands to run, how to test, could the playground be useful for hacking new features together and more like that?).

**Comment by gergelyke** [comment]
Hi @houmark 

you can achieve it this way:

```js
import * as React from "react";
import { Input } from "baseui/input";

export default () => {
  const [value, setValue] = React.useState("aa");
  return (
    <Input
      value={value}
      onChange={event => setValue(event.currentTarget.value)}
      placeholder="Controlled Input"
      type="password"
      overrides={{
        MaskToggleButton: {
          props: {
            tabIndex: -1
          }
        }
      }}
    />
  );
};
```

I think the current default behavior is correct, as we have to make sure it's reachable with the keyboard too.

Regarding contributions, we do not expect you to ship typescript definitions - we are happy to help with them. You can find the contribution guidelines here: https://github.com/uber/baseweb/blob/master/CONTRIBUTING.md

Please reopen, if you have further questions!

**Comment by houmark** [comment]
Very cool. Was not aware of props in that way. I had forgotten. The docs site does not have a lot of examples with doing props overrides, so you may consider adding this to the doc site as an example?

I will try to get into contributing soonish, but first I should learn Baseweb better because most of ones need is already possible with the flexible overrides.

**Comment by gergelyke** [comment]
I think this example would make a good first contribution - what do you think? :)
