### ISSUE TITLE
Docs: Overriding password masking mechanism

### ISSUE THREAD

**Issue by LXSMNSYC** [uber/baseweb#2258]
## Current Behavior

<img width="616" alt="image" src="https://user-images.githubusercontent.com/4783372/68373130-329e5b00-017d-11ea-9919-2874231f1276.png">

According to the docs, the way to override the mask toggle button feature is to pass an Override object which replaces the mask toggle button component.

I tried using the same shape of the Override object as given in the examples, but it seems that the field does not exist.

Contrary to the docs, `<Password>` component does not exist in the library, which makes it impossible to override it.

## Expected Behavior

`<Input>` component accepts the `MaskToggleButton` property from the Override object to replace the mask toggle button feature.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.14.0  |
| React   |  v16.11.0  |
| Typescript | v3.6.3  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
You can do something like this : https://codesandbox.io/s/input-for-passwords-44emc

**Comment by LXSMNSYC** [comment]
the problem is that I am using TypeScript and it isn't the type definitions.
