### ISSUE TITLE
Docs/Feature: Show, Hide and Blank icons missing from baseui/icon

### ISSUE THREAD

**Issue by LXSMNSYC** [uber/baseweb#2259]
<img width="557" alt="image" src="https://user-images.githubusercontent.com/4783372/68375983-bf97e300-0182-11ea-88a3-b6a0144f16d8.png">
<img width="556" alt="image" src="https://user-images.githubusercontent.com/4783372/68376000-c888b480-0182-11ea-9b6f-17565f12be05.png">

Show, Hide and Blank icons are missing from the module 'baseui/icon' exports, even the standalone modules are not working (Docs might be misleading due to the demo).

**Comment by gergelyke** [comment]
Hi @LXSMNSYC - currently, you cannot manually change imports in the editor on the docs site. I've verified, and it works in codesandbox, so you should be good :)

**Comment by LXSMNSYC** [comment]
Btw, this isn't just on the demo, I tried it on Base 9.14 and looked up the type definitions
