### ISSUE TITLE
[Theming] Custom theme broken between v9.5.0 and v9.5.1

### ISSUE THREAD

**Issue by sebastianpantin** [uber/baseweb#2298]
## Current Behavior
 I have defined a custom theme based on the light theme where I override only the primary colors. 
I set all the primary colors to "blue" which should set the background color of, for example, buttons of secondary type to be blue. 

The problem is that when upgrading from v9.5.0 to v9.5.1 (and later) only the styling of my home page is styled according to this custom theme and any other pages are styled according to the standard light theme. So on my home page the secondary buttons have blue fill color but on any other page below home page in the tree the fill color of the secondary buttons are grey. 

## Expected Behavior
Custom theme should be global

## Your Environment
I wrap the root of my application with StyletronProvider and BaseProvider. 

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.5.1  |
| React   |    v.16.11.0     |
| browser |    Chrome     |

- [X] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
@sebastianpantin can you please create a codesandbox that reproduces the issues?

**Comment by sebastianpantin** [comment]
I found out the problem. I had imported the button component for example by writting:
`import {Button} from "baseui/button/index";` instead of `import {Button} from "baseui/button";`
