### ISSUE TITLE
[RadioGroup] Wrapping items in horizontal mode

### ISSUE THREAD

**Issue by andersonba** [uber/baseweb#2331]
## Current Behavior

https://codesandbox.io/s/radiogroup-wj1m1?module=/example.js

![image](https://user-images.githubusercontent.com/1501013/69008386-b3114880-0941-11ea-909d-1e02e196ce61.png)

## Expected Behavior

Wrap the items in newlines. (flex-wrap fixes it)

![image](https://user-images.githubusercontent.com/1501013/69008381-a5f45980-0941-11ea-8b9c-3d521fb7a896.png)

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.19.0  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
@andersonba thanks for the report! would you mind opening a PR fixing it?
