### ISSUE TITLE
Inconsistent usage of overrides for styling + no highlight of MultiValue + no effect after changing colour

### ISSUE THREAD

**Issue by nazariydolfin** [uber/baseweb#2332]
When using the StyleOverride tab for a Select component, with multi prop enabled and a couple of options selected (i.e. multi-select), then:

(1) Clicking on MultiValue does not highlight the tags
(2) Applying background color or any other style attribute has no effect on the tags
(3) It is not clear that MultiValue is an instance of a Tag. Ideally, this should be shown somewhere.
(4) Your override guide gives an example of using this MultiValue differently than styled override tab.
Styled override usage (that has no effect on the style):
```
<Select
      overrides={{
        MultiValue: {
          style: {
            borderRadius: "0px",
            backgroundColor: "slateblue"
          },
        },
...
```

your guide that works:
```
    <Select
      overrides={{
        MultiValue: {
          props: {
            overrides: {
              Root: {
                style: {
                  borderRadius: '0px',
                  backgroundColor: 'slateblue',
                },
              },
...
```

Should there be coherence between the two?

P.S. All Slack channel invites are dead, is there a help chat somewhere?

**Comment by gergelyke** [comment]
hi @nazariydolfin - have you tried [this link](https://join.slack.com/t/baseui/shared_invite/enQtNDI0NTgwMjU0NDUyLWQ0M2RhZWNiMDAwNDA4MDFiOWQyNmViODNkMzFmZDczYzM4MDliNjU3MmZhYWE5YjZhZmJjZWY0MDIxZjdkYzE)? It seems to be working for me

**Comment by gergelyke** [comment]
Also, regarding your original question, this is a known issue - currently, the StyleOverride tab does not support nested overrides. This is something we'll work on in the coming weeks. Closing for now, but please feel free to re-open for further discussion!
