### ISSUE TITLE
[Notification] Force line break in message

### ISSUE THREAD

**Issue by sebastianpantin** [uber/baseweb#2346]
Example at https://codesandbox.io/s/notification-qiwp0

## Current Behavior
Inserting `\n`in the string doesn't line break the message.

## Expected Behavior
Should give a line break at the position where I input `\n`.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.17.0  |
| React   |  v16.11.0  |
| browser | Chrome |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by kahwee** [comment]
You can do this https://codesandbox.io/s/notification-dls2y?fontsize=14&hidenavigation=1&theme=dark

Use it with caution though.

If the message is determined using user input, there's a possibility the user can inject arbitrary scripts that could compromise security.

**Comment by sebastianpantin** [comment]
Realised that you could do it like in this codesandbox: https://codesandbox.io/s/notification-jde02
No need for the `dangerouslySetInnerHTML`.

**Comment by houmark** [comment]
I believe a more correct and cleaner way would be to use an override and use `white-space: pre-line` instead of `white-space: pre`.

Something like:

```
              overrides: {
                Body: {
                  style: {
                    whiteSpace: 'pre-line',
                  },
                },
              },
```

This will also work in a `toaster` where you cannot use a function with a child `div`.
