### ISSUE TITLE
Latest radio buttons look lopsided 

### ISSUE THREAD

**Issue by tvst** [uber/baseweb#2361]
When I go to https://baseweb.design/components/radio/ the radio buttons look like this:

![lopsided_radio_button](https://user-images.githubusercontent.com/690814/69292628-72246880-0bbb-11ea-88a1-3ef991d9cc1a.png)

Notice how the top and right edges are wider than the bottom and left ones.

More info:
* This is on Base Web 9.21.1, but I can repro all the way down to v5 (but not v4).
* I'm on Ubuntu 19.10
* I can repro on Chrome but not Firefox.
* Chrome Version 78.0.3904.97 (Official Build) (64-bit)

[x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by ODAVING** [comment]
I can work on this issue :), if it's still available

**Comment by KarlaChen** [comment]
Hi, @tvst, Can I get more information?

**Comment by tvst** [comment]
Sure @KarlaChen ! What do you need exactly?

**Comment by KarlaChen** [comment]
@tvst Sorry, I have so bug fixing right now, don't think I have time to fix it.

**Comment by chasestarr** [comment]
This seems to have been resolved. Please re-open if it can be reproduced in the latest version

**Comment by tvst** [comment]
I can still repro this bug. Perhaps this is Linux-related?

**Comment by sandgraham** [comment]
Hi @tvst, we run our visual regression tests using ubuntu & puppeteer (headless chrome) and the radios don't seem to have this issue so I don't think this is strictly a linux/ubuntu issue. Do you have the page at the normal 100% zoom level when you take these screenshots?
