### ISSUE TITLE
[Radio] UI distorts when align="horizontal" 

### ISSUE THREAD

**Issue by akshaymarch7** [uber/baseweb#2364]
## Current Behavior
UI distorts when align="horizontal" 

Steps to Reproduce: 

- Open - [https://baseweb.design/components/radio/](https://baseweb.design/components/radio/)
- Select `align="horizontal"`

![image](https://user-images.githubusercontent.com/12824231/69339521-859f0480-0c8b-11ea-96d7-333135790955.png)

## Expected Behavior
UI should render properly

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.21.1  |
| browser |     Chrome    |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by eekbatani** [comment]
I can go ahead and try to get this fixed if you don't mind assigning the issue to me.

**Comment by gergelyke** [comment]
thank you @eekbatani

**Comment by foodforarabbit** [comment]
progress seemed to stall on this fix so I went ahead and finished it
