### ISSUE TITLE
[Datepicker] formatString behaves unexpected

### ISSUE THREAD

**Issue by mrtnbroder** [uber/baseweb#2400]
## Current Behavior

When formatString equals something like `MMMM yyyy`, then it shows as a weird value.

[https://baseweb.design/components/datepicker/](https://baseweb.design/components/datepicker/?code=import%20*%20as%20React%20from%20%22react%22%3B%0Aimport%20%7B%20Datepicker%20%7D%20from%20%22baseui%2Fdatepicker%22%3B%0A%0Aexport%20default%20()%20%3D%3E%20%7B%0A%20%20const%20%5Bvalue%2C%20setValue%5D%20%3D%20React.useState(%5Bnew%20Date()%5D)%3B%0A%20%20return%20(%0A%20%20%20%20%3CDatepicker%0A%20%20%20%20%20%20value%3D%7Bvalue%7D%0A%20%20%20%20%20%20onChange%3D%7B(%7B%20date%20%7D)%20%3D%3E%0A%20%20%20%20%20%20%20%20setValue(Array.isArray(date)%20%3F%20date%20%3A%20%5Bdate%5D)%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20formatString%3D%22MMMM%20yyyy%22%0A%20%20%20%20%2F%3E%0A%20%20)%3B%0A%7D)

formatString is `MMMM yyyy` and should therefore show as `MONTH_NAME YEAR` as being described here: https://date-fns.org/v2.8.1/docs/format

## Expected Behavior

Show date as being described in https://date-fns.org/v2.8.1/docs/format

`MMMM yyyy` should show as `January 2019` for example.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.23.1  |
| React   | v16  |
| browser |  Brave  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
hi @mrtnbroder - for some of the formatters, you have to provide a locale object to work. you can find an example for that here: https://codesandbox.io/s/datepicker-with-localization-nk11z

I'll make a PR to make it more highlighted in the documentation
