### ISSUE TITLE
Phone Input component is breaking the app when filtering country flags and search dont find results

### ISSUE THREAD

**Issue by julianruizsa** [uber/baseweb#2401]
## Current Behavior
If you set up custom flags on phone input component and try to filter on countries and the search don't find any result on country list, throws an error and break the app.

## Expected Behavior
You should be able to filter countries (with custom flags) and don't get an error.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.23.1  |
| React   |  16.12.0  |
| browser | Chrome, Firefox        |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
@julianruizsa thank you for the report - I'll look into this right now

**Comment by gergelyke** [comment]
actually, I am not that familiar with this component - @sandgraham when you have the time, can you look into this please?

**Comment by sandgraham** [comment]
Was able to reproduce here: https://codesandbox.io/s/phone-input-custom-flag-filter-bug-oyo6q

Will look into this today.

**Comment by gergelyke** [comment]
Thank you Graham
