### ISSUE TITLE
[DataTable] loading state

### ISSUE THREAD

**Issue by sijad** [uber/baseweb#2402]
## Feature description

show loading inside DataTable to let user know data are fetching from external resources.

**Comment by chasestarr** [comment]
Linked PR contributes a loading state to the flexbox-based `table` component. The loading state on this `data-table` will simply be text similar to how the empty state is rendered
<img width="620" alt="Screen Shot 2020-01-07 at 11 04 56 AM" src="https://user-images.githubusercontent.com/5317799/71921362-902f3380-313d-11ea-965b-06a9781f8df8.png">
