### ISSUE TITLE
Slider: can't select values that are not multiple of step

### ISSUE THREAD

**Issue by tconkling** [uber/baseweb#2417]
https://codesandbox.io/s/slider-4ngs0

## Current Behavior

I have a slider with current value = 1 and step = 2. When I drag the slider one step to the right, the current value becomes 4.

## Expected Behavior

I expect to get a current value of 3. It seems like Slider doesn't allow selecting values, via user interaction, that are not a multiple of "step".

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.25.0  |
| React   |   16.8.6      |
| browser |   Chrome Version 78.0.3904.108      |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
It looks like the available steps should consider the min value. Given `value = 2`, `min = 2`, and `step = 3`, I similarly expect the first available step to be `5`.

When determining if the slider "in-progress" value lands on a step, the component should calculate `(inProgressValue - min) % step`

**Comment by gergelyke** [comment]
> It looks like the available steps should consider the min value. Given `value = 2`, `min = 2`, and `step = 3`, I similarly expect the first available step to be `5`.
> 
> When determining if the slider "in-progress" value lands on a step, the component should calculate `(inProgressValue - min) % step`

yeah - I'll put up a diff today to react-range to fix it
