### ISSUE TITLE
Datepicker: years before 2000 cause several issues

### ISSUE THREAD

**Issue by tconkling** [uber/baseweb#2418]
https://codesandbox.io/s/datepicker-tkn6r

## Current Behavior

If I set the current value or the minDate of a Datepicker to a date before Y2K, I see the following behaviors:

(See the [linked codesandbox](https://codesandbox.io/s/datepicker-tkn6r) for an example that behaves problematically)

- I can't use the left-arrow button to select months _before_ Jan 2000 (despite my minDate being earlier than that):

![disabled_left_arrow](https://user-images.githubusercontent.com/709022/70104094-e0245300-15f1-11ea-879d-b33f2c874d6e.jpg)

- I _can_ use the right-arrow button to select months _after_ my maxDate:
![right_arrow_should_disable](https://user-images.githubusercontent.com/709022/70104123-f3372300-15f1-11ea-8cb9-6176cd724f4f.jpg)

- The month dropdown doesn't contain any values:
![no_results](https://user-images.githubusercontent.com/709022/70104089-da2e7200-15f1-11ea-857b-0b447fab3a77.jpg)

## Expected Behavior

- Should be able to select dates prior to 2000, if they're within my date range
- Should not be able to select dates greater than my date range, even if my minDate is prior to 2000
- I should see values in the month dropdown, even if my minDate is prior to 2000

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.25.0  |
| React   |    16.8.6     |
| browser |    Chrome Version 78.0.3904.108 (Official Build) (64-bit)     |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
@tconkling can you help us look into this?

**Comment by kantuni** [comment]
Hi @gergelyke,

I'll try send you the PR tomorrow.

**Comment by kantuni** [comment]
Here you go: https://github.com/uber/baseweb/pull/2430
