### ISSUE TITLE
docs(modal): untoggling autoFocus should set to false

### ISSUE THREAD

**Issue by leyanlo** [uber/baseweb#2433]
Docs site playground for Modal is confusing for autoFocus prop. Since autoFocus defaults to true, toggling it does not have to add it as a prop to the component. More importantly, untoggling autoFocus should explicitly set the prop to false to work.

https://baseweb.design/components/modal

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
@tajo should we address this/move the ticket to react-view?

**Comment by chasestarr** [comment]
fixed in https://github.com/uber/react-view/pull/23
