### ISSUE TITLE
Cannot change font size of Select

### ISSUE THREAD

**Issue by sandgraham** [uber/baseweb#2434]
On baseui v9.27.0 there is some strange behavior when trying to override the font size of a Select:

![selectissuefontsize](https://user-images.githubusercontent.com/1939257/70366146-16f4a600-184a-11ea-9db9-cf966d82fb32.gif)

This is targeting `Input` and `ControlContainer` with overrides. Note, this used to work in v8.

[Reproduction here](https://baseweb.design/components/select/?code=import%20*%20as%20React%20from%20%22react%22%3B%0Aimport%20%7B%20Select%20%7D%20from%20%22baseui%2Fselect%22%3B%0A%0Aexport%20default%20()%20%3D%3E%20%7B%0A%20%20const%20%5Bvalue%2C%20setValue%5D%20%3D%20React.useState(%5B%0A%20%20%20%20%7B%20label%3A%20%22AliceBlue%22%2C%20id%3A%20%22%23F0F8FF%22%20%7D%0A%20%20%5D)%3B%0A%20%20return%20(%0A%20%20%20%20%3CSelect%0A%20%20%20%20%20%20options%3D%7B%5B%0A%20%20%20%20%20%20%20%20%7B%20label%3A%20%22AliceBlue%22%2C%20id%3A%20%22%23F0F8FF%22%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%20label%3A%20%22AntiqueWhite%22%2C%20id%3A%20%22%23FAEBD7%22%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%20label%3A%20%22Aqua%22%2C%20id%3A%20%22%2300FFFF%22%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%20label%3A%20%22Aquamarine%22%2C%20id%3A%20%22%237FFFD4%22%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%20label%3A%20%22Azure%22%2C%20id%3A%20%22%23F0FFFF%22%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%20label%3A%20%22Beige%22%2C%20id%3A%20%22%23F5F5DC%22%20%7D%0A%20%20%20%20%20%20%5D%7D%0A%20%20%20%20%20%20value%3D%7Bvalue%7D%0A%20%20%20%20%20%20placeholder%3D%22Select%20color%22%0A%20%20%20%20%20%20onChange%3D%7Bparams%20%3D%3E%20setValue(params.value)%7D%0A%20%20%20%20%20%20overrides%3D%7B%7B%0A%20%20%20%20%20%20%20%20Input%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20style%3A%20(%7B%20%24theme%20%7D)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%7B%20fontSize%3A%20%2228px%22%20%7D%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20ControlContainer%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20style%3A%20(%7B%20%24theme%20%7D)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%7B%20fontSize%3A%20%2228px%22%20%7D%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%7D%0A%20%20%20%20%2F%3E%0A%20%20)%3B%0A%7D)

**Comment by gergelyke** [comment]
I believe it's related to this part https://github.com/uber/baseweb/blob/master/src/select/autosize-input.js#L63-L70
