### ISSUE TITLE
[Modal] Closing nested modals with ESC leaves body scroll locked

### ISSUE THREAD

**Issue by kirbycool** [uber/baseweb#2435]
If you open nested modals and close them both by pressing ESC, the body scroll lock doesn't get reset properly.
This is reproducible in the nested modal example from the docs (I tried in both Chrome and FF).
1. Go to https://baseweb.design/components/modal/#adding-nested-modals
2. Open the modal and the nested modal
3. Press ESC to close the modals
4. The body isn't scrollable

I dug in a bit, and the reason this is happening is because the bottom modal gets unmounted before the top modal. Each modal caches its mount node's `overflow` style attribute and replaces it on close. The top modal caches `overflow: hidden`, which is set by the bottom modal, but since it closes last, it resets to `overflow: hidden` after the bottom modal resets to `overflow = ''`.
https://github.com/uber/baseweb/blob/a82b504c9408f0659755075029f32ab65e61ae90/src/modal/modal.js#L119

In terms of solutions, ideally this would work with external components that modify the body overflow (I'm using a separate Drawer component that has this same bug when including a nested modal).
One option would be to not reset the reset the mountNode's `overflow` if it's been changed from `hidden` by some other component.
```js
  resetMountNodeScroll() {
    const mountNode = this.getMountNode();
    const lastStyle = this.lastMountNodeOverflowStyle;
    // If mountNode.style.overflow !== 'hidden', it's modified externally and we shouldn't reset it
    if (mountNode && lastStyle !== null && mountNode.style.overflow === 'hidden') {
      mountNode.style.overflow = lastStyle || '';
      this.lastMountNodeOverflowStyle = null;
    }
  }
```

## Current Behavior

Closing nested modals with ESC leaves the mount node (usually <body>) scroll locked.

## Expected Behavior

Closing nested modals does not cause scroll lock

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.27.0  |
| React   |         |
| browser |         |

- [ ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
@kirbycool thank you for the bug report! any chance you could send a PR fixing it?

**Comment by kirbycool** [comment]
Sure! I'll take a stab at it when I get some free time.

**Comment by gergelyke** [comment]
thank you! 🤗
