### ISSUE TITLE
[Typescript] RadioGroup and Radio's onChange prop is not typed like the native input

### ISSUE THREAD

**Issue by a-peltier** [uber/baseweb#2469]
First of all : I'd like to say that baseweb is a great project : I have been using it for personal projects for a while now, and we were able to use it in my company since the typescript definitions have been added, so thank you all 🎉 

## Current Behavior

Currently, in typescript we need to cast the `event.target` in the `onChange` event handler, even though it is not needed for a native radio input, see : https://codesandbox.io/s/basic-usage-80wkd

## Expected Behavior

We shouldn't need to cast the event's target. After some digging, I've found that the [onChange prop](https://github.com/uber/baseweb/blob/master/src/radio/index.d.ts#L30 )'s typescript definition could be changed to use the same as the native input element (see the [@types/react definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2006)

i.e it would require changing the onChange props in all the radio components (Radio, RadioGroup, StatefulRadioGroup...)

from `onChange?: React.FormEventHandler<HTMLInputElement>;`

to `onChange?: React.ChangeEventHandler<HTMLInputElement>;`

I gave it a try and updated the prop in a project :  it worked liked a charm, plus it is backward-compatible and doesn't conflict with code that casts the event's target

If you are ok with this change, I would gladly send a PR to update the prop and the code examples in the doc :)

**Comment by gergelyke** [comment]
Hi @a-peltier thank you, please send a PR :)
