### ISSUE TITLE
[DatePicker] date select on right calendar shifts to left

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#2471]
example reproduction: https://codesandbox.io/s/cg7bt?module=/example.js

## Current Behavior

1. select a date in the right calendar
2. notice that the previously right calendar is now on the left

## Expected Behavior

1. select a date in the right calendar
2. calendars should not change position

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.29.0  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by benmkramer** [comment]
Thanks Chase. I agree this might not be a big deal and users might generally select the start date first, so advancing the calendar gives them more range automatically. However, if there are users or use-cases that might lean towards picking an end date first, then it could be nice to configure this auto-advancement.

**Comment by chasestarr** [comment]
I'm going to mark this issue as an `enhancement` to provide the ability to configure this behavior since we now want the position shifting to be default behavior.

**Comment by foodforarabbit** [comment]
will submit PR for this soon
