### ISSUE TITLE
[DataTable] Filter Errors when mapping from object

### ISSUE THREAD

**Issue by gregostrowski** [uber/baseweb#2487]
I get errors with Numerical Filtering and Categorical Filtering when my `mapDataToValue` function is getting a value from an object.

eg:  `mapDataToValue: (data) => data.title,`

You can see the behavior in your examples, as the 3rd one, Custom Line Height, maps data from an object, compared to the other two that only map directly from a value.

https://codesandbox.io/s/9kqoq?module=/example.js

## Current Behavior

Clicking on 'Add Filter > Category Column' results in an error.
`Cannot read property 'toLowerCase' of undefined`
Clicking on 'Add Filter > Numerical Column' results in NaN values in the filter popup.

## Your Environment

These errors/bugs are visible in your examples on https://baseweb.design/components/unstable-data-table/

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.29.0  |
| React   |         |
| browser |         |

- [X ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
thank you, investigating today
