### ISSUE TITLE
[Datepicker] Disable keyboard opening on mobile devices

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#2533]
Feature request from @jonsadka:

> Is it possible to disable the keyboard from opening on mobile devices when using the <Datepicker/> component? It feels like unwanted behavior.

**Comment by jonsadka** [comment]
@chasestarr see attached photo for the experience opening the date picker on mobile devices. 

![4D55461B-61AB-4C59-961B-8C2AFDF9A459](https://user-images.githubusercontent.com/6504944/71294884-cc395a80-232e-11ea-819f-3cd6a599ffab.png)

**Comment by chasestarr** [comment]
It looks like applying the "readonly" attribute to the input element should suffice: https://codesandbox.io/s/datepicker-1yqnc but it does render an invalid attribute error in react. Surprisingly it recommends "readOnly" which does not work properly

**Comment by jonsadka** [comment]
Interesting. Will apply that fix but I suppose the question is wether this should be default behavior for the datepicker.

**Comment by chasestarr** [comment]
yeah should be a good stopgap for you now, we will likely add a control to toggle this

**Comment by foodforarabbit** [comment]
![Screenshot_20200117-172551_Chrome](https://user-images.githubusercontent.com/2348903/72656210-a1065300-394e-11ea-847a-374152e8836c.jpg)

**Comment by chasestarr** [comment]
This PR added how to do this in an example: https://github.com/uber/baseweb/pull/2711

**Comment by therealworldprojectllc** [comment]
The fix worked for this, but when you add in the split start and end dates, the same issue occurs on the second date input. Note to developers to fix this
