### ISSUE TITLE
[Card] Expose `srcset` attribute for <HeaderImage /> in <Card />

### ISSUE THREAD

**Issue by jonsadka** [uber/baseweb#2549]
## Feature description
In addition to the [`src` attribute](https://github.com/uber/baseweb/blob/master/src/card/card.js#L67) on the `<Card />` component, it would be helpful to pass an optional `srcset` attribute ([mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset)). For example

```js
<Card
  srcset={'https://source.unsplash.com/user/erondu/700x400 w400, https://source.unsplash.com/user/erondu/700x1200 w1200'}
  headerImage={'https://source.unsplash.com/user/erondu/700x400'}
>
  Contents
</Card>
```

**Comment by gergelyke** [comment]
@jonsadka thank you for opening this issue! any chance you can help us add this feature by submitting a PR?

**Comment by nbdn** [comment]
@gergelyke Can I work on this?
I'm using baseweb at work, and I found this library wondeful.  So I'm very interesting if I have any chance to work on it

**Comment by gergelyke** [comment]
yes, please do! 🤗 - also, may I ask you to let us know how you use base web here? https://github.com/uber/baseweb/issues/1889

**Comment by jonsadka** [comment]
Sorry just seeing this. @nbdn let me know if I can help in any way
