### ISSUE TITLE
[StatefulMenu] Add optional href for menu item

### ISSUE THREAD

**Issue by lianga888** [uber/baseweb#2555]
It would be useful to be able to supply an href alongside a label to navigate to that destination on click, instead of supplying an `onItemSelect` callback that pushes history. 

The benefit of the href over a callback is that you can "Open Link in New Tab", for example.

[A solution where you supply an anchor as the label](https://codesandbox.io/s/statefulmenu-zcso6) is insufficient because only a click on the text, and not anywhere on the entire menu item, results in navigating to the href.

## Feature description

- be able to optionally supply an `href` as a property on each of the objects in the `items` array supplied to `StatefulMenu`
- ensure the rendered anchor fills the entire height/width of the parent `ListItem`, such that clicking anywhere on the `ListItem` navigates to the href

**Comment by rohitb4** [comment]
@gergelyke Can I work on this?

**Comment by gergelyke** [comment]
of course, thank you @rohitb4
