### ISSUE TITLE
TimePicker set step to 1 crashes app 

### ISSUE THREAD

**Issue by reco** [uber/baseweb#2556]
There should be a way to let users choose time town to the minute.

**Comment by gergelyke** [comment]
@reco can you please provide an example code on what crashes the app?

**Comment by reco** [comment]
hey @gergelyke sure.

1. go to https://baseweb.design/components/time-picker/
2. set the step to 1
3. click the time picker

→ browser window unresponsive.

**Comment by gergelyke** [comment]
oh, I see - thank you! do you want us to look into this or any chance you can help us track it down?

**Comment by reco** [comment]
i think the issue here is that step 1 would render 3600 options. that's just too much. 
i think we should have a text input mode on the time picker... thoughts?

yes i would be happy to contribute.

**Comment by gergelyke** [comment]
@chasestarr what do you think, how should we handle this case?

**Comment by chasestarr** [comment]
We could add windowing to the list, although every time-picker will need to pay for the additional bundle size even if there is a small number of options. Maybe an extra ~7kb is acceptable?

My personal opinion is that minute precision is a suboptimal user experience compared to 'creatable' times, especially given a 24 hour range. One situation I think that level of granularity would be successful is given a small slice of time (between 1pm and 2pm for example). I could reconsider if given a use-case, but I think either enabling creatable or adding limits would be most appropriate.

**Comment by gergelyke** [comment]
that makes perfect sense - @reco would creatable times work for you?

**Comment by reco** [comment]
hey @chasestarr i agree. a full timepicker like what material does is overkill.

my use case really needs all values possible, i ended up using `<input type=range>` for hours and min ad a select for am/pm.

this could be an option on the time picker maybe?

**Comment by chasestarr** [comment]
Take a look at this example: https://codesandbox.io/s/calendar-with-time-select-actions-2wzte where a user will be able to type in a custom time at 1 min precision. Does that work for you?

**Comment by gergelyke** [comment]
We also have an example for that here: https://baseweb.design/components/time-picker/#timepicker

Closing for now, but please feel free to reopen!
