### ISSUE TITLE
Display time in the input field of the Datepicker

### ISSUE THREAD

**Issue by NameFILIP** [uber/baseweb#2559]
## Feature description
When `timeSelectStart` is added to the `Datepicker` a time selector appears on the dropdown panel, but the time is not visible in the input. It would be good to display it there for clarity.

![image](https://user-images.githubusercontent.com/834796/71706540-733fdc80-2d9a-11ea-8824-7ac8a36865a2.png)

https://codesandbox.io/s/datepicker-skdk2?fontsize=14&hidenavigation=1&theme=dark

**Comment by gergelyke** [comment]
thank you for opening this @NameFILIP - any chance you'd have the time to work on it?

**Comment by gergelyke** [comment]
Hm, on second thought, I wonder if it would make more sense to highlight this example, as we already have a specialized component for picking times: https://baseweb.design/components/datepicker/#composed-single-pickers

**Comment by NameFILIP** [comment]
I guess I can try to use a composed one.

P.S. `timeSelectEnd` property doesn't seem to work on the web:
![image](https://user-images.githubusercontent.com/834796/71760341-0ba89080-2e71-11ea-99f2-d63c88f7fb24.png)

**Comment by akshatnitd** [comment]
@NameFILIP I think it works when you select a range of dates.

**Comment by gergelyke** [comment]
@NameFILIP just checked with design, the current recommendation is to use the datepicker in combination with a timepicker:

<img width="601" alt="Screen Shot 2020-01-14 at 5 02 56 PM" src="https://user-images.githubusercontent.com/2174968/72395894-cb0e0a00-36ef-11ea-9e86-86733f7a2714.png">

as @akshatnitd pointed out, the timeEnd is only used in the range version
