### ISSUE TITLE
Set number of visible options in Selectbox

### ISSUE THREAD

**Issue by jrhone** [uber/baseweb#2561]
Is it possible to limit the number of visible options in a select box?

So if there's 50 options we only display 10 and the user can scroll to see the rest instead of displaying all 50?

The HTML Select input has a size attribute but it doesn't seem to be supported by BaseWeb, https://www.w3schools.com/tags/att_select_size.asp

If not possible could you add support for this feature?

Thanks!

**Comment by gergelyke** [comment]
hi @jrhone 👋 

it's a bit hidden in the props docs, but you can use the `maxDropdownHeight` property to set the height of the dropdown, like here: https://bit.ly/37vOjIz

we don't plan to support the same functionality as the native `size` property

I hope it helps!
