### ISSUE TITLE
ProgressSteps override to increase length of ContentTail doesn't work in IE11

### ISSUE THREAD

**Issue by bencohen2** [uber/baseweb#2562]
We want to make the `ContentTail` longer than the default, so we used an override on `StyledContentTail`. This works in Chrome but not in IE11 - in IE11, the tail is still too short and doesn't connect all the way to the next dot.

Codesandbox:
https://codesandbox.io/s/progress-steps-ie-bug-nm238

The relevant override is:
```js
  Tail: {
    style: (props: {$theme: ThemeT}) => {
      const {
        $theme: {
          sizing: {scale100}
        }
      } = props;
      return {
        ':after': {
          height: `calc(100% - ${scale100})`
        }
      };
    }
  },
```

## Current Behavior
The `ContentTail` is too short, this is an IE11 screenshot:
![image](https://user-images.githubusercontent.com/42184179/71750087-58767200-2e45-11ea-862d-68147edbf114.png)

## Expected Behavior
The `ContentTail` is just right, and leads nicely in to the next dot:
![image](https://user-images.githubusercontent.com/42184179/71750103-675d2480-2e45-11ea-81db-0f76885423b3.png)

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.30.0  |
| React   |  v16.10.2       |
| browser |  Chrome 78.0.3904.108 (works), IE 11 (doesn't work)       |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by bencohen2** [comment]
Why is the length of the `ContentTail` implemented using an `:after` CSS selector, rather than making the 'tail' part of the tail its own `div`? I.e. why not make it a `div` with length and width, etc.? It seems like that would be more extensible and more be easier to override.

**Comment by gergelyke** [comment]
> Why is the length of the `ContentTail` implemented using an `:after` CSS selector, rather than making the 'tail' part of the tail its own `div`? I.e. why not make it a `div` with length and width, etc.? It seems like that would be more extensible and more be easier to override.

I am not sure why we made that decision - can you send a PR fixing it?

**Comment by foodforarabbit** [comment]
I've submitted a PR to address the issue with the ContentTail being an :after instead of just the div itself
