### ISSUE TITLE
Calendar time selector does not call onChage

### ISSUE THREAD

**Issue by gergelyke** [uber/baseweb#2563]
When using the calendar with the built-in time picker, the onChange prop is not called when a time is selected. 

Reproducible here: https://baseweb.design/components/datepicker/#composed-single-pickers

**Comment by akshatnitd** [comment]
@gergelyke Can I work on it?

**Comment by akshatnitd** [comment]
I have found a solution to it. Let me know if I can go ahead and raise a PR.

**Comment by gergelyke** [comment]
@akshatnitd please do! 🤗 I'd also like to ask you to add a regression e2e test to make sure it won't happen again

**Comment by akshatnitd** [comment]
@gergelyke Sure, will do.

**Comment by gergelyke** [comment]
thank you!
