### ISSUE TITLE
Export Timezone type from the timezonepicker/types

### ISSUE THREAD

**Issue by NameFILIP** [uber/baseweb#2571]
## Feature description
I would like to use the `Timezone` type in my application (redux state, callbacks, etc). Please export it from the timezonepicker/types:
```
type Timezone = {
  id: string,
  label: string,
  offset: number
};
```
(https://github.com/uber/baseweb/blob/master/src/timezonepicker/types.js#L35)

**Comment by gergelyke** [comment]
@NameFILIP would you mind creating a PR for this?
