### ISSUE TITLE
Internationalization Documentation is Vague

### ISSUE THREAD

**Issue by LaurenReillyW2G** [uber/baseweb#2574]
## Feature description
I was reading through the i18n section of the documentation and it was not very clear how to use this and what kind of features it has. I think that the internationalization documentation should be updated.
 
A few specific things:
-Can it format data per language such as time, date, currency, pluralizations?
-How do you switch between languages, and when you switch does it update the HTML document language? I can't see an english version of the example so its hard to see what is going on.
-I can't see the script for the StatefulPagination component so it is difficult to see how the translations are actually being implemented.
-How do you use the LocaleProvider? Wrap the whole app or each component? What props does it take?
-Is this built with Format.js at all?

Overall it is hard to tell how to best utilize the Internationalization components with the current state of the documentation. Would love for more explanation and in depth examples of functionality and how to use.

**Comment by adenta** [comment]
@LaurenReillyW2G were you able to get any clarity here?

**Comment by chasestarr** [comment]
Apologies for taking so long to update this. Hopefully the improvements linked above will be more useful
