### ISSUE TITLE
[DataTable] support RTL

### ISSUE THREAD

**Issue by sijad** [uber/baseweb#2589]
## Feature description

add RTL support for DataTable

**Comment by rohitb4** [comment]
@gergelyke can I work on this?

**Comment by gergelyke** [comment]
sure think, thank you @rohitb4 - just assigned it to you

**Comment by chasestarr** [comment]
What do we expect to change in RTL? In google docs for example, does the column order reverse? Let's please determine the requirements before getting to far with development

**Comment by sijad** [comment]
I think reversed columns is very useful feature. Google docs also supports it (https://invidio.us/watch?v=aDXxnDQwQ3I).
Other elements like filters and bulk actions should also support RTL.

**Comment by rohitb4** [comment]
We can do it similar to baseweb table component, which reverses the column as well in RTL. https://baseweb.design/components/table/

**Comment by rohitb4** [comment]
@chasestarr can I implement it similar to baseweb table component?

**Comment by chasestarr** [comment]
Can you please list the tasks required to accomplish the feature? My guess is that this will be a significant effort and I'd like to make sure a merged PR sufficiently meets those requirements

**Comment by rohitb4** [comment]
These are the tasks I've identified, please let me know if I missed something.
- Change rendering positions for each cell based on the direction
- Change column/row highlight logic on hover of header/row cell based on the direction
- Change rendering of sort icons within the header cell based on the direction
- Change rendering of cell separator based on the first or last cell of the row
- Change positions of actions row elements based on the direction
- Change empty message/component positioning based on the direction
- Add scenario for rtl of the data table.

**Comment by chasestarr** [comment]
- reverse numerical column text-align
- filter UIs should be reversed

Thanks, a couple more that I thought of, but I think the list looks good

**Comment by rohitb4** [comment]
Filter UI is already right with RTL, because there is no absolute positioning.
If there are no other concerns, I will start implementing these.
