### ISSUE TITLE
Tags Input example on page has errors

### ISSUE THREAD

**Issue by reco** [uber/baseweb#2591]
Error Message: 

`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

https://codesandbox.io/s/pvhll?module=/example.js

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

<img width="1436" alt="Screen Shot 2020-01-08 at 11 53 50 AM" src="https://user-images.githubusercontent.com/18141/72005565-e2468680-321b-11ea-8703-90a503bc1252.png">

**Comment by nbdn** [comment]
Hi @gergelyke, I see nobody is assigned to this issue, can I work on it?

**Comment by gergelyke** [comment]
Please do, thank you @nbdn!

**Comment by alee8** [comment]
The fix for this issue is to wrap the InputReplacement component in the example.js with React.createRef as follows:

const InputReplacement = React.forwardRef(
  ({ tags, removeTag, ...restProps }, ref) => {

**Comment by nbdn** [comment]
@alee8 In fact you're right, but I think you miss that we need to pass the ref to the StyledInput component too (otherwise it will be undefined), I will make a relative PR in the next hours
