### ISSUE TITLE
[Select] Add enhancer support

### ISSUE THREAD

**Issue by nbdn** [uber/baseweb#2595]
In my usage, I found that start and end enhancers props are missing on the select component. 

Eg: for this component 
<img width="503" alt="Capture d’écran 2020-01-09 à 11 02 04" src="https://user-images.githubusercontent.com/32292384/72057921-876e6700-32cf-11ea-8786-542ec7281fc2.png">

Currently to achieve this, I have to tweak with the SearchIcon overrides and I have to handle the right button outside the Select component.

I think that it is a missing feature in the Select component comparing to the Input component, and for me the API must be the same in the usage.

## Feature description
Add start and end enhancers support to the select component

If you define the issue as valid, I can take the subject and make a relative PR.

**Comment by gergelyke** [comment]
The design recommendation for this use-case was to simply position the select next to the button with some padding, and we don't have guidelines for the design proposed above. 

With that said, I'd be happy to accept contributions to make the above use-case easier. What do you think  @nadiia @chasestarr ?

**Comment by chasestarr** [comment]
The nice thing about overrides is not needing to provide this kind of API, but I'm fine with it if others find the current pattern too painful. At some point this becomes a documentation issue. Why does the Select component shuttle overrides through to the sub-component but not the timezone selector? Lots of repeated work if we want to add it for every component

**Comment by chasestarr** [comment]
I'm going to close this PR since it's currently possible through overrides
