### ISSUE TITLE
Select dynamically inject options

### ISSUE THREAD

**Issue by apguan** [uber/baseweb#2617]
When trying to load in options dynamically from a request, the dropdown doesn't show the updated options available. 

[example demonstration](https://codesandbox.io/s/select-xp9bu?fontsize=14&hidenavigation=1&theme=dark) under  _example.js_

This example is a simple demonstration of the issue I'm facing when dynamically injecting options. I'd expect that changes in state should force a re-render, which would show an updated version of the dropdown. As I _search_, I should be seeing the number of options changing on each keypress. 
The only way to update it would be to use the `filterOptions` prop and return the same options as is. 

Is this normal behavior?

**Comment by chasestarr** [comment]
The select component will filter options based on the entered text. Is that not working? If you type in 'blue' I would expect to see one option in the dropdown. You may want to recreate something similar to the linked sandbox below to populate options asynchronously

https://codesandbox.io/s/select-un4b6

**Comment by apguan** [comment]
I'm not looking to filter the options, but I found that using the filterOptions prop was a work-around for what I needed. 

Why is it that if I were to dynamically pass options through like in my example, it doesn't work, but it works in your example? (bit of a under the hood question)

**Comment by chasestarr** [comment]
I'm not really sure what does not work about your example. If I type in a bunch of spaces, all of the dropdown options appear

**Comment by chasestarr** [comment]
Closing since it's been a couple weeks. Please add more detail if you're still experiencing the issue
