### ISSUE TITLE
LayoutGrid should allow for alternate CSS units.

### ISSUE THREAD

**Issue by sandgraham** [uber/baseweb#2626]
## Feature description

Currently `LayoutGrid` has props and theme properties for `gutters`, `margins`, and `gaps`. These take numbers and use them for calculating relative widths and such. These values are then fixed to pixels.

Example:
```js
// src/layout-grid/styled-components.js
{
  paddingLeft: `${calculateLength()}px`
}
```

The component should allow developers to specify other [CSS length units](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#Lengths) such as `rem`, `em`, etc.

Potentially the unit could be another theme property or a prop which specifies the unit (or both).

**Comment by karanisverma** [comment]
I would like to pick this up!  This is my first time on base web project, it would be great if you can point of a specific file where I should start looking to solve this problem.

**Comment by gergelyke** [comment]
thank you, just assign it to you @karanisverma - @sandgraham will be able to point you to the correct files, but I believe this is a good start: https://github.com/uber/baseweb/blob/master/src/layout-grid/styled-components.js

**Comment by sandgraham** [comment]
Hi @karanisverma, thanks for offering to help on this.

I think the ideal change is to update the `grid` section of the theme to accept a `unit` property, which can be a CSS unit (`em`, `rem`, etc) but defaults to `px`. Here is the [relevant file](https://github.com/uber/baseweb/blob/master/src/themes/shared/grid.js).

Then on the component side of things, update it to use that theme value. It might also be nice to add a prop for overwriting `unit` at the top level Grid/StyledGrid components so you can have an instance that uses `em` for some reason. Here is a [good starting point for that](https://github.com/uber/baseweb/blob/master/src/layout-grid/styled-components.js).

That said, feel free to play around with it and come up with other ideas- this is just how I would approach it.

**Comment by karanisverma** [comment]
@gergelyke thanks for assigning this issue,  @sandgraham Thanks a lot for information. I like your approach of building grid api and if required adding flexibility to have nested girds with different units.

I will start looking into these pointer first and update here if I have other ideas to solve this problem.

**Comment by karanisverma** [comment]
Hi @sandgraham, @gergelyke 
I have done some basic changes which allow users to specify alternate css units. I have a question around how are we going to handle default values for grid which are in px, for instance  in [grid.js](https://github.com/uber/baseweb/blob/master/src/themes/shared/grid.js) file 16, 36 etc represent px numbers. so should I create a function to convert px value to respective css units? I am sure about this bit.. would love to hear what do you guys think about this.

**Comment by karanisverma** [comment]
After spending some time I understood that.. if user want to give alternate css units, they have to also share custom gridGutters and gridMargins with respect to that css unit 
I tested with following values(converted default px to em) and seems to work just fine:

`gridGutters={[1,2,2]} gridMargins={[1,2,4]}`

Please confirm if my understand is correct or incorrect 😕

**Comment by karanisverma** [comment]
> After spending some time I understood that.. if user want to give alternate css units, they have to also share custom gridGutters and gridMargins with respect to that css unit
> I tested with following values(converted default px to em) and seems to work just fine:
> 
> `gridGutters={[1,2,2]} gridMargins={[1,2,4]}`
> 
> Please confirm if my understand is correct or incorrect 😕

I tried this approach and added docs for the same, since I am new to styled components I am having hard time to understand why on theme override is reflecting on all the components(as a result currently all components are using `em` as unit)  here is a file where I am overriding theme: [custom-css-unit](https://github.com/karanisverma/baseweb/blob/feat/%232626/alternate-css-units-for-LayoutGrid/documentation-site/examples/layout-grid/custom-css-unit.js) 

I would really appreciate some help on this 😂

**Comment by sandgraham** [comment]
Hi @karanisverma, we were on holiday yesterday- sorry for late reply.

> if user want to give alternate css units, they have to also share custom gridGutters and gridMargins with respect to that css unit

I agree. The defaults are based on pixels. If you want to use another unit it is pretty easy to update a few properties on the theme object.

> why on theme override is reflecting on all the components

That is actually exactly what we want! If you set theme grid values to `em` and update gutters and margins accordingly, then every `Grid` component should use those values as the defaults.

The idea is that you generally want to have a single grid specification that is used across your application. The theme is the perfect interface for declaring that specification. If for some reason you need to have an alternate grid spec, you can either pass down props to a single instance of Grid or you can create a new theme and `ThemeProvider` for a subtree of your application.

I'll take a look at the PR now and give more detailed feedback there.

**Comment by karanisverma** [comment]
@sandgraham thanks for the explanation. This really helps.. looking forward for feedback on PR. 🙌

**Comment by karanisverma** [comment]
> 
> That is actually exactly what we want! If you set theme grid values to `em` and update gutters and margins accordingly, then every `Grid` component should use those values as the defaults.
> 
> The idea is that you generally want to have a single grid specification that is used across your application. The theme is the perfect interface for declaring that specification. If for some reason you need to have an alternate grid spec, you can either pass down props to a single instance of Grid or you can create a new theme and `ThemeProvider` for a subtree of your application.

Oh! I understood. so while adding an documentation and example, I should pass CSS unit by props. Currently I was passing it by theme.
