### ISSUE TITLE
Click Popover should trap focus and return focus to trigger when closed

### ISSUE THREAD

**Issue by matthewharwood** [uber/baseweb#2633]
## General Summary

Popover with triggerType of "click" should follow the recommendations for dialogs and drawers in [WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices/#dialog_drawer).

[Codesandbox](https://codesandbox.io/s/statefulpopover-jswmu)

## Current Behavior

Currently when popover opens the popover does not trap focus.  When closing the popover focus is reset to top of document.

## Expected Behavior

Popover's Trigger should trap focus inside popover and closing the popover should return focus back to trigger.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | ^9.32.0  |
| React   |    ^16.8.6     |
| browser |   chrome   79  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.
Not a duplicate but perhaps similar to https://github.com/uber/baseweb/issues/1807

**Comment by gergelyke** [comment]
thankyou @matthewharwood - any chance you could contribute this to the library?

**Comment by matthewharwood** [comment]
I think I should have sometime to work on it next week.

**Comment by foodforarabbit** [comment]
@gergelyke I'm on @matthewharwood 's team so I'll coordinate with him to get this fixed
