### ISSUE TITLE
Provide utility function to compute color by name

### ISSUE THREAD

**Issue by tonioloewald** [uber/baseweb#2636]
## Problem

It's difficult to determine the computed value of a color from a Baseui theme at runtime (you can create a component, set its color, do some Javascript DOM fu to getComputedStyle and pull its color – but this involves fighting React every step of the way and you're still going to break if, say, the thing you're querying no longer gets assigned the color for some other reason (now it has a box-shadow and not a border).

## Scenario

Layer features in a map or Deck.gl overlay are specified in terms of Baseui theme colors.

## ProposedSolution

Something like:

```
getColorByName(name, format='rgba') // format = rgba|rgb|hex|...
```

**Comment by chasestarr** [comment]
Can you please add more detail? I'm not sure if I completely follow what purpose the utility function will serve. Is accessing a color from baseui's theme object not appropriate? For example, `theme.color.accent400` will give you a hex code that some npm packages can convert to other formats

**Comment by chasestarr** [comment]
Feel free to comment further, but I'm going to close this issue for now
