### ISSUE TITLE
Add a "native" option for select boxes

### ISSUE THREAD

**Issue by vicapow** [uber/baseweb#2638]
In some case with a really large number of select options, the baseUI can be laggy compared to native select options. It would be nice to have a "native" option to use the built in select option in these cases.

As a demo, checkout: https://codesandbox.io/s/select-similar-to-native-select-hzivn?fontsize=14&hidenavigation=1&theme=dark

**Comment by gergelyke** [comment]
hi @vicapow - would this example work for you? https://baseweb.design/components/select/#select-with-many-options

**Comment by vicapow** [comment]
Oh yes. This works. Sorry I missed it.
