### ISSUE TITLE
Missing Types for createThemed* styling utilility factories

### ISSUE THREAD

**Issue by LaurenReillyW2G** [uber/baseweb#2640]
## Current Behavior
Cannot import the createThemed* styling  utilities to use with typescript because they are missing types. Would prefer to not have to set the 'noImplicitAny' rule to false to use these. 

Not able to find/import styling utility factory functions without allowing 'any' types in ts.config
## Expected Behavior

Ideally I could import these createThemed* functions with no issue, provide them my typed custom theme and then use that type whenever I access the theme via these functions.
## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.37.0  |
| React   |    16.12.0     |
| browser |     chrome    |

Using TypeScript in the project.

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
thank you for reporting it @LaurenReillyW2G - any chance you'd be up to submitting a PR with the improvements?

**Comment by grrowl** [comment]
The DefinitelyTyped definitions for `styletron-react` might be a good reference/starting point: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styletron-react/index.d.ts

**Comment by grrowl** [comment]
Here you go buddies, this is based on `styletron-react`'s styles and `baseui`'s flow types. Feel free to incorporate the module overrides into base web:

```ts
import { StyletronComponent, StyleObject } from 'styletron-react'
import { createThemedStyled, createThemedWithStyle, createThemedUseStyletron } from 'baseui'
import { OurTheme } from './theme'

declare module 'baseui' {
  export interface ThemedStyleFn<Theme> {
    <C extends keyof JSX.IntrinsicElements | React.ComponentType<any>, P extends object, T = Theme>(
      component: C,
      style: (props: P & { $theme: T }) => StyleObject,
    ): StyletronComponent<Pick<React.ComponentProps<C>, Exclude<keyof React.ComponentProps<C>, { className: string }>> & P>

    <C extends keyof JSX.IntrinsicElements | React.ComponentType<any>>(component: C, style: StyleObject): StyletronComponent<
      Pick<React.ComponentProps<C>, Exclude<keyof React.ComponentProps<C>, { className: string }>>
    >
  }
  export function createThemedStyled<Theme>(): ThemedStyleFn<Theme>

  export interface WithThemedStyleFn<Theme> {
    <C extends StyletronComponent<any>, P extends object, T = Theme>(
      component: C,
      style: (props: P & { $theme: T }) => StyleObject,
    ): StyletronComponent<React.ComponentProps<C> & P>
    <C extends StyletronComponent<any>>(component: C, style: StyleObject): StyletronComponent<React.ComponentProps<C>>
  }

  export function createThemedWithStyle<Theme>(): WithThemedStyleFn<Theme>
}

export const styled = createThemedStyled<OurTheme>()
export const withStyle = createThemedWithStyle<OurTheme>()
export const useStyletron = createThemedUseStyletron<OurTheme>()
```

**Comment by chasestarr** [comment]
I believe this was completed by https://github.com/uber/baseweb/pull/2717 but let me know if the issue is still unresolved
