### ISSUE TITLE
Forward `className` / `id` through to root HTML element

### ISSUE THREAD

**Issue by ericsoco** [uber/baseweb#2649]
##  Feature description

Currently, Base Web components (well, at least `Panel`, I haven't looked much into the others) don't forward className to their child root HTMLElements. This makes it prohibitively difficult to apply class names to them.

Our use case is a bit idiosyncratic: our integration test suite uses HTML `class`es and `id`s for Puppeteer selectors (which are just Javascript selectors, i.e. `querySelector()`), so we can't target Base Web components in our integration tests.

However, there are probably other, more general use cases, such as styling via raw CSS, that could benefit from this approach. I would strive to avoid styling via both Styletron / CSS-in-JS and raw CSS, but using third-party libraries sometimes requires this kind of ad-hoc piecing things together.

**Comment by gergelyke** [comment]
@ericsoco - you can use the overrides to provide ids to the components: https://baseweb.design/guides/understanding-overrides/#introducing-overrides

would something like this work for you?

**Comment by ericsoco** [comment]
Yes!

```
<Panel overrides={{props: {className: 'foo'}}} ... />
```

Does the trick. Thanks!
