### ISSUE TITLE
Missing addEventListener and removeEventListener for Button type, Button should extend HTMLButtonElement

### ISSUE THREAD

**Issue by ajbogh** [uber/baseweb#2652]
The Button element does not include types for addEventListener or removeEventListener, so Typescript will complain when using those functions.

## Current Behavior

Typescript shows an error when using a HTMLButtonElement property that is not part of Button:

"Property 'addEventListener' does not exist on type 'Button'.ts(2339)"

The consumer cannot create a new type which extends both Button and HTMLButtonElement because the focus() function on Button doesn't match the focus function on HTMLButtonElement. If Button extended HTMLButtonElement then they would have to match.

## Expected Behavior

Button should extend HTMLButtonElement

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.42.0  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
thank you for opening the issue @ajbogh - any chance you can help to contribute a fix for this?

**Comment by ajbogh** [comment]
> thank you for opening the issue @ajbogh - any chance you can help to contribute a fix for this?

I'll see what I can do but I have to timebox the problem. If I don't link a PR then I'll keep this open for someone else.

**Comment by gergelyke** [comment]
thank you

**Comment by ajbogh** [comment]
I looked into this for a little time but couldn't come up with a good solution. Extending the interfaces at a naive level doesn't seem to fix the problem. Admittedly, I lack the advanced knowledge of Typescript to define a more complex solution.

**Comment by gergelyke** [comment]
@ajbogh can you help me understand what's your use case for the `addEventListener` handler?

**Comment by gergelyke** [comment]
that makes sense, thank you for the additional info!
