### ISSUE TITLE
[Treeview] Ability to customize open/close overrides based on item

### ISSUE THREAD

**Issue by matthewharwood** [uber/baseweb#2665]
## Feature description
I'm looking to create a TreeView component where each node could be customized. Today this is not possible without some pretty ugly hacks.

I can see two API Designs to make this work.

1 - The current API renders everything via initial data. This approach can work; however, each node does not have access to each entry of the initial data as props.  Each entry could be used to override and create each variants from the overrides>component api.

[Codesandbox demo inflexible api](https://codesandbox.io/s/overrides-usage-2qkpo)

2 - Another API could follow Material design; the API design of Material TreeView is a more declarative api similar to Base Accordion:

[MaterialUI's Custom Tree View Example](https://codesandbox.io/s/ujp8m)

**Comment by chasestarr** [comment]
`label` also accepts a React.Node. Does this example meet your needs? https://codesandbox.io/s/overrides-usage-t5oy9

**Comment by matthewharwood** [comment]
@chasestarr I think this could almost work!  Can we change the chevron size from at a node level?  In my implementation we need to make it larger to match larger Labels.

https://imgur.com/HLFsdEf

**Comment by chasestarr** [comment]
I can't think of a work-around. The feature will need to be added in some way

**Comment by matthewharwood** [comment]
What protocol should  I rewrite this question. Or close this one and write another for this overridable icon feature?

**Comment by chasestarr** [comment]
Please comment with specific requirements beyond the edited title

**Comment by foodforarabbit** [comment]
I'll handle this one

**Comment by foodforarabbit** [comment]
- entirely customizable labels
- pass shared props / item props to label function?
- renderAll
- prop to allow only single branch open at a time
