### ISSUE TITLE
Menu divider

### ISSUE THREAD

**Issue by supersonicclay** [uber/baseweb#2690]
## Feature description

How can I add a dividing line to a menu similar to bootstrap's Dropdown divider?
https://getbootstrap.com/docs/3.3/components/#dropdowns-divider

![image](https://user-images.githubusercontent.com/469582/73022206-52413900-3de6-11ea-8ba8-2cef86a59551.png)

Is there an ability to provide overrides on a per-item basis?

I got pretty close with this, but I'm wondering if there's a better way:
```js
items={[
    {label: 'Action'},
    {label: 'Another action'},
    {label: 'Something else here'},
    {label: <div style={{borderBottom: '1px solid #e2e2e2', marginLeft: '-16px', marginRight: '-16px'}} />},
    {label: 'Separated link'},
 ]}
```

![image](https://user-images.githubusercontent.com/469582/73025617-270e1800-3ded-11ea-8bb5-d36f70b15812.png)

**Comment by chasestarr** [comment]
Design hasn't come to us with requirements for this feature so a top-level api has not been considered. Here is an example of how to configure overrides to achieve what you're looking for: https://codesandbox.io/s/statefulmenu-5m6l3

Also here is an example of grouping items: https://baseweb.design/components/menu/#menu-with-grouped-items

**Comment by chasestarr** [comment]
I'm going to close this issue as it's not an approved pattern by base web designers, but I'll raise the idea with them
