### ISSUE TITLE
[Documentation] Props not extracted in production

### ISSUE THREAD

**Issue by raunofreiberg** [uber/baseweb#2698]
## Current Behavior

Hovering over the component name in the Editor component does not show the props extracted by `extract-react-types`

![image](https://user-images.githubusercontent.com/23662329/73085177-f4d8e500-3ed6-11ea-9240-193e36c73afe.png)

https://baseweb.design/components/button/

## Expected Behavior

Props should be shown:

![image](https://user-images.githubusercontent.com/23662329/73085160-ee4a6d80-3ed6-11ea-8a68-af2284695534.png)

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | n/a  |
| React   |    n/a     |
| browser |   Version 79.0.3945.130 (Official Build) (64-bit)      |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by raunofreiberg** [comment]
cc @tajo

**Comment by gergelyke** [comment]
I am looking into this

**Comment by raunofreiberg** [comment]
If it's of any help, then the props were extracted properly in the [deploy preview of #2686](https://baseweb-git-fix-modal-closeable.uber-ui-platform.now.sh/components/button).

The PR after (#2688) would then [display the issue.](https://baseweb-git-update-my-libs.uber-ui-platform.now.sh/components/button)

**Comment by gergelyke** [comment]
After a quick look, it seems like the issue is present in the netlify deploys, but not on the zeit bulds (we use netlify for the main domain, and zeit for the versioned docs site)

**Comment by gergelyke** [comment]
I was wrong, it worked on netlify before too https://5e29cc00fef63c2f4b85fce9--baseui.netlify.com/components/button/

**Comment by raunofreiberg** [comment]
I built the documentation locally and served it, and it work. So the issue has something to do with the deployment.

**Comment by raunofreiberg** [comment]
The issue seems to have re-appeared in production: https://baseweb.design/components/button/

**Comment by gergelyke** [comment]
checking

**Comment by raunofreiberg** [comment]
I'm starting to sound like a broken record, but to me, the issue has surfaced again: https://baseweb.design/components/button/ 🙈

**Comment by gergelyke** [comment]
I've created a story for our next sprint - sorry about the inconvenience
