### ISSUE TITLE
[Menu/MenuWithChildren] Should be SEO Friendly via the renderAll API

### ISSUE THREAD

**Issue by matthewharwood** [uber/baseweb#2702]
The [Menu](https://baseweb.design/components/menu/) component does not render its List or Options until the user interacts with the StatefulMenu. This prevents content from being crawled properly because search engines don't interact with components.

Could we get a similar [`renderAll`](https://baseui.netlify.com/guides/seo/#tab) prop of Tabs or Accordion into the Menu and MenuWithChildren component so that Options within a menu are SEO friendly?

**Comment by chasestarr** [comment]
The similarity between this and the similar issues are that they all use `Popover` under-the-hood. Maybe there can be an approach on the popover component that can render the content hidden. It would be nice to solve all of those problems at once if possible

**Comment by foodforarabbit** [comment]
I'll handle this one
