### ISSUE TITLE
[Drawer] Should be SEO Friendly via the renderAll API

### ISSUE THREAD

**Issue by matthewharwood** [uber/baseweb#2703]
The [Drawer](https://baseweb.design/components/drawer/) component does not render its DrawerBody  until the user interacts with the Drawer. This prevents content from being crawled properly because search engines don't interact with components.

The [`renderAll`](https://baseweb.design/guides/seo/#tab) API of Tabs or Accordion should be moved into the Drawer component, so that it is SEO friendly.

**Comment by foodforarabbit** [comment]
I'll handle this one
