### ISSUE TITLE
[Popover] Should be SEO Friendly via the renderAll API

### ISSUE THREAD

**Issue by matthewharwood** [uber/baseweb#2704]
The [Popover](https://baseweb.design/components/popover/) component does not render its Body  until the user interacts with the Popover. This prevents content from being crawled properly because search engines don't interact with components.

The [`renderAll`](https://baseweb.design/guides/seo/#tab) API of Tabs or Accordion should be moved into the Popover component, so that it's SEO friendly.

**Comment by foodforarabbit** [comment]
I'll handle this one
