### ISSUE TITLE
Add shared prop "$isExpanded" for component Unstable_StatefulTreeView

### ISSUE THREAD

**Issue by hlokavarapu** [uber/baseweb#2720]
## Feature description

For the base web component Unstable_StatefulTreeView, would it possible to add a shared prop "$isExpanded"? 

One benefit is that, this feature would allow one to override TreeItem's background color using a style function on the condition that a given node is expanded. 

This feature request is similar to $isSelected state prop for component StatefulList.

Thanks!!

**Comment by gergelyke** [comment]
@hlokavarapu I think this is addressed in one of the open PRs: https://github.com/uber/baseweb/pull/2716/files#diff-f2183ec5c2cc8724d1ad6728bec2260dR15

cc @foodforarabbit

**Comment by foodforarabbit** [comment]
I added the ability to override TreeLabel which is a component that renders the entire label - the expand / collapse icons, the icon container and the label itself. This component receives a prop isExpanded which you can use.

I looked briefly into copying over the sharedStyleProps pattern from other components but it looks like more rearrangement and planning of types would be helpful, its not too clear if there is a common set of styling props or if you'd need multiple sets, and what components the styling props might need to be applied to, and what props should be shared, etc.... 

For now, that PR should have what you need to style the tree node based on isExpanded, although in a slightly round-about way. 

I can create another VERY BASIC pr to add $isExpanded and $hasChildren to IconContainer, ExpandIcon, CollapseIcon, and TreeItemContent
