### ISSUE TITLE
[Popover] autoFocus property isn't copied from the StatefulPopover

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#2725]
v9.46.0

It appears that the autoFocus property isn't copied from the StatefulPopover to the Popover. (it isn't included in the popoverProps that gets passed to the Popover).

You can see this on the documentation site.  [here](https://baseweb.design/components/popover/?code=import%20*%20as%20React%20from%20%22react%22%3B%0Aimport%20%7B%20StatefulPopover%20%7D%20from%20%22baseui%2Fpopover%22%3B%0Aimport%20%7B%20Input%20%7D%20from%20%22baseui%2Finput%22%3B%0Aimport%20%7B%20Button%20%7D%20from%20%22baseui%2Fbutton%22%3B%0A%0Aexport%20default%20()%20%3D%3E%20%7B%0A%20%20return%20(%0A%20%20%20%20%3CStatefulPopover%0A%20%20%20%20%20%20content%3D%7B()%20%3D%3E%20(%0A%20%20%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%20%20Hello%2C%20there!%20%F0%9F%91%8B%0A%20%20%20%20%20%20%20%20%20%20%3CInput%20placeholder%3D%22Focusable%20Element%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%20)%7D%0A%20%20%20%20%20%20focusLock%0A%20%20%20%20%20%20returnFocus%0A%20%20%20%20%20%20autoFocus%3D%7Bfalse%7D%0A%20%20%20%20%3E%0A%20%20%20%20%20%20%3CButton%3EClick%20me%3C%2FButton%3E%0A%20%20%20%20%3C%2FStatefulPopover%3E%0A%20%20)%3B%0A%7D)
Setting autoFocus={false} still causes focus to shift to the text box.
Simply unchecking the autoFocus checkbox will just cause the attribute to not be added to the JSX, which will cause it to use the default value, true

**Comment by chasestarr** [comment]
cc @foodforarabbit since it seems related to https://github.com/uber/baseweb/pull/2650

**Comment by Xiot** [comment]
Thanks for the super quick turnaround
