### ISSUE TITLE
[select] filterOutSelected not working

### ISSUE THREAD

**Issue by hc-codersatlas** [uber/baseweb#2739]
FilterOutSelected option not working

## Current Behavior

Doesn't filter

## Expected Behavior

Filters

## Your Environment

As per example in https://baseweb.design/components/select/ (also doesn't work locally)

Tested in latest Chrome.

**Comment by gergelyke** [comment]
hi @hc-codersatlas! `filterOutSelected ` is only taken into account when using a `multi` select - I'll update the docs to reflect this
