### ISSUE TITLE
Invisible notification when used in popover

### ISSUE THREAD

**Issue by supersonicclay** [uber/baseweb#2755]
https://codesandbox.io/s/invisible-notification-889kq

## Current Behavior

![image](https://user-images.githubusercontent.com/469582/73314567-6c668700-41eb-11ea-9acc-a76904bad6a6.png)
`Notification` content is blank when used as popover content

## Expected Behavior

![image](https://user-images.githubusercontent.com/469582/73314590-80aa8400-41eb-11ea-86c0-b473bb0cf5a5.png)

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.47.2  |
| React   |         |
| browser | Chrome        |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
@foodforarabbit it seems to be broken because of this diff: https://github.com/uber/baseweb/pull/2650

I wonder, why that might be? 🤔

**Comment by foodforarabbit** [comment]
hmm not sure, if you add 
    `focusLock={false}`
to `StatefulPopover`
then it shows up again. 

I will debug it later tonight

**Comment by nadiia** [comment]
It clears `animateInTimer` on focus triggered by `focusLock` https://github.com/uber/baseweb/blob/master/src/toast/toast.js#L115

**Comment by houmark** [comment]
I also have a modal where the Notification is not showing (`opacity: 0`) due to this regression. Is the PR not good to release?

**Comment by gergelyke** [comment]
I think we should add some test coverage first, to make sure we don't run into this issue again

**Comment by houmark** [comment]
I agree, but this is a regression that potentially is breaking existing installations in the wild. It "broke" ours - we did a hot patch with `opacity: 1` as an override, but this may affect others way worse.

**Comment by houmark** [comment]
So the fix could release and then a follow up with more tests covering it all imho.

**Comment by gergelyke** [comment]
that sounds reasonable to me - what do you think @nadiia ?
