### ISSUE TITLE
[Layout-grid] Adding style overrides

### ISSUE THREAD

**Issue by parigi-n** [uber/baseweb#2800]
I can't find any possibility to overrides anything in the LayoutGrid component like there is in all  others Base web components.
I would like to add some css properties directly on the div created by a Cell component, that i can't put in the children.

There should a possibility to overrides style in Cell component, or at least use the $style in StyledCell.

Thanks !

**Comment by sandgraham** [comment]
We could probably add a top-level `overrides` to Grid for this purpose.

```js
<Grid overrides={{
  Cell: {
    style: {/* ... */}
  },
  Grid: {
    style: {/* ... */}
  }
}}>
  <Cell />
  <Cell />
  <Cell />
</Grid>
```

Curious about your use case though. What sort of CSS are you applying? Also, is this CSS something you apply to only one Cell or need applied to all Cells?

**Comment by parigi-n** [comment]
Thanks for your quick answer @sandgraham 😄 
For my specific case, I need to apply property 'position: sticky' (on a specific media-query) to one Cell.

**Comment by parigi-n** [comment]
To be more specific, i used overrides on SideNavigation with media queries so that i can be more usable in mobile devices
![image](https://user-images.githubusercontent.com/20981240/74148494-daf10f00-4c05-11ea-9fa7-30e77026104d.png)
It's displayed inside a LayoutGrid.
I would like this to be become a sticky header in mobile

**Comment by sandgraham** [comment]
@parigi-n Gotcha. I think there is a legitimate case to add style overrides to `Grid` & `Cell`. The current API is a bit too restrictive.

However I wonder if you could do something like this for your current design: https://codesandbox.io/s/sticky-cells-n373j

The idea being that you can use custom CSS on an element wrapping the `Grid` component (`Outer` in example) and elements directly inside of `Cell` components (`Inner` in example) to achieve most of what you would do by applying CSS _directly_ to the `Grid`/`Cell` components.

**Comment by parigi-n** [comment]
@sandgraham Yeah i think so too, not just for my case, but more because of baseui components policy to be so open to customization.
Thanks for taking the time to search a solution !
However, in your exemple, the whole Grid is sticky. I need only one Cell sticky over the Grid, as this navbar get back to side (thanks to responsive span values), without being sticky, in desktop resolution
![image](https://user-images.githubusercontent.com/20981240/74227022-db4ce100-4cbd-11ea-96b6-642d4b309eab.png)

**Comment by parigi-n** [comment]
@sandgraham Thanks for the PR, you rock ! Reviewed the PR and it seems to properly add all the functionalities i described 😃
