### ISSUE TITLE
Button will capture space key after being clicked

### ISSUE THREAD

**Issue by tangye1234** [uber/baseweb#2801]
## Current Behavior

When I click a `Button`, my pre-registered onkeydown listener for document will not be invoked upon I press 'space' key, I guess it is captured by the `Button` component and being stopped from propagation. Why and how can I avoid that?

## Expected Behavior

The component won't capture the space key event and swallow it

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v8.51.0  |
| React   |  v16.8     |
| browser |   chrome 79   |

- [*] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Can you edit this codesandbox to reproduce the issue? https://codesandbox.io/s/button-kjo4t
