### ISSUE TITLE
maxLength attribute does not work on input fields

### ISSUE THREAD

**Issue by AbdelOufkir** [uber/baseweb#2804]
## Current Behavior

Adding a maxLength attribute to an Input field seems to be not working since the number of characters can be exceeded in that field

## Expected Behavior

As soon as the number of the characters hits the maxLength value the input field should stop accepting any additional input and only allow for editing the entered value

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.22.0  |
| React   | v16.11.0  |
| browser | chrome |

- [v] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Can you please add a reproducing codesandbox? This should get you started: https://codesandbox.io/s/6vfqv?module=/example.js

**Comment by chasestarr** [comment]
Closing, but feel free to continue the conversation with a reproduction

**Comment by kirbycool** [comment]
@chasestarr This is still an issue. Trying typing in the inputs here https://codesandbox.io/s/input-lpfxg?file=/example.js
