### ISSUE TITLE
StyledTable crashes when nesting a table using span

### ISSUE THREAD

**Issue by houmark** [uber/baseweb#2822]
## Current Behavior

Having a Grid Table with a nested table above, where doing a `gridColumn="span 5"` crashes using the latest `styletron-react` and `styletron-engine-atomic`:

```
TypeError
Cannot read property 'split' of undefined
```

This is a forked demo of the documentation site, but with upgraded packages to the latest available version from npm (click on a row arrow to expand it):
https://codesandbox.io/s/nested-table-bulyr

This seems to be a problem in `styletron-engine-atomic` between version 1.4.1 and 1.4.2 but as this affects Baseweb if those packages are updated, I thought I'd start by reporting it here.

I'll continue to research this one myself, but I'll probably downgrade `styletron-engine-atomic` for now to keep our production build working.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.52.0  |
| React   |    Latest     |
| browser |     Any    |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by houmark** [comment]
This seems to be related to this commit in `inline-style-prefixer` (styletron-react depends on it) which now expects a `/` in the `gridColumn` property to split on or it will fail:
https://github.com/robinweser/inline-style-prefixer/pull/186/files#diff-5b100f16ea6eb23ee5e65a270c3c0873R54

A workaround seems to be changing `span 5` to `1 / span 5` but that should not be needed.

**Comment by houmark** [comment]
Alternatively the long hand `gridColumnStart: 1` and `gridColumnEnd: span 5` will produce the same result. I guess all Baseweb needs to do, is update any example using the shorthand to ensure it does not break with newer versions of `inline-style-prefixer`.

**Comment by houmark** [comment]
This seems to be on the radar of `inline-style-prefixer` thanks to @matthewharwood:

https://github.com/robinweser/inline-style-prefixer/issues/176

**Comment by matthewharwood** [comment]
https://github.com/styletron/styletron/issues/358 For visibility.

**Comment by matthewharwood** [comment]
I made a diff to fix this: 
https://github.com/robinweser/inline-style-prefixer/pull/190

**Comment by houmark** [comment]
> [styletron/styletron#358](https://github.com/styletron/styletron/issues/358) For visibility.
> 
> @houmark My solution for now is to use yarn resolutions
> 

We only use this span technique two places, so we decided to fix it by adding the correct shorthand "1 / span 5". Happy to see you submitted a PR.

**Comment by matthewharwood** [comment]
@houmark @chasestarr the robinweser/inline-style-prefixer#190 has been landed

**Comment by chasestarr** [comment]
I think this can be safely closed since we specify `styletron-engine-atomic` to be the latest minor version in `package.json`. Thank you for putting in the upstream pr @matthewharwood
