### ISSUE TITLE
[Accordion] Document how to create a custom panel component

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#2862]
It's unclear that props need to be shuttled through a custom wrapper to a `Panel` component. We should add an example that shows this on the docs site

[sandbox](https://codesandbox.io/s/accordion-u5q0q)

**Comment by gwuah** [comment]
Hey @chasestarr, I want to pick this up. Where do I start from?
There's not much in the `contribution.md` file relative to improving documentation.

**Comment by chasestarr** [comment]
Hi @gwuah thank you for looking into improving the documentation. You will want to run the `yarn documentation:dev` command if you are on windows (this does not recompile on source code changes) or `yarn documentation:dev:watch` if you are on mac/linux. This should start the page locally at `localhost:3000`

This is a good example to base your work on: https://github.com/uber/baseweb/pull/2491/files

**Comment by gwuah** [comment]
Hey @chasestarr , thanks for your patience with my initial pull request.
I want to take on this issue(https://github.com/uber/baseweb/issues/2825) next.
Hope it's up for grabs?

**Comment by chasestarr** [comment]
> Hey @chasestarr , thanks for your patience with my initial pull request.
> I want to take on this issue(#2825) next.
> Hope it's up for grabs?

Yes Thanks. Please write a comment on that issue. Github didn't work properly to assign it to you
