### ISSUE TITLE
[Block] Setting `className` on a `Block` element results in a TypeScript error

### ISSUE THREAD

**Issue by jonsadka** [uber/baseweb#2872]
Setting `className` on a `Block` element results in a TypeScript error:

https://codesandbox.io/s/block-basic-usage-dny94

<img width="649" alt="Screen Shot 2020-02-18 at 10 47 12 AM" src="https://user-images.githubusercontent.com/6504944/74767621-0d20f300-523c-11ea-9780-c3a027adfe7b.png">

## Current Behavior

TypeScript error

## Expected Behavior

No TypeScript error

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
I think this is by design? Currently, I don't think any component supports this

**Comment by jonsadka** [comment]
Seems odd that this `className` wouldnt be a supported prop / attribute since it's available on nearly all JSX elements. 

I know it can be set as an override but this behavior is inconsistent with FlowJS which does not throw an error

**Comment by jonsadka** [comment]
@gergelyke @chasestarr any further thoughts about this? 

Seems odd I'd get an error doing something like:
```javascript
import {useStyletron} from 'baseui';

const [css] = useStyletron();
<Block className={css({color: 'red'})}/>
```

**Comment by chasestarr** [comment]
I believe it's just because it's left out of the TS props definition here https://github.com/uber/baseweb/blob/master/src/block/index.d.ts#L215 I can put up a diff later today

**Comment by nick-khoury** [comment]
> I believe it's just because it's left out of the TS props definition here https://github.com/uber/baseweb/blob/master/src/block/index.d.ts#L215 I can put up a diff later today

can you expose the `id` prop as well?

**Comment by jonsadka** [comment]
> > I believe it's just because it's left out of the TS props definition here https://github.com/uber/baseweb/blob/master/src/block/index.d.ts#L215 I can put up a diff later today
> 
> can you expose the `id` prop as well?

@nick-khoury if you update to the latest version of BaseWeb you should see the `id` prop supported (was part of https://github.com/uber/baseweb/pull/4081)

**Comment by x-EricH-x** [comment]
Hi, sorry for reviving this thread, I notice `id` and `className` is not exposed on other components as well,
it is by design or just missing TS definition like this one?
