### ISSUE TITLE
[Select] option with href property renders as anchor in dropdown

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#2884]
This is an unintended side-effect of https://github.com/uber/baseweb/pull/2631 which adds anchor rendering to the `Menu` component. I can't think of a use-case for rendering the anchor in the select dropdown. We should probably disable this feature when rendered from the select component since it's somewhat of a regression on existing applications

## Current Behavior

options with the `href` property are rendered as an anchor in the dropdown
https://codesandbox.io/s/select-xr8t9

## Expected Behavior

options should not be rendered as anchors

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.55.x  |

**Comment by rohitb4** [comment]
Do existing applications use href within select, I thought #2631 introduced href in menu and select.

**Comment by chasestarr** [comment]
I edited the original message to be more clear. It doesn't make much sense to render an anchor element in a select dropdown. The select component is supposed to act similarly to html select element, which does not cause a page navigation when an option is clicked
