### ISSUE TITLE
how to use KIND for button and notifications?

### ISSUE THREAD

**Issue by png-prakash** [uber/baseweb#2902]
import { Button, KIND, SIZE } from "baseui/button";
import {Notification, KIND} from 'baseui/notification';

I got error like Parsing error: Identifier 'KIND' has already been declared

If I remove KIND in notification, KIND not working

**Comment by gergelyke** [comment]
you can do something likethis

```
import { Button, KIND as ButtonKind, SIZE } from "baseui/button";
import {Notification, KIND as NotificationKind} from 'baseui/notification';
```
