### ISSUE TITLE
Open Source the Figma File

### ISSUE THREAD

**Issue by trevorwhealy** [uber/baseweb#2955]
## Feature description
To improve the adoption of the design library by other companies, it would be great if the Figma file could be open-sourced and shared so that designers could experiment with the library components, and not be forced to recreate them all manually.

It's nice that there are so many plug-and-play React components, but if the designers cannot easily plug-and-play the mocks into Figma, then they'd need to recreate them, which will take a lot of time and effort.

**Comment by gergelyke** [comment]
@trevorwhealy you can find it in this blogpost: https://baseweb.design/blog/base-figma-community/ 

I'll update the doc site to have more links to it

**Comment by gergelyke** [comment]
Also, feel free to reopen for further discussion
