### ISSUE TITLE
Select and other components using Menu / MenuStatefulContainer throws warnings

### ISSUE THREAD

**Issue by houmark** [uber/baseweb#2980]
## Current Behavior

In version 9.60.1 or the version before, probably due to https://github.com/uber/baseweb/pull/2947 but I could be wrong, changes have resulted in warnings being thrown both on load of a Select (and other components using Menu / MenuStatefulContainer as sub-components) when loading and when opening the Select.

This is the sandbox of the current Select on the demo page:
https://codesandbox.io/s/qxsqy

1. Open Sandbox console
2. Notice LayersManager warnings
3. Click to open dropdown
4. Notice warning: `Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.`

This is not meant as critique in any way at all (I love Baseweb, I think it's overall super stable, releases and bugfixes are crazy fast and I'd wish I had time and knowledge to participate more, but I'm a one-man show here, just trying to keep up to speed with our (not so) small platform), and my knowledge on this subject is very limited, so with the risk of sounding stupid, my question in relation to this goes:

In a couple of the most recent versions, I have noticed similar warnings thrown (#2962 specifically). Are these warnings not caught due to the limited possibility of testing or due to missing tests on the component?

I would think that for example `Select` is tested and the on-load warnings should have been caught and prevented merge of the commit? I'd also think that `Select` is tested to open, select and item and ensure that the value is correct. And in the process of doing that, the test should catch any warnings thrown and fail?

If directions on what would be possible and optimal are given, then I may be able to start participating by increase test coverage on warnings like these on the main components, because it seems the one main point where things are falling through the cracks creating possible regressions at this time.

## Expected Behavior

No warnings. I did test v9.61.0 and the warnings are still present (the sandbox uses latest releases Baseweb).

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.60.1+ |
| React   |     16.13    |
| browser |     Chrome 80.x    |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Thanks for the report @houmark. I think the reason this slips through is the over-reliance on automated tests which do not fail CI on these kind of warnings. 

One next step we can take is try to `inbox-zero` the present warnings in unit-tests and review test log output before merging changes. I wonder if there is a way to fail on warnings/errors from react?

**Comment by houmark** [comment]
Thanks for your feedback @chasestarr.

It seems to me that those types of warnings are slipping through quite often and those can be potentially breaking for some users. Warning should not be, and if react crashes due to an error, I would assume the test will pick that up.

It's important to note that when React is running in production mode, those warnings are not displayed in the console, so React needs to be in development mode in the tests for the warnings to be thrown.

**Comment by chasestarr** [comment]
Landed a fix for the bug, and we've got some plans for failing CI on react errors
