### ISSUE TITLE
[Input] add 'maxLength' prop at top level

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#2990]
Applying `maxLength` as an override is currently possible, but it's unclear that this does not get forwarded to the underlying input element. We should add this the `Input` component top-level api.

https://codesandbox.io/s/input-eumbf

**Comment by kimasenbeck** [comment]
We discussed this in https://github.com/uber/baseweb/issues/3449
I'll look to have a PR out as soon as I can.
