### ISSUE TITLE
Feature request for `withWrapper` extension

### ISSUE THREAD

**Issue by chrisirhc** [uber/baseweb#2998]
## Feature description
I would like to wrap some baseweb components, such as the Link.
However, using withWrapper `from 'styletron-react'` doesn't work as expected.

Repro:
```js
export const FlexibleLink = withWrapper(
  StyledLink,
  Styled => ({to, isExternal, children}: Props) => {
    // do some logic
      return (
        <Styled href={to} target="_blank">
          {children}
        </Styled>
      );
})
```

Perhaps we need a `withWrapper` export on baseweb to fulfill such use cases?

**Comment by sandgraham** [comment]
@chrisirhc I actually added this last week to fix some other issues. It extends the styletron `withWrapper` to include `$theme` in the props (similar to our `styled` and `withStyle` utilities).

You can try it by importing it like so:
```js
import {withWrapper} from "baseui/styles"
```

The types are pretty weak right now but it should work for what you are doing in that example.

**Comment by chrisirhc** [comment]
Yep tested that it worked. Though there's a lint rule recommending users not to import from internals.

**Comment by sandgraham** [comment]
Awesome - the lint rule should be fine with `baseui/styles`. Anything more than 2 "levels deep" is considered internal. Does the lint rule fire for this?

That said: I'll add to main import along with other utils to be consistent.

**Comment by chrisirhc** [comment]
Yep, got:
```
  5:1  warning  Please limit imports to "baseui" or one level deep modules such as "baseui/button". Importing more than one level deep is dangerous as source code may change in breaking ways without notice  baseui/no-deep-imports
```

**Comment by sandgraham** [comment]
Hm I can't reproduce with `import {withWrapper} from "baseui/styles"` but it should be available from `"baseui"` directly now as well if that helps.
