### ISSUE TITLE
[Tree-view] Replace index with id as key

### ISSUE THREAD

**Issue by joginder07** [uber/baseweb#2999]
Index of tree node is set as key which needs to be replaced with getId(node).

## Current Behavior

On tree node mount, node id is stored in ref. When a node is replaced which has new id componentDidMount is not invoked because index is same and therefore new id is not stored in ref.

## Expected Behavior

Node id should be set as key. Secondly, we need to remove ref in componentWillUnmount. 

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.62.0  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gwuah** [comment]
@chasestarr can I pick this up?
