### ISSUE TITLE
[Feature Request] CSS Longhand helper functions

### ISSUE THREAD

**Issue by hackily** [uber/baseweb#3006]
## Feature description
Since the official recommendation with baseui is to use longhand properties whenever possible, it would help developer ergonomics to have a utility that expands shorthand.

Right now, a user would need to type all of this out
```
Case 1:
marginTop: theme.sizing.scale600,
marginLeft: theme.sizing.scale600,
marginRight: theme.sizing.scale600,
marginBottom: theme.sizing.scale600

Case 2:
marginTop: theme.sizing.scale600,
marginLeft: theme.sizing.scale200,
marginRight: theme.sizing.scale200,
marginBottom: theme.sizing.scale600

Case 3:
marginTop: theme.sizing.scale200,
marginLeft: theme.sizing.scale400,
marginRight: theme.sizing.scale600,
marginBottom: theme.sizing.scale800
```
But this could be simplified with a utility to something resembling shorthand
```
Case 1:
...longhandHelper('margin', theme.sizing.scale600),

Case 2: 
...longhandHelper('margin', theme.sizing.scale200, theme.sizing.scale600),

Case3:
...longhandHelper('margin', theme.sizing.scale200, theme.sizing.scale400, theme.sizing.scale600, theme.sizing.scale800
```

The first parameter could take in other types, such as `padding`, `border`, `border-radius`, etc.

Alternatively, several utility functions could be exported instead
```
...margin(theme.sizing.scale200, theme.sizing.scale600)
...padding(...),
...borderRadius(...)
...border(...)
```

**Comment by chasestarr** [comment]
Hi there, thanks for submitting the issue. This can be reasonably built as a utility in application code or you could explore some open source modules like https://github.com/mahirshah/css-property-parser#expandshorthandpropertyproperty-string-value-string-recursivelyresolvefalse-includeinitialvaluesfalse-object

**Comment by chasestarr** [comment]
Going to close this one. Our suggestion is to use a library/custom utility
