### ISSUE TITLE
[Datepicker] backspace should clear value

### ISSUE THREAD

**Issue by matthewschwegler** [uber/baseweb#3045]
Sandbox - https://baseweb.design/components/datepicker/

## Current Behavior
When I type backspace into the current date picker to clear a selection, it will auto fill in front of my deletes with the date "2001/02/01"

## Expected Behavior
When I type backspace into the current date picker to clear a selection, I expect to see a blank form for me to type a new date

## Your Environment

Testing in chrome on - https://baseweb.design/components/datepicker/

| Tech    | Version |
| ------- | ------- |
| Base UI | https://baseweb.design/components/datepicker/ |
| React   |         |
| browser |   Chrome Version 80.0.3987.87    |

- [ ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
This was fixed in a previous release
