### ISSUE TITLE
[Radio] Radio label not displaying.

### ISSUE THREAD

**Issue by LXSMNSYC** [uber/baseweb#3046]
Only the descriptions are showing. The value passed for the Radio children isn't empty nor null.

<img width="619" alt="Screen Shot 2020-03-16 at 12 42 50 AM" src="https://user-images.githubusercontent.com/4783372/76705981-1314d180-671f-11ea-85d0-79e86114eaa0.png">

The component is missing the third element which supposedly contains the title.

<img width="635" alt="Screen Shot 2020-03-16 at 12 43 29 AM" src="https://user-images.githubusercontent.com/4783372/76705991-29229200-671f-11ea-9ad3-5939b8ad1c4f.png">

as compared to the demo:
<img width="701" alt="Screen Shot 2020-03-16 at 12 44 19 AM" src="https://user-images.githubusercontent.com/4783372/76706010-47888d80-671f-11ea-96b4-5b1a9a493141.png">

I am currently using the latest React and Base UI packages.

**Comment by LXSMNSYC** [comment]
Here is the JSX code:
<img width="436" alt="Screen Shot 2020-03-16 at 12 45 55 AM" src="https://user-images.githubusercontent.com/4783372/76706031-80286700-671f-11ea-97d7-055f7291e6a3.png">


I even added the H1 component but it doesn't seem to display at all.

The Base Demo in React DevTools is expected to have a Label component before the description.
<img width="242" alt="Screen Shot 2020-03-16 at 12 47 35 AM" src="https://user-images.githubusercontent.com/4783372/76706060-be258b00-671f-11ea-8266-808122190dc3.png">

But it doesn't show to my component:
<img width="263" alt="Screen Shot 2020-03-16 at 12 48 36 AM" src="https://user-images.githubusercontent.com/4783372/76706074-e01f0d80-671f-11ea-829f-b4b72840a515.png">

**Comment by chasestarr** [comment]
Hi there, can you please edit this codesandbox to reproduce your issue? https://codesandbox.io/s/216pd?module=/example.js

**Comment by LXSMNSYC** [comment]
I am not sure if I can replicate the behavior, but I'll try the editing the code sandbox and see what happens.

**Comment by LXSMNSYC** [comment]
I have tried editing the code sandbox, and it seems that the problem stems to when I remove the <RadioGroup> component when using <Radio>

**Comment by chasestarr** [comment]
The `Radio` components will not work as expected without the `RadioGroup` component

**Comment by LXSMNSYC** [comment]
That's a shame, anyways, I am closing this issue for now.
