### ISSUE TITLE
[Timepicker] Can't clear date picker selection

### ISSUE THREAD

**Issue by matthewschwegler** [uber/baseweb#3047]
Sandbox - https://baseweb.design/components/datepicker/

## Current Behavior
1. Time picker loads with a time auto selected, this time field cannot be cleared with backspace. Pressing backspace gives user no feedback.
2. After typing a new time in and deleting that time dropdown selection defaults to 12:00AM but the input box has previously auto filled time in it
![image](https://user-images.githubusercontent.com/16162961/76706043-e1a9f080-66a1-11ea-8ce7-a69b16999ef5.png)

## Expected Behavior
1. I expect backspace to be a valid interaction to clear fields for a time for both the auto fill and manually typed data.
2. I expect the input selected time to correlate with the dropdown time.

## Your Environment

Testing in chrome on - https://baseweb.design/components/datepicker/

| Tech    | Version |
| ------- | ------- |
| Base UI | https://baseweb.design/components/datepicker/ |
| React   |         |
| browser |   Chrome Version 80.0.3987.87    |

- [ ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
I forget which PR fixed this bug, but can no longer reproduce the issue on the docs site
