### ISSUE TITLE
[ListItem, ListItemLabel] onClick not working

### ISSUE THREAD

**Issue by pixelgrid** [uber/baseweb#3058]
Attaching an onclick event handler on `<ListItem>` or `<ListItemLabel>` does not work.

Example codesandbox
https://codesandbox.io/s/sublist-hhoeu

## Current Behavior
Attaching an `onClick` handler on `<ListItem>` or `<ListItemLabel>` does not work.
To make it work the `onClick` has to be registered as a prop override for Root

```
<ListItem
    //this does not work
    onClick={() => console.log("not working")}
    overrides={{
      Root: {
        props: {
          onClick: () => { console.log("this works")}
        }
      }
    }}
>
content
</ListItem>
```

## Expected Behavior
Attaching an `onClick` handler on `<ListItem>` or `<ListItemLabel>` should properly be called once the list item is clicked

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.60.1 / v9.64.1  |
| React   |    16.8.6     |
| browser |    Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)     |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by YashGadle** [comment]
Probably because of this :
https://github.com/uber/baseweb/blob/cd4e0b2be33258f0aabb796790f58898a5d65971/src/list/list-item.js#L83
The `ListItem` takes out the `overrides -> Root -> props` and then spreads them on the `Root` component. It is not using the `onClick` passed via `props`.

**Comment by chasestarr** [comment]
We don't plan on adding `onClick` as a top level prop. Clickable elements add a significant amount of accessibility responsibility that is tough to get correct without a semantic `button` element. Please continue to override the component and manage the unique accessibility case for your application. If this element needs to be clickable, you may want to consider adding it to a `Menu` component
