### ISSUE TITLE
Select component's ClearIcon override doesn't work

### ISSUE THREAD

**Issue by candycanetrain** [uber/baseweb#3066]
Styling for ClearIcon from Select component cannot be overridden.

Repro: https://codesandbox.io/s/select-2igju

## Current Behavior

Following the docs: 
![image](https://user-images.githubusercontent.com/19182744/76933757-163cc880-68ab-11ea-8820-0f0135e2aced.png)

shows that styles cannot be overridden.

## Expected Behavior

Styles can be overridden.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.64.2  |
| React   |     16.8.6     |
| browser |    chrome     |

- [ yes ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
thank you @candycanetrain - any chance you can help us with the bug fix?
