### ISSUE TITLE
[datepicker] After setting date by clicking [Day], and then changing the value of the Calendar component, leaves the startDate selected by click highlighted. This feels like a glitch.

### ISSUE THREAD

**Issue by minseoksuh** [uber/baseweb#3067]
(Our team use version 9.0.0 datepicker from base ui, 
but I think the same issue is there in the most recent version)

As described in the title,
If you set Date range by clicking the days (Event), 
and then if you change the date range through "value" props of Calender component 
(without Event: like quickSelect)
then you see a highlight remaining in the calendar for the startDate of the "Clicked Range."

Users felt like that is a glitch and a bug. 
And it does seem weird.

However, as I looked into your code base, I just thought you guys are not resetting the highlight value when the "value" props update.

When, I just resetted the highlightedDate state in componendDidUpdate,
I felt everything work generally fine without the problem people found strange.
<img width="918" alt="스크린샷 2020-03-18 오후 6 53 03" src="https://user-images.githubusercontent.com/61446966/76947975-c2cd8780-6949-11ea-86e9-9048613ef63b.png">

## Feature description

Is it possible that you guys allow another option for the datepicker
like "resetHighLightOnChange" for the Calendar component
when "true"

that does something like this?
<img width="620" alt="스크린샷 2020-03-18 오후 6 56 59" src="https://user-images.githubusercontent.com/61446966/76948294-45eedd80-694a-11ea-94c0-9ba4ac8d07c2.png">

This is my first time writing anything on other repositories, so please excuse me if my format was not proper.

I will fix and reissue if you guys want me to.

Hope you guys look into the issue.

Thanks!!

**Comment by gergelyke** [comment]
@minseoksuh would you mind creating a code sandbox for this? you can fork this one https://codesandbox.io/s/7t0oh?module=/example.js

**Comment by minseoksuh** [comment]
https://codesandbox.io/s/datepicker-y7xvr

I forked it and set up the setting in which the issue occurs.

If you select a range by clicking, and then if you select option in quickSelect,
the highlight for the startDate of the "Clicked range" remains. (Although the actual range has changed to select option range i.e. last week).
(Note: when I quickSelect in codeSandbox the whole picker sometimes disappear. This is not the scenario I have in mind. In our project the the calendar always stays there when we select "last week" )

Is this what you wanted me to do?

I would like to apply the changes I made to the basueui dependency, 
but I do not know how to do that in code sandbox.

Let me know what

**Comment by chasestarr** [comment]
This issue is not something we plan to fix since it has minimal impact on the component's functionality. Let me know if you'd like to contribute a fix and I can re-open.

**Comment by minseoksuh** [comment]
> This issue is not something we plan to fix since it has minimal impact on the component's functionality. Let me know if you'd like to contribute a fix and I can re-open.

Yes, I would like to contribute a fix if I can.

**Comment by minseoksuh** [comment]
Just created a PR

I presume I did many things out of order.

Please let me know so I can edit it.

Thanks!
