### ISSUE TITLE
[Modal] Docs

### ISSUE THREAD

**Issue by kauly** [uber/baseweb#3068]
## Current Behavior
The Modal documentation don't have a component to overrides they style like the others components.

## Expected Behavior
A open modal at the top of the overrides menu, just like the others components.

- [X] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
hi @kauly - this is the expected behavior

you can click the `isOpen` know, so it will show the modal to you
