### ISSUE TITLE
Why was v9.64.3 released

### ISSUE THREAD

**Issue by conradreuter** [uber/baseweb#3076]
I am curious why version v9.64.3 was released. 

Looking at this diff: https://github.com/uber/baseweb/compare/v9.64.2...v9.64.3

`baseui` does not seem to ship any code changes with this new version.

**Comment by gergelyke** [comment]
hi @conradreuter - we version all baseui packages, like the eslint plugin or vscode extension. this version was shipping a fix for the vscode extension

I'll clarify this in our versioning policity
