### ISSUE TITLE
[DataTable] Application should know what rows are rendered

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#3099]
Suppose I need to export the table to csv after filter and sorting. This is not possible at the moment.

It can be achieved by adding a callback function (maybe named `onIncludedRowsChange` or similar) to the component called when `rows` [is recalculated](https://github.com/uber/baseweb/blob/master/src/data-table/data-table.js#L783).

**Comment by Deliaz** [comment]
Hi Chase, 
It sounds as a missing feature that we also need in our project. 
We plan to download the table data and to re-calculate some numbers based on what's left after filters have been applied. Just wondering, is there any ETA?
Thank you :)

**Comment by chasestarr** [comment]
I plan to start looking into it this week
