### ISSUE TITLE
[Select] Allow customizing Popover content in Select

### ISSUE THREAD

**Issue by dheeraj-jn** [uber/baseweb#3102]
## Feature description
I'm trying to override the `Popover` component and its `content` prop. So far the only thing preventing this overriding is that the Select component [expects a private instance variable `this.dropdown` to be set to the `ref` of the Popover content](https://github.com/uber/baseweb/blob/master/src/select/select-component.js#L1019). There is no way to assign`this.dropdown` from overrides. If `this.dropdown` is not set, then [`handleClickOutside`](https://github.com/uber/baseweb/blob/master/src/select/select-component.js#L317) throws an error as it tries to access `this.dropdown.current`.

**Comment by chasestarr** [comment]
Can you share a mockup design or diagram of the end goal you want to achieve?

**Comment by dheeraj-jn** [comment]
I'm building a custom datepicker. Using the `select` component seems the best match to my mockup, since I don't want the masked input of Base Web's own `Datepicker` and I need to be able to choose months and years separately.

So basically I'm pairing a simple `Select` with [`react-calendar`](https://github.com/wojtekmaj/react-calendar/).

**Comment by nadiia** [comment]
`DropdownContainer` gets that ref as a prop, so you could add an override for the `DropdownContainer` to get that ref and pass it onto a custom element.

**Comment by dheeraj-jn** [comment]
@nadiia Thanks for the tip, it works.
