### ISSUE TITLE
Can't override the expand state of Panel in Accordion from props

### ISSUE THREAD

**Issue by javidhsueh** [uber/baseweb#3104]
Please see the [demo](https://codesandbox.io/s/accordion-basic-usage-zlo6z)

## Current Behavior
Current the expand status is determine from state of props:
```
expanded: isExpanded || child.props.expanded,
```
See the source:
https://github.com/uber/baseweb/blob/master/src/accordion/accordion.js#L93

This will prevent passing the expand status from props if the `isExpanded` from the state is `true`.

## Expected Behavior
The expand status should be determined by props if expanded exists.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.25.0  |
| React   |   v16.12.0 |
| browser |  Chrome@v80.0.3987.132        |

- [ v ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
We have a task in our backlog to handle this case with a 'stateless' accordion component. If you are stuck in the mean-time this will be useful https://codesandbox.io/s/accordion-basic-usage-l6q5o

**Comment by javidhsueh** [comment]
> We have a task in our backlog to handle this case with a 'stateless' accordion component. If you are stuck in the mean-time this will be useful https://codesandbox.io/s/accordion-basic-usage-l6q5o

Thanks so much! this is very helpful!

**Comment by sandgraham** [comment]
Resoled in #3180. Available as of v9.69.0. See the [example](https://baseweb.design/components/accordion/#stateless-accordion) on doc site.
