### ISSUE TITLE
[Select] mimic native select text search option behaviour

### ISSUE THREAD

**Issue by AndrewUldin** [uber/baseweb#3108]
Select supports search option but very often list of options consist only of 2 or 3 options. Using search in that case doesn't make much sense but it would be handy to be able to navigate through the options by just typing on focused select as it is implemented for native select control.

It is also just a good practise to support native navigation patterns.

![screencast 2020-03-24 16-17-35](https://user-images.githubusercontent.com/13057193/77443309-46282680-6deb-11ea-82eb-c5c7fa68c92a.gif)

**Comment by chasestarr** [comment]
We do not plan to support this feature. If the options need need to be searchable please use the built-in functionality to do so.
