### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by eminmuhammadi** [uber/baseweb#3115]
## Current Behavior
XSS vulnerability on [https://baseweb.design/components/slider/?code=alert(document.cookie);](https://baseweb.design/components/slider/?code=alert(document.cookie);)

## Expected Behavior
It should block the execution of **xss** based components

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
We'll get back to you on this in private.
