### ISSUE TITLE
Cannot override Popover styles in Menu component

### ISSUE THREAD

**Issue by hhvys** [uber/baseweb#3155]
We cannot override Popover styles for Menu component. The same utility is present for Select component.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.65.1  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by sandgraham** [comment]
Hi @hhvys could you add a bit of detail to this issue? Perhaps a code example of what you want to accomplish? The `Menu` doesn't use a `Popover` so I'm not sure what you would like to override.

**Comment by hhvys** [comment]
@sandgraham Popover is used in displaying `ChildMenu`. I wanted to show an arrow on the child menu. https://codesandbox.io/s/kfisv?module=/example.tsx Can you please provide me a way to show an arrow on the child menu.

**Comment by sandgraham** [comment]
Ohhh, you want to enable `showArrow` on the Popover used for child menus. Yeah we would need to add an override for nested menu popovers. Not much we can do about the arrow currently.

**Comment by hhvys** [comment]
Same problem with Tooltip, too. Although tooltip provides `showArrow` functionality. I think `baseweb` should not use any internal component directly without input from overrides.

**Comment by sandgraham** [comment]
@hhvys would be down to open a PR adding the override?

**Comment by hhvys** [comment]
Sure, will raise the PR
