### ISSUE TITLE
[Styling] Longhand CSS attributes not used consistently for borders

### ISSUE THREAD

**Issue by jasongi-actu** [uber/baseweb#3159]
## Current Behavior

Non-longhand border styles are used in many components, instead of border[Left/Right/Top/Bottom][Style/Width/Color] border[Left/Right/Top/Bottom] or border[Style/Width/Color] is used instead. This can cause styling errors when overriding.

## Expected Behavior

Longhand styles should be used at all times. 

- [ x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

Here is a list of all the border[Top/Left/Right/Bottom] by searching the repo. There are also many cases of border[Style/Width/Color] that I haven't listed but also should probably be fixed.

Components:
- [Accordion 1](https://github.com/uber/baseweb/blob/1aab1e6372be78f0a5c4b733ba9bde277ba87dfa/src/accordion/styled-components.js#L49) [2
](https://github.com/uber/baseweb/blob/1aab1e6372be78f0a5c4b733ba9bde277ba87dfa/src/accordion/styled-components.js#L87)
- [Header Navigation](https://github.com/uber/baseweb/blob/3d6e3c4a40d4787aa080dc48bd8b7ffe121d61e9/src/header-navigation/styled-components.js#L23)
- [Tabs 1](https://github.com/uber/baseweb/blob/1aab1e6372be78f0a5c4b733ba9bde277ba87dfa/src/tabs/styled-components.js#L43)
- [Table 1](https://github.com/uber/baseweb/blob/f14c8c1a11345f456007bd08cda83e05ca3f749d/src/table/styled-components.js#L72) [2](https://github.com/uber/baseweb/blob/f14c8c1a11345f456007bd08cda83e05ca3f749d/src/table/styled-components.js#L71) [3](https://github.com/uber/baseweb/blob/f14c8c1a11345f456007bd08cda83e05ca3f749d/src/table/styled-components.js#L73) [4](https://github.com/uber/baseweb/blob/f14c8c1a11345f456007bd08cda83e05ca3f749d/src/table/styled-components.js#L215) [5](https://github.com/uber/baseweb/blob/f14c8c1a11345f456007bd08cda83e05ca3f749d/src/table/styled-components.js#L67)
- [Input 1](https://github.com/uber/baseweb/blob/744a63342141572b37e2cd30c2131517f89bff89/src/input/styled-components.js#L29) [2](https://github.com/uber/baseweb/blob/744a63342141572b37e2cd30c2131517f89bff89/src/input/styled-components.js#L28) [3](https://github.com/uber/baseweb/blob/744a63342141572b37e2cd30c2131517f89bff89/src/input/styled-components.js#L30) [4](https://github.com/uber/baseweb/blob/744a63342141572b37e2cd30c2131517f89bff89/src/input/styled-components.js#L31)
- [DataTable 1](https://github.com/uber/baseweb/blob/761a0e688f788ecde164a2297c5110d961079b04/src/data-table/data-table.js#L119) [2](https://github.com/uber/baseweb/blob/761a0e688f788ecde164a2297c5110d961079b04/src/data-table/data-table.js#L118) [3](https://github.com/uber/baseweb/blob/761a0e688f788ecde164a2297c5110d961079b04/src/data-table/data-table.js#L471) [4](https://github.com/uber/baseweb/blob/761a0e688f788ecde164a2297c5110d961079b04/src/data-table/data-table.js#L120) [5](https://github.com/uber/baseweb/blob/761a0e688f788ecde164a2297c5110d961079b04/src/data-table/data-table.js#L122) [6](https://github.com/uber/baseweb/blob/761a0e688f788ecde164a2297c5110d961079b04/src/data-table/data-table.js#L473)
- [List 1](https://github.com/uber/baseweb/blob/3d6e3c4a40d4787aa080dc48bd8b7ffe121d61e9/src/list/styled-components.js#L33) [2](https://github.com/uber/baseweb/blob/3d6e3c4a40d4787aa080dc48bd8b7ffe121d61e9/src/list/styled-components.js#L35) [3](https://github.com/uber/baseweb/blob/3d6e3c4a40d4787aa080dc48bd8b7ffe121d61e9/src/list/styled-components.js#L34)

Tests:
- [table-cell](https://github.com/uber/baseweb/blob/85d126dcc9469cad628b2488575979129e9b9fe6/src/table/__tests__/table-cells.scenario.js#L78)
- [tree-view](https://github.com/uber/baseweb/blob/9777544299ff8190fd8f54e21772df88c3106bf6/src/tree-view/styled-components.js#L30)

Docs:
- [table-of-contents](https://github.com/uber/baseweb/blob/3ff3b2df141ac06ff933c1de2a4b9eb2c3d22377/documentation-site/components/table-of-contents.js#L67)
- [code-box](https://github.com/uber/baseweb/blob/c2f54c1a0f2f636067b4c11658e0d2f949201c1e/documentation-site/components/code-box.tsx#L11)
- [Gallery 1](https://github.com/uber/baseweb/blob/51bca7ff69ecba2b2722773c75592f2019d1a78d/documentation-site/components/gallery.js#L297) [2](https://github.com/uber/baseweb/blob/51bca7ff69ecba2b2722773c75592f2019d1a78d/documentation-site/components/gallery.js#L298) [3](https://github.com/uber/baseweb/blob/51bca7ff69ecba2b2722773c75592f2019d1a78d/documentation-site/components/gallery.js#L299)
- [Tooltip 1](https://github.com/uber/baseweb/blob/c2f54c1a0f2f636067b4c11658e0d2f949201c1e/documentation-site/examples/tooltip/stateful-complex-content.js#L27) [2](https://github.com/uber/baseweb/blob/c2f54c1a0f2f636067b4c11658e0d2f949201c1e/documentation-site/examples/tooltip/stateful-complex-content.tsx#L26) [3](https://github.com/uber/baseweb/blob/c2f54c1a0f2f636067b4c11658e0d2f949201c1e/documentation-site/examples/tooltip/stateful.js#L17) [4](https://github.com/uber/baseweb/blob/c2f54c1a0f2f636067b4c11658e0d2f949201c1e/documentation-site/examples/tooltip/stateful.tsx#L16)
- [Tokens](https://github.com/uber/baseweb/blob/3d6e3c4a40d4787aa080dc48bd8b7ffe121d61e9/documentation-site/pages/components/tokens.mdx#L35)

**Comment by gergelyke** [comment]
@jasongi-actu thank you for the thorough list! any chance you could help us send PRs fixing these?

**Comment by jasongi-actu** [comment]
I can if I can find time, however wondering what the best way to do this would be since technically it could be a (minor?) breaking change - as people who have encountered the warnings would probably have used the shorthand styles, so when they upgrade baseweb they may get warning for the shorthand styles and it will mess up their styling.

**Comment by gergelyke** [comment]
historically, we just went ahead and fixed these issues - what's your take on this @chasestarr @sandgraham @tajo @nadiia ?

**Comment by tajo** [comment]
We ask people to always use longhand properties so fixing this should not be considered as a breaking change.

Also for the tests and docs, it's ok to use shorthands. Those are our internal components, not a part of `baseui`.

**Comment by gergelyke** [comment]
@jasongi-actu in lights of Vojtech's comment, can you help us open a PR for this?

**Comment by hemildesai** [comment]
There's one example here as well - https://github.com/uber/baseweb/blob/master/src/card/styled-components.js#L47

**Comment by jasongi-actu** [comment]
> @jasongi-actu in lights of Vojtech's comment, can you help us open a PR for this?

Have had a crack at this today
https://github.com/uber/baseweb/pull/3172
