### ISSUE TITLE
Naming inconsistency with Datepicker vs TimePicker.

### ISSUE THREAD

**Issue by illogikal** [uber/baseweb#3173]
import { Datepicker } from "baseui/datepicker";
import { TimePicker } from "baseui/timepicker";
import { TimezonePicker } from "baseui/timezonepicker";

## Current Behavior

Datepicker the p is lower case.

## Expected Behavior

DatePicker with upper case P.

Maybe alias the name? Or perhaps this is just splitting hairs.

- [x ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
hi @illogikal - thank you for opening this issue. While I agree, that they should be consistent, I wouldn't change it, as it would incur a migration cost for all users, without real benefits

I'll close this, for now, please re-open if you feel strongly about it.
