### ISSUE TITLE
[Toast] Add docs site example to close from outside of toast

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#3188]
This sandbox should be added to the docs site: https://codesandbox.io/s/toastercontainer-7yqdf?file=/example.js

**Comment by alan-oliv** [comment]
Hi @chasestarr and @sandgraham, I'm interested in working on this.

**Comment by alan-oliv** [comment]
> This sandbox should be added to the docs site: https://codesandbox.io/s/toastercontainer-7yqdf?file=/example.js

@chasestarr this [PR](https://github.com/uber/baseweb/pull/3306) closes this issue, thanks for allowing my contribution on this
