### ISSUE TITLE
StyledTable not responsive

### ISSUE THREAD

**Issue by png-prakash** [uber/baseweb#3199]
See [this codesandbox](https://codesandbox.io/s/baseui-lack-of-responsive-styling-on-table-mohsr) reproducing the issue.

![page](https://user-images.githubusercontent.com/61315943/79071902-beec1580-7cfb-11ea-9406-8c41c157902f.png)

This is working fine. But in responsive screen not working. 
Is it possible to make responsive table? 
I checked with basic table (https://baseweb.design/components/table/), its working fine. But I don't know how to make dynamic data, like using map method.
How to solve this?
Thanks

**Comment by sandgraham** [comment]
See [this codesandbox](https://codesandbox.io/s/baseui-lack-of-responsive-styling-on-table-mohsr) for example of responsive styling issue.

**Comment by sandgraham** [comment]
Note, the basic table does not seem to handle narrow widths very well either: [codesandbox](https://codesandbox.io/s/baseui-table-default-responsive-styling-l8gw2?file=/example.js)

**Comment by chasestarr** [comment]
See [this example](https://baseweb.design/components/table#table-cell-examples) for how to handle horizontal scrolling
