### ISSUE TITLE
[Datepicker] Inputting a date into input field results in wrong date

### ISSUE THREAD

**Issue by jasongi-actu** [uber/baseweb#3230]
## Current Behavior
If you go [here](https://baseweb.design/components/datepicker/), clear the field and start typing "1993/01/01" you end up with "2993/01/01"
I haven't really explored why this is happening, but it makes inputting the field in the textfield fairly useless. You can paste 1993/01/01 and it works fine, which makes me think it's somehow turning the incomplete year into a completely different one.

## Expected Behavior
It should only display what you are typing. Perhaps one way to do this is to ignore onChange events until the requisite number of digits are in the field.

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

![6d8eb892-1b32-4792-88ec-9ad238ad688d](https://user-images.githubusercontent.com/40749062/79525211-adad5b00-80a5-11ea-86b5-f4485cb8a069.gif)

**Comment by jayanthchandra** [comment]
I looked it up and found that when the first character is typed in , the value returned here is "1 / / " and when passed to JS Date constructor with that field it returns Jan 2001.  Date object uses the first character in the string as month for the year 2001 so if you type the first character as 5 then the result would be 2001/05/01.
https://github.com/uber/baseweb/blob/a4de154ced26570b320f9e90b7136db5e49c9d9f/src/datepicker/datepicker.js#L223
