### ISSUE TITLE
Child components of NumberedStep not rendered

### ISSUE THREAD

**Issue by wnyao** [uber/baseweb#3235]
Children components under NumberedStep component are not rendered when working with ProgressSteps. This issue also happened at the given [example](https://baseweb.design/components/progress-steps#numbered-progress-steps) provided on docs, as it specified child elements but are not rendered as the display shown.

```
<NumberedStep title="Verify Address">
        <p>Address on file: 1455 Market Street</p>
        <Button
          size="compact"
          onClick={() => setCurrent(1)}
        >
          Next
        </Button>
</NumberedStep>
```

**Sandbox:** 
[https://github.com/wnyao/baseui-sandbox](https://github.com/wnyao/baseui-sandbox)

## Current Behavior
Children under NumberedStep component are not rendered when working with ProgressSteps

## Expected Behavior
Children under NumberedStep component are rendered as specified

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.71.0  |
| React   |  v16.3.1   |
| browser | Chrome v80.0.3987.163 |

**Comment by wnyao** [comment]
After digging the source code. I found that it is required to set `isActive` prop to true in order to have children rendered on numbered-step component [as it defaulted to false](https://github.com/uber/baseweb/blob/a4de154ced26570b320f9e90b7136db5e49c9d9f/src/progress-steps/numbered-step.js#L77). 

Strangely compared to code in [progress-steps/step.js](https://github.com/uber/baseweb/blob/a4de154ced26570b320f9e90b7136db5e49c9d9f/src/progress-steps/step.js#L70) component, it has missing isActive defaultProp but even value of isActive prop not passed by user (which i assumed isActive prop will result to undefined) the render are not affected and still will be rendered.

Source code from progress-steps/numbered-step:
```
...
  return (
    <Root {...sharedProps} {...rootProps}>
      <Icon {...sharedProps} {...iconProps}>
        {!isCompleted && <span>{step}</span>}
        {isCompleted && <CheckIcon size={12} {...checkIconProps} />}
      </Icon>
      {!isLast && <Tail {...sharedProps} {...tailProps} />}
      <Content {...sharedProps} {...contentProps}>
        <Title {...sharedProps} {...titleProps}>
          {title}
        </Title>
        <Description {...descriptionProps}>{isActive && children}</Description>
      </Content>
    </Root>
  );
}

NumberedStep.defaultProps = {
  isCompleted: false,
  isActive: false,
  isLast: false,
};

```

Source code from progress-steps/step.js:

```
...
   return (
    <Root {...sharedProps} {...rootProps}>
      <Icon {...sharedProps} {...iconProps}>
        {isActive && <InnerIcon {...innerIconProps} />}
      </Icon>
      {!isLast && <Tail {...sharedProps} {...tailProps} />}
      <Content {...sharedProps} {...contentProps}>
        <Title {...sharedProps} {...titleProps}>
          {title}
        </Title>
        <Description {...descriptionProps}>{isActive && children}</Description>
      </Content>
    </Root>
  );
}

Step.defaultProps = {
  isCompleted: false,
  isLast: false,
};

```

**Comment by sandgraham** [comment]
Hi @wnyao, thanks for looking into this. This seems like a regression caused by #3140. We probably need to update numbered step to match step's api again.
