### ISSUE TITLE
[Skeleton] What's the status?

### ISSUE THREAD

**Issue by conradreuter** [uber/baseweb#3259]
A while ago I wrote up a [proposal for a Skeleton component](../blob/f318b2f28e0d7ca6e427bea8f7157fab22f53d63/proposals/skeleton.md).

@chasestarr 
What is the status on this?
Is the design team working on it? ([referring to the comment on my PR](../pull/2399#issuecomment-561396685))

**Comment by chasestarr** [comment]
Added it to our next meeting notes

**Comment by chasestarr** [comment]
There has not been much design capacity to spec this out, so they are leaving it up to the implementor to make some sensible decisions. Something close to material ui is preferable. We've pushed this effort higher in our own priority and I expect it to be taken on within the next month or so

**Comment by chasestarr** [comment]
Here's the first version of the skeleton completed by @jiaoy14 https://github.com/uber/baseweb/pull/3472
