### ISSUE TITLE
[AppNavBar] MainNav Items on full screen should have a pointer cursor

### ISSUE THREAD

**Issue by wseagar** [uber/baseweb#3262]
Reproduction can be seen in https://baseweb.design/components/app-nav-bar/

## Current Behavior

On full screen the nav items show a text cursor on hover.

## Expected Behavior

On full screen the nav items show a pointer cursor on hover.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | 9.72.0  |
| React   |   16.13.1 |
| browser |   chrome   |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by Barathwaja** [comment]
For getting pointer cursor, below snippet should be added.

`const appDisplayName = (
    <StyledLink
      $style={{
        textDecoration: 'none',
        color: 'inherit',
        ':hover': {color: 'inherit'},
        ':visited': {color: 'inherit'}
      }}
      href={'#'}
    >
      Navigation Bar
    </StyledLink>
  );

<AppNavBar
         appDisplayName={appDisplayName}
          mainNav={[]}
/>`

**Comment by sandgraham** [comment]
I don't see this when I hover over main nav items. Any other steps to reproduce? Browser? Custom code?

**Comment by wseagar** [comment]
I just checked and it appears to have been fixed. I did have a work around but I assumed it should be a pointer cursor by default.

We can close this. Thanks!
