### ISSUE TITLE
[Form Control] logs out error for some child components

### ISSUE THREAD

**Issue by andriuss** [uber/baseweb#3301]
https://codesandbox.io/s/formcontrol-86gye?file=/example.js

## Current Behavior

Form Control outputs error for some child components. Example in codesandbox (look at the console tab).

Console error output:
Warning: Received `false` for a non-boolean attribute `error`.
```
If you want to write it to the DOM, pass a string instead: error="false" or error={value.toString()}.

If you used to conditionally omit it with error={condition && value}, pass error={condition ? value : undefined} instead.
    in div (created by Context.Consumer)
    in DevConsumer (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in StyledBlock (created by Block)
    in Block (created by Block)
    in Block (at example.js:9)
    in div (created by Context.Consumer)
    in DevConsumer (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in ControlContainer (created by FormControl)
    in FormControl (at example.js:8)
    in _default (at index.js:14)
    in App (at index.js:21)
    in ThemeProvider (created by BaseProvider)
    in div (created by Context.Consumer)
    in DevConsumer (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in StyledAppContainer (created by Context.Consumer)
    in LayersManager (created by BaseProvider)
    in BaseProvider (at index.js:20)
    in DevProvider (at index.js:19)
```

## Expected Behavior

No error should not be in the output.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.73.2  |

**Comment by chasestarr** [comment]
Sorry for overlooking this. `FormControl` components should only wrap `Input` components (or similar like `Datepicker`). It forwards some accessibility props through to the input element. We don't plan on changing the current functionality, but feel free to share more about your situation

**Comment by chasestarr** [comment]
Closing, but feel free to continue if you have more information
