### ISSUE TITLE
OnClick property on Icon gives typescript error. 

### ISSUE THREAD

**Issue by shubh28** [uber/baseweb#3302]
## Current Behavior

I am working with baseui, reactjs and typescript.  When I try and attach an onClick event to icon I get typescript error `_Property 'onClick' does not exist on type 'IntrinsicAttributes & IconProps_`.
 Code to replicate it: 

    import { Delete } from "baseui/icon";
    function DeleteIcon() {
        render(){
            return <Delete size={32} onClick={() => console.log("hey")} />;
        }
    }

## Expected Behavior

There should be onClick available on the default proptypes for the same.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.73.2  |
| React   |  16.13.1       |
| browser |  Chrome       |

**Comment by chasestarr** [comment]
Click handlers should not be added to `Icon` components for accessibility purposes. Try wrapping it in a `Button` https://baseweb.design/components/button#shapes
