### ISSUE TITLE
How to show ToasterContainer when get response from server instead of button click?

### ISSUE THREAD

**Issue by png-prakash** [uber/baseweb#3332]
https://codesandbox.io/s/mihqy?module=/example.js&file=/example.js:231-247
Example in baseweb

const userData = {
      username: 'test'
    };
axios.post(Constants.APIURL + 'user/add', userData, {
      headers: {
        'Authorization' : `Bearer ${token}`
      }
    })
    .then(response => {
      if (response.data.status === 'success') {
        alert('User added successfully');  //Show toast container
      }
    })
    .catch(error => {
    });

**Comment by houmark** [comment]
Toast is very well documented and you can open a toast simply by using `toaster.info(<>message</a>)` as long as you make sure that your component has `ToasterContainer` in one way or the other.

Much more here: https://baseweb.design/components/toast/

**Comment by gergelyke** [comment]
thanks @houmark
