### ISSUE TITLE
[Slider] Handle 'jumps' when min value is negative

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#3334]
reproducing sandbox: https://codesandbox.io/s/slider-yzqrx

![slider-jump](https://user-images.githubusercontent.com/5317799/81959545-7a86ba80-95c4-11ea-84c1-ad6f0d13d00f.gif)

## Current Behavior

If `min` value is negative, slow handle drags cause 'jumping' when handle value is positive.

## Expected Behavior

Handle should not jump

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.76.0  |

**Comment by 94151** [comment]
@chasestarr  Can i look into this bug.

**Comment by sandgraham** [comment]
Hi @94151 - are you still planning to work on this bug?

**Comment by nadiia** [comment]
`react-range@1.6.7` with a fix is published
