### ISSUE TITLE
App Nav Bar - mainNav should hide if false or null array

### ISSUE THREAD

**Issue by Barathwaja** [uber/baseweb#3348]
## Current Behavior
In the AppNavBar Component, the mainNav if the value is not give or empty array, the list icon appears and on performing click event on icon it fails and asks for avatar and other components.

**Icon Screenshot** - list icon
![image](https://user-images.githubusercontent.com/5066436/82302632-7d741780-99d7-11ea-8b05-5cfa9b6cd7bc.png)

**OnClick Event Screenshot**
![image](https://user-images.githubusercontent.com/5066436/82302521-54ec1d80-99d7-11ea-8694-1ca1dc9cc2be.png)

## Expected Behavior
In the AppNavBar Component, the mainNav if the value is empty array, the list icon should appear but event should not happen.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.72.0 |
| React   |  16.13.1   |
| Browser |  Chrome/ Firefox/ Safari |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by sandgraham** [comment]
@Barathwaja could you include a reproducing stackblitz please? You can fork [this one](https://stackblitz.com/edit/react-uyhcq7?file=src/example.js).

**Comment by Barathwaja** [comment]
@sandgraham - Yes please check this [stackblitz](https://stackblitz.com/edit/react-uyhcq7-akq6hk?file=src/example.js) for this issue.

**Comment by sandgraham** [comment]
Thanks @Barathwaja.

**Comment by Barathwaja** [comment]
Thanks @nadiia , Can i do npm install to get this latest change?

**Comment by nadiia** [comment]
@Barathwaja Created a release here #3375, will be published once merged.
