### ISSUE TITLE
[Menu] Child menu does not have a method to indicate which of its provided items was selected

### ISSUE THREAD

**Issue by michaelaflores** [uber/baseweb#3353]
## Current Behavior

To create a child menu, the documentation shows how to use `getChildMenu` and provide a function which will create a child menu. However, there doesn't seem to be a built-in method of indicating which of the provided items was clicked.

## Expected Behavior

Should be some built-in way of indicating which item was clicked on click, rather than doing some reading of the DOM on click and matching against the list.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v?.?.?  |
| React   |         |
| browser |         |

- [ ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Hi @michaelaflores here is an example of how to do this https://jd59yh.run.stackblitz.io

**Comment by michaelaflores** [comment]
@chasestarr just a heads up, that example doesn't load for me (stuck on "Starting dev server").

**Comment by sandgraham** [comment]
@michaelaflores - what browser do you use? It is working for me on latest Chrome.
