### ISSUE TITLE
Popover broken in IE11

### ISSUE THREAD

**Issue by leyanlo** [uber/baseweb#3354]
![ie11-base-web-popover 2020-05-20 02_02_18](https://user-images.githubusercontent.com/1285326/82427858-81875000-9a3e-11ea-9152-776bff05270d.gif)

It looks like the Popover component does not work on IE11. I looked at older versions on the documentation site, and the last working version was in Base Web v7.8.0.

![ie11-base-web-popover-v7 2020-05-20 02_09_22](https://user-images.githubusercontent.com/1285326/82428155-ef337c00-9a3e-11ea-8469-016d0f5b8385.gif)

**Comment by sandgraham** [comment]
Hi @leyanlo - I've tested the popover in isolation on IE11 and things seemed to work. I think this might be an issue with the documentation site itself. Are you able to reproduce this issue in your application?

**Comment by leyanlo** [comment]
Ah sorry yes this only concerning the documentation site. Application works fine :-)

**Comment by leyanlo** [comment]
Yay thanks!
