### ISSUE TITLE
FlexGridItem throws error for borderRadius

### ISSUE THREAD

**Issue by Barathwaja** [uber/baseweb#3357]
## Current Behavior

When I add borderRadius to prop, the FlexGridItem errors.
![image](https://user-images.githubusercontent.com/5066436/82661950-a5b77c80-9c4a-11ea-8018-868945f3e3c7.png)

Even though in this document [Flex Grid Document](https://baseweb.design/components/flex-grid/) there no API for that, is there an alternative approach for this to add borderRadius??

## Your Environment
Please find the below link.
https://stackblitz.com/edit/react-uyhcq7-jvpfmm

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.72.0|
| React   |   16.13.1  |
| browser |     Chrome/Firefox/Safari    |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
👋 

the flexgrid component does not support the borderRadius prop

you can do something like this instead:

```js
const gridProps = {
        backgroundColor: '#000000',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: 'scale1000',
        marginTop: '50px',
        marginRight: '20px',
        overrides: {
          Block: {
            style: {
              borderRadius: '6px'
            }
          }
        }
    };

```

this works, because under the hood, flexgrid uses the Block component
