### ISSUE TITLE
[ListItem] Enable overrides at the ListItemLabel level

### ISSUE THREAD

**Issue by angus-c** [uber/baseweb#3361]
**What I want to do**

example: render a list where each item has two parts, letters in black and numbers in grey
```
ABC 123
DEF 456
GHI 789
```

**How I want to do it**
Use an override at the `ListItemLabel` level
```js
<ListItem 
  overrides={
    ListItemLabel: {
      style: $index => ({  
        color: $index === 0 ? '#000' : '#888',
      })  
    }  
  }
>
  <ListItemLabel>{letters}</ListItemLabel>
  <ListItemLabel>{numbers}</ListItemLabel>
</ListItem>
```

**Other things I tried**
1.
```js
<ListItemLabel style={{color: '#888'}}>123</ListItemLabel>
```
2.
```js
<ListItemLabel className={css({color: '#888'})}>123</ListItemLabel>
```
3. Using an `endEnhancer` for the second label. However the `EndEnhancerContainer` override seems to only apply to the container, so I can't override the color.

**The only way that worked**
Use spans :(

```js
<ListItem>
  <span>ABC</span>
  <span className={css({color: '#888' })}>123</span>
</ListItem>       
```

**Comment by angus-c** [comment]
If we decide to do this, I'm happy to take a stab at the PR

**Comment by gergelyke** [comment]
this makes sense to me - @angus-c just assigned the issue to you, thanks!
