### ISSUE TITLE
Feature: StyledLink Prop Types

### ISSUE THREAD

**Issue by git-ced** [uber/baseweb#3362]
## Feature description

`StyledLink` doesn't have proper prop types. I can put any props that i want. Would be better if it has a prop type instead of `<any>`. 

For example, If i use `target` i can put anything that i want (string, bool, etc). I expect that i can only put a string there or even more specific `'_blank' | '_self' | '_parent' | '_top' `.  Even `href` itself, in the documentation the href prop type said that its a string, but i can also put anything that i want and it wont complain.

Having proper types would give a better developer experience.

**Comment by gergelyke** [comment]
@git-ced  are you using flow or typescript?

**Comment by git-ced** [comment]
I'm using typescript.
