### ISSUE TITLE
Tab component is not responsive

### ISSUE THREAD

**Issue by mramosvi** [uber/baseweb#3366]
https://stackblitz.com/edit/react-pibsdy-6tyfl3

## Current Behavior

Tab component is not looking properly on iPad and mobile devices, it seems is not responsive at all and when there are 4 or more tabs don't looks properly. Also when having many tabs a scroll appears below of the page.

## Expected Behavior

Tab component should be adaptative, so must have an option to allow horizontally scroll on TabBar, and not to entire page, when have many tab items, also, in touch screens, the scroll action should be swappable. Also have an option to show arrows to make the same behavior for desktop or big devices.

## Your Environment

You can test it directly in Stackblitz because it is an issue that could be found and test it in base web documentation:

https://stackblitz.com/edit/react-pibsdy-6tyfl3

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.79.0  |
| React   |         |
| browser |   issue could be found in all browsers      |

- [ x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
@mraam for this specific component, mobile was not a primary consideration - with that being said, we'd be happy to accept contributions that improve it. Would you be up for sending a PR fixing it?

**Comment by sandgraham** [comment]
@mramosvi In the mean time, you can [add an `overflowX: scroll` to the `TabBar`](https://stackblitz.com/edit/react-pibsdy-xz3faw?file=src/example.js).

**Comment by mramosvi** [comment]
> @mramosvi for this specific component, mobile was not a primary consideration - with that being said, we'd be happy to accept contributions that improve it. Would you be up for sending a PR fixing it?

ok well is not a mobile issue really, if you use tab in a small layout or if you use many tab items, tabs component will not show properly because is not responsive.

**Comment by mramosvi** [comment]
> @mramosvi In the mean time, you can [add an `overflowX: scroll` to the `TabBar`](https://stackblitz.com/edit/react-pibsdy-xz3faw?file=src/example.js).

Yes but is not a properly solution for desktop because is not swappable so is not a usable solution for user

**Comment by gergelyke** [comment]
@mraam would you be up to send a PR fixing it?

**Comment by sandgraham** [comment]
@mramosvi - What do you mean by swappable? I think scrolling horizontally through tabs is a fine experience if the area is very narrow.

**Comment by mramosvi** [comment]
> @mramosvi - What do you mean by swappable? I think scrolling horizontally through tabs is a fine experience if the area is very narrow.

In desktop there are no natural mouse horizontally scroll, only if user put mouse inside tabs zone, so you need to offer an usable solution that works on mobile and desktop as well. Usually, horizontal scroll is solved with arrows or swippable option in desktop.

**Comment by mramosvi** [comment]
> @mramosvi would you be up to send a PR fixing it?

Sorry but I'm not going to fix this, have no time at the moment, I would like to know if you are planning to solve that because i think it is a library important gap.

Thank you.

**Comment by sandgraham** [comment]
@mramosvi There are no plans to update the Tab component for enhanced mobile interactivity. We don't have any internal requirements for such an enhancement. There are also a few low-effort solutions available right now, such as applying some overflow scrolling via [overrides](https://stackblitz.com/edit/react-pibsdy-xz3faw?file=src/example.js) or using a [vertical tab list](https://baseweb.design/components/tabs/#tabs-vertical-usage).

If an internal requirement for this enhancement arises we will update the issue accordingly. In the meantime, if someone in the community wants this feature and has the time to take it on we would be happy to review a PR.

**Comment by mramosvi** [comment]
> @mramosvi There are no plans to update the Tab component for enhanced mobile interactivity. We don't have any internal requirements for such an enhancement. There are also a few low-effort solutions available right now, such as applying some overflow scrolling via [overrides](https://stackblitz.com/edit/react-pibsdy-xz3faw?file=src/example.js) or using a [vertical tab list](https://baseweb.design/components/tabs/#tabs-vertical-usage).
> 
> If an internal requirement for this enhancement arises we will update the issue accordingly. In the meantime, if someone in the community wants this feature and has the time to take it on we would be happy to review a PR.

Hello, ok thank you. However is not only a mobile issue, tab component is not responsive at all, so in my opinion it is a seriously gap that need to be fixed if you say that BaseWeb library is a responsive library, because now it is not.

**Comment by gergelyke** [comment]
@mramosvi that's how free open-source software is - if you need a feature/fix, and there is no one else to work on it, it's your job to fix it

as Graham said, we welcome any PRs, and are happy to provide guidance, but we won't be able to work on this in the near future

**Comment by sandgraham** [comment]
The new [tabs-motion](https://baseweb.design/components/tabs-motion/) component solves some of the responsive issues that the initial Tab component had. Please give that a try if you need something more flexible.

**Comment by mramosvi** [comment]
> @mramosvi that's how free open-source software is - if you need a feature/fix, and there is no one else to work on it, it's your job to fix it
> 
> as Graham said, we welcome any PRs, and are happy to provide guidance, but we won't be able to work on this in the near future

Hello, yes I understand how open-source software works but as I said, you cannot say your open-source library is totally responsive when is not the case. Also, I don't think that is my job to fix anything, I'm using the library but have no time to contribute it as I'm contributing to other libraries as well, so I think that I did my job to open an issue when anyone else sees it.

**Comment by mramosvi** [comment]
> The new [tabs-motion](https://baseweb.design/components/tabs-motion/) component solves some of the responsive issues that the initial Tab component had. Please give that a try if you need something more flexible.

Hello, ok thank you so much. I will try this new component and see if it works well. 👍
