### ISSUE TITLE
Inconsistent capitalization for exports - Datepicker, TimePicker

### ISSUE THREAD

**Issue by ajbogh** [uber/baseweb#3368]
The Datepicker component is exported as "Datepicker" with a lowercase "p" while "TimePicker" is exported as with an uppercase "P". These "Picker" components should have consistent casing. 

## Current Behavior

```
import { Datepicker } from 'baseui/datepicker';
import { TimePicker } from 'baseui/timepicker';
```

## Expected Behavior

Since "Picker" is a separate word, it should be capitalized in both instances.

```
import { DatePicker } from 'baseui/datepicker';
import { TimePicker } from 'baseui/timepicker';
```
It's possible to export `Datepicker` for backwards compatibility, as well as `DatePicker` for consistency from the index.js file. 

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.73.2  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
@ajbogh that's a good point - would you mind sending a PR?
