### ISSUE TITLE
[TableSemantic] Expose row and rowIndex to TableSemantic/Table component

### ISSUE THREAD

**Issue by curtislin7** [uber/baseweb#3394]
Related to #3208. Recently, the TableBuilder component was updated to expose col, colIndex, row, and rowIndex such that overrides could access these props (useful for highlighting rows/columns). This has only been done for the TableBuilder component, and not for the table-semantic/table.js component. My request is that this new develop be extended to that other component as well. Given the PR that @chasestarr and @shannonmoeller have already put in to fix #3208, this should be a pretty straightforward change. 

Ideally, I would be able to implement an override like this with the table-semantic/table component. 

For example:

```javascript
import {Table} from "baseui/table-semantic";


const rowExposedTable = () => {
    const [selectedRow, setSelectedRow] = useState(0);
    return (
        <>
            <Table
                data={DATA}
                overrides={{
                    TableBodyRow: {
                        props: {
                            onClick: (e) => {
                                setSelectedRow(e.target.closest('tr').rowIndex);
                            },
                        },
                        style: ({ $theme, $rowIndex }) => {
                            if ($rowIndex === selectedRow) {
                            return { backgroundColor: $theme.colors.warning600 };
                            }
                        },
                    }
                }}
            />
        </>
    );
}

```

More than happy to submit a PR for this change myself, if I get the go ahead!

**Comment by shannonmoeller** [comment]
Whoops! Sorry about that. A PR would be awesome.

**Comment by curtislin7** [comment]
@shannonmoeller on it now, thanks!
