### ISSUE TITLE
Grid Table: Loading

### ISSUE THREAD

**Issue by joselarios** [uber/baseweb#3400]
Is there a way to show loading progress with the Grid Table component? (Loading is available in the Table and Data Table component, but it is not clear to me if, or how, loading works with Grid Table).

Thank you in advance for your help!

**Comment by chasestarr** [comment]
Hi @joselarios if your data is loading, just replace the table or the contents of the table with a loading message. See this example for a starting direction: https://stackblitz.com/edit/react-b8gyw6?file=src/example.js
