### ISSUE TITLE
Icons add extra attributes to dom

### ISSUE THREAD

**Issue by leyanlo** [uber/baseweb#3410]
Icons add props to the dom that are unnecessary.

E.g.
```js
export default () => {
  return <ArrowUp size={64} color="red" />;
}
```

Renders as:
```html
<svg data-baseweb="icon" viewBox="0 0 24 24" title="Arrow Up" size="64" color="red" class="cu s4 q3 pm pn" />
```

The size attribute is not necessary, as it is added as width/height rules by Styletron. Color is also not necessary, as it is added as color/fill rules by Styletron.

I believe this is due to the nature of React.forwardRef(), where setting the prop will get passed all the way down to the svg.

**Comment by chasestarr** [comment]
Created this example to reproduce the issue https://stackblitz.com/edit/react-jdp6ag?file=src/index.js

**Comment by ksnyder9801** [comment]
Related example where even more attributes are added by TreeView (and then passed through Icon, etc.), particularly when the icons are overridden in the theme by a non-`styled` component:
https://stackblitz.com/edit/react-mx9asp?file=src/index.js
