### ISSUE TITLE
Calendar picker: external value does produces unexpected cell color

### ISSUE THREAD

**Issue by bkapus2** [uber/baseweb#3429]
Example:
This can be seeing in the demo provided by
https://baseweb.design/components/datepicker/

## Current Behavior

1.  Type in a date into the input.
2. Click Enter.
3. The selected cell is not solid black.
4. Hover over the cell.
5. The selected cell is now solid black.

## Expected Behavior

The selected cell should be black without having to hover over it.

There must be some expectation that the user is using their mouse to set these values (MouseOver / MouseOut).

**Comment by chasestarr** [comment]
Is this behavior expected @nadiia?

**Comment by nadiia** [comment]
When it's black it means the date is selected and highlighted currently. I don't think it's an issue here. But I found another bug looking into it: it doesn't set tab-index on the newly selected day, so if the new typed in date is in a different month it doesn't let you arrow down into the calendar while keyboard navigating.
