### ISSUE TITLE
Warning: Invalid attribute name: `$size`

### ISSUE THREAD

**Issue by Bomkas** [uber/baseweb#3433]
When I import an icon along this path 

> import {Plus} from 'baseui/icon'

This error appears in the console

`The Warning: Invalid attribute name: '$ size'`
<img width="462" alt="Screen Shot 2020-06-24 at 11 21 37" src="https://user-images.githubusercontent.com/31337482/85521403-e0775080-b60c-11ea-8547-badf22bba185.png">

## My Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.84.0  |
| React   | v16.12.0 |
| Browser | Chrome Version 83.0.4103.106 (Official Build) (64-bit) |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Can you please share a reproduction of this bug? https://stackblitz.com/edit/react-acr6yc?file=src/example.js

**Comment by S0Lucky4Y0u** [comment]
This needs to b pulled it is a violation of google

**Comment by kahwee** [comment]
I think this only happens when you do a createTheme and customized the icons. The customized icons are returned as an SVG and so `$size` gets exposed to the HTML element as an invalid attribute.

**Comment by chasestarr** [comment]
Thank you @kahwee we can investigate
