### ISSUE TITLE
Icon library FontAwesome overriders generated classes.

### ISSUE THREAD

**Issue by 4eshircat** [uber/baseweb#3439]
Icon library FontAwesome use their own class **.fa** which overrides generated by BaseWeb classes.
And when these classes are applied, visual problems occur — you can check it below.

![The Alpinist 2020-06-29 12-15-34](https://user-images.githubusercontent.com/1543843/86017875-414bc200-ba2d-11ea-8efc-60df4a585e4f.png)
![The Alpinist 2020-06-29 12-21-41](https://user-images.githubusercontent.com/1543843/86017930-54f72880-ba2d-11ea-8608-01d62c87c115.png)

Can you make exclusion for **fa** class or what do I need to do?

**Comment by gergelyke** [comment]
I believe you can use the `prefix` option on the Styletron engine: https://www.styletron.org/api-reference#options

**Comment by 4eshircat** [comment]
@gergelyke yes this approach works like a charm.
Thank you 🙌🏻

I just used prefix there:
`const engine = new Styletron({ prefix: '_' });`
