### ISSUE TITLE
ButtonGroup responsive styling

### ISSUE THREAD

**Issue by jackieleighh** [uber/baseweb#3448]
ButtonGroup components do not line wrap - they should line wrap responsively if the container is smaller than the group.

## Current Behavior
buttons do not wrap to next line

## Expected Behavior
buttons should be pushed onto next line

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v?.?.?  |
| React   |         |
| browser |         |

- [ ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by tomcwatts** [comment]
Would the desired behaviour be to simply wrap each button that overflows the container onto the next line? I think from a UI perspective that might not be ideal as usually you would want to do something like stack all buttons vertically or collapse them into a single select dropdown at a certain breakpoint or when they can no longer fit.
