### ISSUE TITLE
Character limit for text input box

### ISSUE THREAD

**Issue by kimasenbeck** [uber/baseweb#3449]
Feature request: 
characterLimit prop on input box (https://baseweb.design/components/input/)
Could also apply on https://baseweb.design/components/textarea/

Character limit text box UI which could serve as example:
![image](https://user-images.githubusercontent.com/10892241/86298201-0d4dd980-bbb2-11ea-9d33-b2ed46411caa.png)

Note: I'm an Uber engineer, and would be very willing to take this on as a baseweb contribution! I've been looking for a way to start contributing :)

**Comment by kahwee** [comment]
Maybe we use just use `maxLength`?

It's part of HTML input.

This doesn't give the visual word count indicator you shown in your example though.

**Comment by chasestarr** [comment]
Related issue here: https://github.com/uber/baseweb/issues/2990 Happy to accept a PR that adds `maxLength` to the top-level api

**Comment by kimasenbeck** [comment]
Excellent! I'll look to have a PR out as soon as I can.

**Comment by chasestarr** [comment]
Sounds good, Thanks!
