### ISSUE TITLE
Combobox example is misleading

### ISSUE THREAD

**Issue by sandgraham** [uber/baseweb#3450]
The [combobox example](https://baseweb.design/components/combobox/#combobox) at the top of the page is a bit misleading. It seems broken because no filtering is being done in the example code.

**Comment by chasestarr** [comment]
@sandgraham I attempted to work on this, but I was not quite sure how a more complex example would look like in yard

**Comment by RisingGeek** [comment]
What enhancement is to be added? I can see that filtering is already implemented here: [https://baseweb.design/components/combobox/#filtered-options](url)

**Comment by sandgraham** [comment]
I think it is fine to close this. The initial intention was to update the yard example to better showcase the typical filtering use case for the combobox.
