### ISSUE TITLE
Internal Billing Problem

### ISSUE THREAD

**Issue by larcho** [uber/baseweb#3457]
I want to start with an apology by saying that I'm aware that this is not related to Baseweb, but I need a software developer at Uber to take a look at this.

I've been struggling with support since weeks with no success because they are not able to see the seemingly internal issue your billing system has with an outstanding transaction.

I currently have an outstanding invoice of PYG 18, which in US Dollars translate to less than a cent of a Dollar. It seems that somewhere in your currency system it's failing with some rounding somewhere and when trying to pay (I already tried with 4 different credit cards) I get the following error:

```
{
    "status": "success",
    "data": {
        "status": "PaymentErrorAmountTooLarge",
        "orderUUID": "858d65fa-fde4-3981-bc67-1d0149fa64b4",
        "additionalErrorDataJson": null,
        "errorKey": null,
        "uberTransactionId": "a53dd08a30b459fb883c76023094e9fc_2"
    }
}
```

My user account is: larcho@gmail.com

I absolutely don't mind this being deleted, but I'd highly appreciate if a developer at Uber can take a look at this.

Thank you again and sorry.

**Comment by gergelyke** [comment]
Hey @larcho - I am sorry for your troubles, but this is not something we can help here. I am going to close this issue.
