### ISSUE TITLE
[Question] Theme settings for tab element focus

### ISSUE THREAD

**Issue by matchatype** [uber/baseweb#3458]
Hitting the tab key to switch focus adds an outline to the focused element set to color accent600. Is there a theme override setting to control the style of focused elements globally?

**Comment by gergelyke** [comment]
hey @matchatype - we use `theme.colors.accent` for the outline, so you'd have to change that. I am going to close this issue, but feel free to reopen, if you have further questions

**Comment by matchatype** [comment]
Many thanks @gergelyke That's consistent with my findings, however my question was about how to control that with theming. For example, I might want to set the outline to a different color or tint in the scale, and adding other rules like border and borderRadius. How would you achieve that?

**Comment by sandgraham** [comment]
@matchatype We don't have a theme property for setting the focus outline color specifically. The only way to customize the color is to change `theme.colors.accent` by [customizing your theme](https://baseweb.design/guides/theming/#a-custom-theme). Unfortunately, if you don't want to change the `accent` color in your theme, you will have to override the focus styling for each component manually.
