### ISSUE TITLE
Select Popover override doesn't work

### ISSUE THREAD

**Issue by 4eshircat** [uber/baseweb#3459]
I need to add `zIndex: 200` to Popover but it seems that  all other props works as expected except Popover.
It doesn't work even on the Select's landing page:
https://baseweb.design/components/select/

My code looks like this:
```
<Select
    options={quarters}
    labelKey="title"
    valueKey="value"
    placeholder="Choose a quarter"
    onChange={({ value }) => setQuarter(value)}
    value={quarter}
    overrides={{
        Popover: {
            style: ({ $theme }) => {
                return {
                    zIndex: 200
                };
            }
        }
    }}
/>
```

**Comment by chasestarr** [comment]
Styles applied to baseui's `Popover` component will not have any effect. You may want to investigate the `mountNode` prop or try applying the styles to the `DropdownContainer` override

**Comment by chasestarr** [comment]
Going to close for now, but feel free to continue the conversation if it doesn't work for you

**Comment by 4eshircat** [comment]
Hi @chasestarr!
Thank you for your answer. I tried both variants you suggested and couldn't get the desired result.

I'm using Select inside a modal window with _z-index: 1031_ and dropdown list displayed behind the window.
I tried to add _z-index: 1032_ to DropdownContainer as you advised but this z-index doesn't help to bring it in front.

Also, I havn't figured out how to mount the dropdown to the specific block.

I implemented both your suggestions there:
https://stackblitz.com/edit/react-ghzc1m?file=src%2Fexample.js

Can you help me please to figure out what's wrong?

**Comment by chasestarr** [comment]
Here's an example: https://stackblitz.com/edit/react-ghzc1m-equjpx

**Comment by 4eshircat** [comment]
> Here's an example: https://stackblitz.com/edit/react-ghzc1m-equjpx

Thank you for you detailed answer with example 🙌🏻

But can you answer why the mount div should be outside the modal?
