### ISSUE TITLE
[Card] title ignores HeadingLevel and renders as <h1> all the time

### ISSUE THREAD

**Issue by shdq** [uber/baseweb#3470]
Hello. First of all, thank you for the base web!

## Current Behavior
Example code:

```
<HeadingLevel>
  <Heading>Header H1</Heading>
  <HeadingLevel>
    <Heading>Header H2</Heading>
    <Card title="Card title still H1">
      <StyledBody>
            Proin ut dui sed metus pharetra hend rerit vel non
            mi. Nulla ornare faucibus ex, non facilisis nisl.
            Proin ut dui sed metus pharetra hend rerit vel non
            mi. Nulla ornare faucibus ex, non facilisis nisl.
      </StyledBody>
    </Card>
  </HeadingLevel>
</HeadingLevel>
```
`<Card title="This is card title">` renders as `<h1>` anyway.

Stackblitz to reproduce [Link]( https://stackblitz.com/edit/react-yd3ejd?file=src%2Fexample.js)

## Expected Behavior

`<Card title="This is card title">` renders as `<h2>`.

Moreover, I suggest adding `<StyledHeader>` like `<StyledBody>` and `<StyledAction>`. It would be more intuitive instead of the title prop. And maybe card title shouldn't be rendered as a header element at all, render a `<div>` like `StyledBody` and let the developer decide what to put there `<Label1>` or `<Heading>`.

All the best, Sergei

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
I tend to agree with the proposal - however, I think it would be a breaking change, right? Do you think we could do it in a non-breaking way?

**Comment by shdq** [comment]
It is breaking change. But both `<StyledHeader>` and `title` can coexist for some time. Mark `title` as deprecated in docs and drop it in the future releases.

**Comment by gergelyke** [comment]
That seems like a reasonable approach. Is it something you'd be willing to take on?

**Comment by shdq** [comment]
I'd like to take it, but I need some guidance. First of all, is it about implementation of `<StyledHeader>`? If so, should I fix `<HeadingLevel>` ignorance by `title`?

**Comment by gergelyke** [comment]
Yes, I believe we should fix that - probably it won't be a StyledHeader component, as it will include some logic, probably just call it `Header`?

**Comment by shdq** [comment]
I looked at the code and it seems intentional to render card title as `<h1>` inside `<section>` according to [whatwg recommendation](https://html.spec.whatwg.org/multipage/sections.html#headings-and-sections) (the last example).
And title style can be changed through `<Card>` overrides:
```
overrides={{
  Title: {
    style: ({ $theme }) => {
      return {
        outline: `${$theme.colors.warning600} solid`,
        backgroundColor: $theme.colors.warning600
      };
    }
  }
}}
```
