### ISSUE TITLE
[Checkbox] onChange doesn't fire on click when using React Concurrent mode

### ISSUE THREAD

**Issue by airhorns** [uber/baseweb#3476]
React's upcoming Concurrent mode has all sorts of awesome new patterns like Suspense and `useTransition`. When using Concurrent mode, baseui's `Checkbox` component doesn't check. The `onChange` handler never fires on click. It does fire however if you tab focus to the checkbox and press space.

Preview issue here: https://baseweb-react-concurrent-checkbox.stackblitz.io (edit here: https://stackblitz.com/edit/baseweb-react-concurrent-checkbox?file=src/index.js)

Concurrent mode isn't supposed to require any code changes to work, so this is pretty strange -- everything else I'm using within baseui has been working fine. I am not super familiar with the baseui source but I couldn't find anything strange that it might be doing that is now broken in concurrent mode (specifically `findDOMNode` isn't a thing anymore), but you can see the compatibility table here: https://reactjs.org/docs/concurrent-mode-adoption.html#feature-comparison

Concurrent mode has not been released yet so I understand if fixing this is a low priority, but, the React team has stated that the old mode of operation (Legacy Mode) is going to go away, so its likely this is going to matter as soon as the new mode is actually released.

Also notable: `onBlur` and `onFocus` seem to be working fine. 
## Current Behavior

`onChange` handlers aren't fired for `Checkbox` or `StatefulCheckbox` components when rendered using React's unreleased concurrent mode.

## Expected Behavior

`onChange` should fire.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | 9.85.2  |
| React   | 0.0.0-experimental-7f28234f8 |
| browser | Chrome latest on OSX |

- [X] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by airhorns** [comment]
Update: this is probably a bug in the experimental Concurrent mode of React itself, we reproduced it outside baseweb over in that React issue.

**Comment by sandgraham** [comment]
Thanks for the update @airhorns - I'll close for now, but let us know if there is something we could change to better support concurrent mode going forwards.

**Comment by airhorns** [comment]
For any intrepid travellers who come along trying to solve this same issue, the React core team suggested `ReactDOM.flushSync(() => { ... })` wrappers around things that set state in focus change handlers. I hacked those into a fork of baseui and it fixed this issue for experimental React versions.
