### ISSUE TITLE
Type wrong for ToggleIcon's component in Accordian component's override when used with Typescript

### ISSUE THREAD

**Issue by peironggg** [uber/baseweb#3477]
## Current Behavior
This problem only occurs when used with Typescript. Within the Accordian component's override prop, I overrode the ToggleIcon I want to be displayed to be an "up" or "down" chevron (depending on whether the Accordian is expanded or collapsed) instead of the default "plus" sign. 
The problem I believe is due to the type of the "component" prop of ToggleIcon, which does not expects the argument `$expanded`. (The type of `$expanded` is `never` as can been seen below when I hover over the error) When I use `$disabled` as the argument instead, the error goes away. Hence, I believe there is just a typing error with the component prop.

## Expected Behavior
There should not be any typing error if I pass in `$expanded` as the argument.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.85.2  |
| React   |    16.13.1     |
| browser |    NA     |

- [ ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.
<img width="540" alt="TS error" src="https://user-images.githubusercontent.com/35712975/87293294-abd42600-c534-11ea-8015-b840ebb630b0.png">
<img width="1149" alt="TS error verbose" src="https://user-images.githubusercontent.com/35712975/87293307-b2629d80-c534-11ea-8c2f-e8778435dcf0.png">
<img width="741" alt="TS no error if argument changed" src="https://user-images.githubusercontent.com/35712975/87293320-b68ebb00-c534-11ea-92db-191334a7a5c8.png">

**Comment by gergelyke** [comment]
thank you for the report @peironggg - is it something you can help with?

**Comment by peironggg** [comment]
I don't mind contributing but I am not completely sure of the way the project is structured. From what I understand all I need to do is change the types?

**Comment by gergelyke** [comment]
That's correct - I believe this is the only file you have to modify: https://github.com/uber/baseweb/blob/master/src/accordion/index.d.ts
