### ISSUE TITLE
Datepicker overrides Input backgroundColor not changing

### ISSUE THREAD

**Issue by arpitprod** [uber/baseweb#3487]
## Current Behavior

I want to change [DatePicker](https://baseweb.design/components/datepicker/) Input color to white color but it's not changing. You can see in [stackblitz code](https://react-hfnn3z.stackblitz.io) 

## Expected Behavior

`DatePicker` color should change like `Input` and `Select` 

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.85.3  |
| React   |  v16.13.1    |
| browser |         |

- [ ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by sandgraham** [comment]
Here is an [example](https://stackblitz.com/edit/react-vjufuy?file=src/example.js) of how to do this. You have to use what we call a [Nested Override](https://baseweb.design/guides/understanding-overrides/#override-nested-components).
