### ISSUE TITLE
Tabs motion is missing

### ISSUE THREAD

**Issue by simPod** [uber/baseweb#3509]
Hello, I found https://baseweb.design/components/tabs-motion/ section in documentation. I have the same version installed as is in docs header (9.86.0). However, there's no tabs-motion module in node_modules. Am I doing something wrong? Thanks!

![image](https://user-images.githubusercontent.com/327717/87791810-2eb1f500-c843-11ea-89de-37a8f411dc89.png)

**Comment by gergelyke** [comment]
hey! we'll cut a release later today, it will be included in 9.87. sorry about the confusion!

**Comment by simPod** [comment]
Ah, I had perfect timing it seems :D thanks!
