### ISSUE TITLE
[TabsMotion] If Tabs are wrapped in form, the form submits on tab change

### ISSUE THREAD

**Issue by houmark** [uber/baseweb#3519]
## Current Behavior

Please see this Stackblitz for example:
https://stackblitz.com/edit/react-szam3j?file=src/example.js

This is different behavior than the old tabs component.

## Expected Behavior

Only the tab changing, no submission of a wrapping form.

I think the solution is simple, and that is to add `type="button"` to the Tab button, if no type is set, it will default to submit.

I have not yet tested that solution, as I don't have BaseWeb set up in development mode (I really should get to that).

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.87.0  |
| React   |    16.8     |
| browser |    Chrome     |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by houmark** [comment]
That's what I call fast fixing :) Early adopter here, loving this new component in terms of design and animation, and besides this one, it was very simple to swap the components out.

**Comment by gergelyke** [comment]
sure, you are welcome 👍 

and yeah, you should set up a local dev env for Base Web :) should be pretty simple, but let us know if you run into any issues!
