### ISSUE TITLE
DatePicker component. How to start a week from Monday?

### ISSUE THREAD

**Issue by 4eshircat** [uber/baseweb#3527]
Actually I already asked a question in the title :)
I didn't find how to do this so can you drop a hint please?

Thank you 🙏🏻

**Comment by shdq** [comment]
Hello Mikhail.

You should import locale from `date-fns`, I suppose it's `ru` and pass it to the datepicker as a prop. It will do the magic.

There is an example with customized `mask` and `placeholder` and `formatString`.

```
import * as React from 'react';
import {Datepicker} from 'baseui/datepicker';
import ru from 'date-fns/locale/ru';

export default () => (
  <Datepicker
    locale={ru}
    onChange={({date}) => console.log(date)}
    mask="ДД.ММ.ГГГГ"
    placeholder="ДД.ММ.ГГГГ"
    formatString="dd.MM.yyyy"
  />
);
```

**Comment by gergelyke** [comment]
thank you @shdq 🤗

**Comment by gergelyke** [comment]
for future reference, the corresponding doc site example can be found here: https://baseweb.design/components/datepicker/#datepicker-with-localization

**Comment by 4eshircat** [comment]
@shdq @gergelyke thanks a lot guys!
I'm very appreciate your help 😌🙏🏻
