### ISSUE TITLE
[Slider] click[touch] area of a track is too narrow, impossible to change the value by clicking on [touching] the track

### ISSUE THREAD

**Issue by shdq** [uber/baseweb#3528]
## Current Behavior

If you have only 2-3-4 steps in the slider it's almost impossible to change the value by clicking on [touching] the track.
Also when you start pulling the thumb you have to move it precisely on the desired value or it won't change.

[Stackblitz to try](https://stackblitz.com/edit/react-rbupcr)

```
import * as React from "react";
import { Slider } from "baseui/slider";

export default () => {
  const [value, setValue] = React.useState([1000]);
  return (
    <Slider
      value={value}
      onChange={({ value }) => value && setValue(value)}
      onFinalChange={({ value }) => console.log(value)}
      min={500}
      max={1500}
      step={500}
    />
  );
}
```

## Expected Behavior

Clicking on [touching] the track should change to the next closest step. Previous one if you click after the thumb or the next one if you click before the thumb.

When you start pulling thumb, the slider should change the value to the closest tick on track at the time you released the thumb.

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
It seems like that something we should address in https://github.com/tajo/react-range

@shdq is it something you could help with?

**Comment by tajo** [comment]
Fixing this in react-range and soon here.

**Comment by williamernest** [comment]
This issue appears to be resolved with the latest updates to react-range. Closing this for now, but don't hesitate to re-open it if you continue to have issues.
