### ISSUE TITLE
[File-uploader] Allow to override Spinner

### ISSUE THREAD

**Issue by kizmo04** [uber/baseweb#3529]
## Feature description
I'm trying to override `Spinner` component in `FileUploader` component. I want to change spinner's active path color. but there is no way overrides Spinner component styles.
that would be great to have an opportunity to override spinner component. Is there anyone working on this issue? If not, may I take it?

**Comment by gergelyke** [comment]
that would be a great addition! I've just assigned this issue to you, thanks @kizmo04!

**Comment by sandgraham** [comment]
This was added in #3541. You can override the Spinner now like so:
```js
<FileUploader overrides={{ Spinner: {/* style, props, component */}  }} />
```
