### ISSUE TITLE
[Select] Value attribute of input inside Select component stays empty on Select change.

### ISSUE THREAD

**Issue by 4eshircat** [uber/baseweb#3545]
Hi!
I'm using a [react-hook-form](http://react-hook-form.com) library that validates fields based on the name and value attributes. The problem is that the Select component doesn't update the value attribute of its input when it changes.
Therefore, the Select component cannot pass validation even when it is valid.

So my question is, how can I update the input value attribute that is inside the component?

<img width="514" alt="image" src="https://user-images.githubusercontent.com/1543843/88372484-a54c7680-cd9e-11ea-8f4f-a23f97d451e4.png">

**Comment by gergelyke** [comment]
hey @4eshircat 👋 

I am not familiar with that library, but is it possible to expect the Select's value prop directly, instead of from the DOM?

If not, would it be something you'd be willing to help with, and raise a PR?

**Comment by 4eshircat** [comment]
> I am not familiar with that library, but is it possible to expect the Select's value prop directly, instead of from the DOM?
Unfortunately not, but I think there are many other libraries out there that work with DOM directly. So I think this is an important issue.

> If not, would it be something you'd be willing to help with, and raise a PR?
Okay, I will try 👌🏻

**Comment by sandgraham** [comment]
@4eshircat would [controlling a hidden input](https://stackblitz.com/edit/react-28mrly?file=src/example.js) work for your use case?

**Comment by 4eshircat** [comment]
> @4eshircat would [controlling a hidden input](https://stackblitz.com/edit/react-28mrly?file=src/example.js) work for your use case? If not, a repro would be helpful using the validation library.

Thank you for your reply 🙌🏻
Yes, I did it this way, but it doesn't looks like the solution from the box. I mean when you can use a component like a standard select without having to think about how it's built 🤷🏻‍♂️

**Comment by sandgraham** [comment]
@4eshircat Glad you found a workaround. If you could, would you mind creating a small sandbox reproducing your initial issue with this library? Might be a small change on our side could make the integration smoother with these types of form libraries.

**Comment by konradkalemba** [comment]
Hey @4eshircat 

React Hook Form library has a [`Controller` component](https://react-hook-form.com/api/#Controller) made to deal with custom form components. I used it with success in my projects, here's a snippet:

```js
const { control } = useForm();

<Controller
  control={control}
  name={"example"}
  rules={{
    required: true
  }}
  render={({ onChange, onBlur, value }) => (
    <Select
      value={value}
      onChange={(params) => onChange(params.value)}
      onBlur={onBlur}
      // rest props
    />
  )}
/>
```

Make sure to set `defaultValues` of your select input in `useForm` hook though. Otherwise it won't reset itself when using `reset` method.

If you plan to use it more than once I recommend you to create yourself a helper component to avoid duplicated code. Mine looks like this:
```js
export function ControlledSelect({
  control,
  name,
  rules,
  ...rest
}) {
  return (
    <Controller
      control={control}
      name={name}
      rules={rules}
      render={({ onChange, onBlur, value }) => (
        <Select
          value={value}
          onChange={(params) => onChange(params.value)}
          onBlur={onBlur}
          {...rest}
        />
      )}
    />
  );
}
```

**Comment by 4eshircat** [comment]
> Hey @4eshircat
> 
> React Hook Form library has a [`Controller` component](https://react-hook-form.com/api/#Controller) made to deal with custom form components. I used it with success in my projects, here's a snippet:
> 
> ```js
> const { control } = useForm();
> 
> <Controller
>   control={control}
>   name={"example"}
>   rules={{
>     required: true
>   }}
>   render={({ onChange, onBlur, value }) => (
>     <Select
>       value={value}
>       onChange={(params) => onChange(params.value)}
>       onBlur={onBlur}
>       // rest props
>     />
>   )}
> />
> ```
> 
> Make sure to set `defaultValues` of your select input in `useForm` hook though. Otherwise it won't reset itself when using `reset` method.
> 
> If you plan to use it more than once I recommend you to create yourself a helper component to avoid duplicated code. Mine looks like this:
> 
> ```js
> export function ControlledSelect({
>   control,
>   name,
>   rules,
>   ...rest
> }) {
>   return (
>     <Controller
>       control={control}
>       name={name}
>       rules={rules}
>       render={({ onChange, onBlur, value }) => (
>         <Select
>           value={value}
>           onChange={(params) => onChange(params.value)}
>           onBlur={onBlur}
>           {...rest}
>         />
>       )}
>     />
>   );
> }
> ```

Thank you for this very detailed answer!
Everything works like a charm 😌
