### ISSUE TITLE
Allow to extend/customize TabPanel globally

### ISSUE THREAD

**Issue by simPod** [uber/baseweb#3548]
I attempted to extend TabPanel:

```ts
const CustomTabPanel = withStyle(StyledTabPanel, () => (
  {
    paddingLeft: 0,
    paddingRight: 0,
  }
));
```

But AFAIK it's not possible to use it this way as it's impossible to override TabPanel component within `tab-motion` `Root` as it's rendered directly by mapping `Tab` children.

https://github.com/uber/baseweb/blob/5f92bdfef0a8461e79f9517623eb4288bf552577/src/tabs-motion/tabs.js#L224

**Comment by gergelyke** [comment]
@sandgraham can you help with this question?

**Comment by sandgraham** [comment]
Hi @simPod there are a few ways to do this- depending on what you want to accomplish.

You can use your custom component using overrides [as in this example](https://stackblitz.com/edit/react-bscfkq?file=src/example.js):

```js
<Tab overrides={{TabPanel: {component: CustomTabPanel}}} />
```

If you only want to override styles you can avoid passing in a full component and just override styles:
```js
<Tab overrides={{TabPanel: {style: {paddingLeft: 0, paddingRight: 0}}}} />
```

Also, if you only want to remove padding, TabPanel has a styling prop for that which basically does `padding: 0`.

```js
<Tab overrides={{TabPanel: {prop: {$pad: false}}}} />
```

**Comment by simPod** [comment]
Hi @sandgraham, thanks for your response. Though my point is that I cannot do this globally by creating custom component or something similar. Let's say I do this for all my tabs

```jsx
<Tab overrides={{TabPanel: {style: {paddingLeft: 0, paddingRight: 0}}}} />
```

and then decide to add `paddingBottom: 0` so I have to change it on all places. Instead, if I was able to create my component that encapsulates my general tab definition, I could just change it there.

**Comment by houmark** [comment]
I'd usually keep the style object in a system-wide file and import it per component and then if I need to tweak it on one page, I'd just do:

```
<Tab overrides={{TabPanel: {style: ...defaultTabStyle, paddingBottom: '10px' }}} />
```

But I don't see why you cannot make a wrapping component that outputs the outer Tab component.

**Comment by simPod** [comment]
> I'd usually keep the style object in a system-wide file

doing the same now, don't fancy it much though.

> But I don't see why you cannot make a wrapping component that outputs the outer Tab component.

I tried so but it does not work for some reason, I guess it's because of some internal design of rendering Tab and TabPanels 🤔 

https://codesandbox.io/s/baseweb-nklju?file=/src/example.tsx

**Comment by sandgraham** [comment]
@simPod this approach doesn't work because the `Tab` components are never rendered - they are mapped to internal `Tab` and `TabPanel` components. If you want to create a wrapper for the `Tabs` component it should look something like [this sandbox](https://codesandbox.io/s/baseweb-tabs-motion-custom-g7n52?file=/src/example.tsx). Note, you might want to deep merge overrides passed in with the custom wrapper overrides so you can still pass them in later on- depends on your usage.

**Comment by simPod** [comment]
Yes, I have found this out as I have been examining rendering logic in https://github.com/uber/baseweb/blob/5f92bdfef0a8461e79f9517623eb4288bf552577/src/tabs-motion/tabs.js#L224

So the recommended solution is to extend Tabs instead of Tab. Will do, thanks!
