### ISSUE TITLE
TypeScript locale definition does not align with docs

### ISSUE THREAD

**Issue by liegeandlief** [uber/baseweb#3572]
## Current Behavior

The shape of the locale file described at https://baseweb.design/guides/internationalization/ does not match the TypeScript definition in `baseui/locale.ts`. For instance the docs define many more date picker strings than the TypeScript interface. When passing an object of the shape described in the docs to the `LocaleProvider` I get a type error because it does not match the TypeScript definition. I am not sure whether the docs are correct or the TypeScript definition is correct.

## Expected Behavior

The docs and TypeScript definition should align.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.91.0 |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Thanks for the report @liegeandlief We primarily use flow types and the typescript definitions are copied from flow so there are bound to be discrepancies. Feel free to submit a PR correcting it!

**Comment by liegeandlief** [comment]
@chasestarr I have updated the TypeScript locale types to match the Flow types. See the PR at https://github.com/uber/baseweb/pull/3576
