### ISSUE TITLE
Select doesn't update when new options are provided

### ISSUE THREAD

**Issue by vqrulane** [uber/baseweb#3626]
## Current Behavior
The prop `options` in `<Select />` changes, but they aren't rendered. Instead, I see "No results".

## Expected Behavior
The component renders new options.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | 9.92.0 |
| React   | 16.9.0 |
| browser | Latest Firefox DE |

- [ x ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by vqrulane** [comment]
Additional information: it updates on input reset, which is not an option for me.

**Comment by chasestarr** [comment]
Can you please share a reproduction example? Try using this as a base: https://stackblitz.com/edit/react-bs5wda?file=src/example.js

**Comment by chasestarr** [comment]
Closing this, but feel free to share a reproduction. If I understand the bug report correctly, I don't think it's an issue. We have lots of known applications that fetch select options

**Comment by vqrulane** [comment]
It's likely I used the wrong component for the problem I was trying to solve. `<Combobox />` did work for me. Sorry for late response.
