### ISSUE TITLE
Tag component don't allow you to change icon through theme definition

### ISSUE THREAD

**Issue by mramosvi** [uber/baseweb#3638]
Issue detected when try to change through theme definitions the icon tag component. Other components allow to change the icon throughout the Theme, like Button or Paginator, but in the tag component, seems like the <svg> icon is not using the Theme in the core library.

You could see this issue in this stackblitz:
https://stackblitz.com/edit/wb6upm--run?file=src/example.js

## Current Behavior
When using the tag component and try to change the "Delete" icon to a custom icon using ThemeProvider the icon doesn't change.

## Expected Behavior
The tag component icon should change throughout theme definitions like occurs with other components like Button or Paginator.

## Your Environment
Seeing BaseWeb library code it seems that in tag component the icon is defined without passing through the theme, as in other components, and that's why the icon couldn't change through theme definitions.

| Tech    | Version |
| ------- | ------- |
| Base UI | latest  |
| React   |    16.12.0     |
| browser |    all     |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by lhbrennan** [comment]
Hi @mramosvi, the stackblitz link you provided is down. Do you have an alternative example I can check out?

**Comment by xMartax** [comment]
Hello, sorry long time ago, 1 year... but it was related to the Icon "close" of the tag component, so that icon cannot be changed, also in general you are not able to put your custom icons on the components, you can only switch the icons with other custom component but then you are losing all the icon states and needs to develop again.
