### ISSUE TITLE
Feature Request: Update TimezonePicker format

### ISSUE THREAD

**Issue by ajbogh** [uber/baseweb#3645]
## Problem

The timezone picker display format is very confusing and out of order. The display follows:

`Country/Location (GMT -xx:yy)`
**Or** 
`TimeCode - Country/Location (GMT -xx:yy)`
**Or**
`Etc/GMT+6 (GMT -06:00)`
**Or** 
`TimeCode - Timecode (GMT -xx:yy)`

All of these formats are sprinkled together with no ordering besides the offset at the end of the text (shown in the image below).

![Screenshot_2020-08-17_11-44-09](https://user-images.githubusercontent.com/161761/90432163-00604900-e07f-11ea-9e92-bab41dbd7645.png)

## Feature description

I'm requesting that timezones are filtered and formatted to display the offset first then the Country/Location afterward. An example to change the default format using existing code is below. The resulting image is also below. The resulting format increases clarity, makes the sorting method understandable, and removes extraneous timezones.

![Screenshot_2020-08-17_11-48-58](https://user-images.githubusercontent.com/161761/90432621-aad86c00-e07f-11ea-9e95-0f1dffad23f5.png)

```
<TimezonePicker
      value={value || 'Etc/UTC'}
      mapLabels={option => {
        const { label, offset } = option;
        // negative offset is a positive value
        const offsetHours = -1 * (offset / 60);
        const offsetSign = offsetHours >= 0 ? '+' : '';
        // This variable assignment is unnecessary but (label: any) breaks code coloring
        const anyLabel: any = label;
        let newLabel: string = anyLabel;

        newLabel = newLabel.substring(0, newLabel.indexOf('(GMT')).trim();
        newLabel = newLabel.substring(newLabel.indexOf(' - ') + 3).trim();
        newLabel = newLabel.replace(/^Etc\//, '');

        // Filter out some timezones
        if (
          /GMT[-+][0-9]*$/.test(newLabel) ||
          [
            'EET',
            'MET',
            'CET',
            'WET',
            'EST5EDT',
            'EST',
            'CST6CDT',
            'MST7MDT',
            'PST8PDT',
            'MST',
            'HST',
          ].includes(newLabel) ||
          (filterOption != null && !filterOption(option))
        ) {
          return '';
        }

        return `(GMT ${offsetSign}${offsetHours}) ${newLabel}`;
      }}
      onChange={onChange}
      disabled={disabled}
      overrides={{
        // eslint-disable-next-line react/display-name
        Select: {
          props: {
            filterOptions: options => options.filter(option => !!option.label),
          },
        },
      }}
    />
```

**Comment by sandgraham** [comment]
This seems reasonable. I'll bring this up at our next design sync.

**Comment by JerHowden** [comment]
Any updates on this issue?

**Comment by sandgraham** [comment]
Design did approve this change but it hasn't been prioritized yet. cc @chasestarr
