### ISSUE TITLE
Feature Request: Add Timezone Map similar to Ubuntu's timezone picker

### ISSUE THREAD

**Issue by ajbogh** [uber/baseweb#3646]
The timezone picker includes a long list of locations, making it difficult to find the desired timezone. A great feature of various OSes is a timezone map which displays the world separated into timezone regions. Selecting a timezone is as easy as clicking on the map near the desired location.

## Feature description

Create a method of displaying a timezone map to select the timezone. This can be a new component (TimezonePickerMap) or a property of the TimezonePicker (`showMap={boolean}`)

## Map Examples:

**Ubuntu's map:**
![Screenshot_2020-08-17_11-52-24](https://user-images.githubusercontent.com/161761/90433382-99dc2a80-e080-11ea-9183-850d057df2db.png)

**Old Ubuntu map**
![Screenshot_2020-08-17_12-01-22](https://user-images.githubusercontent.com/161761/90433933-7cf42700-e081-11ea-975a-c4da5b834313.png)

**Javascript Example:**
https://codesandbox.io/s/cp42d?file=/src/TimezonePicker.js

![Screenshot_2020-08-17_11-57-35](https://user-images.githubusercontent.com/161761/90433564-e3c51080-e080-11ea-9e90-6e41b369e45d.png)

https://bl.ocks.org/ewheeler/2be7373ca280d667d6e0

![Screenshot_2020-08-17_11-58-44](https://user-images.githubusercontent.com/161761/90433653-09eab080-e081-11ea-8c16-f9193e6729ce.png)

**Comment by sandgraham** [comment]
I'll bring it up at our next design sync. That said, I don't think it makes sense to include it in `baseweb` unless this type of input is much more common than I realize. If we were to include it, it would likely need to be a new component for bundling purposes.

**Comment by sandgraham** [comment]
Hey @ajbogh - I spoke with design and we aren't planning to support this feature in Base. If you think it is something worth considering further, you and your team's designer can reach out to the design platform team. Feel free to ping me if you need any help with that.
