### ISSUE TITLE
[styled] relax prop type when no style object provided

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#3659]
Instantiating a styletron-component like `styled('div')` is valid (although not very useful) but will type props as exactly `{||}`. This type makes it so the created element will not accept any props. This should be relaxed to `{}`.

https://github.com/uber/baseweb/blob/master/src/styles/styled.js#L38

**Comment by chasestarr** [comment]
The code below should pass flow type-check

```js
import { styled } from 'baseui';
const A = styled('div');
function B() {
  return <A>hello</A>;
}
```

**Comment by RisingGeek** [comment]
I would like to work on this issue. Please assign this to me.
