### ISSUE TITLE
reversed rounded corner on RTL with enhancers

### ISSUE THREAD

**Issue by wael-mohamed** [uber/baseweb#3688]
## Current Behavior

<img width="645" alt="Screen Shot 2020-08-25 at 20 40 41" src="https://user-images.githubusercontent.com/24360200/91219877-40749b00-e713-11ea-9ad2-1524a44049d4.png">

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.95.2  |
| React   |     v^ 16.13.1   |
| browser |   chrome      |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Thanks for the report @wael-mohamed Can you please share a reproduction case? You can fork this example to get started https://stackblitz.com/edit/react-dckpko?file=src/example.js

**Comment by wael-mohamed** [comment]
please check this [link](https://stackblitz.com/edit/react-dckpko-27onsl?file=src/index.js)

**Comment by sandgraham** [comment]
@wael-mohamed - We've had a recent design change to input enhancers. Check out [this fork](https://stackblitz.com/edit/react-dckpko-b2n58o?file=src%2Fexample.js) of your example using the latest baseweb. 

As you can see from the stackblitz link, updating to the latest version should sort out RTL this issue for you. If you find other RTL issues though please let us know!

**Comment by wael-mohamed** [comment]
It works fine, thanks for your patience
