### ISSUE TITLE
[Accordion] Icon shrinks when texts overflows to multiple lines

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#3707]
example: https://stackblitz.com/edit/react-d3zk7x?file=src/example.js

<img width="593" alt="Screen Shot 2020-08-28 at 2 20 34 PM" src="https://user-images.githubusercontent.com/5317799/91616003-a80c2f80-e939-11ea-9bc0-017f78589783.png">

**Comment by maulik1729** [comment]
@tajo @chasestarr @sandgraham please review this change
