### ISSUE TITLE
[Textarea] TS type def does not include clearOnEscape prop

### ISSUE THREAD

**Issue by simPod** [uber/baseweb#3740]
## Current Behavior

Docs states there's `clearOnEscape` prop on `Textarea`
```ts
import * as React from "react";
import { Textarea } from "baseui/textarea";

export default () => {
  const [value, setValue] = React.useState("Hello");
  return (
    <Textarea
      value={value}
      onChange={e => setValue(e.target.value)}
      placeholder="Controlled Input"
      clearOnEscape
    />
  );
}
```

but there is none. Should it be there?

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.98.0  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Hi @simPod try setting the 'clearable' prop to true

**Comment by simPod** [comment]
That one works, my issue here is with `clearOnEscape` whether it actually should exists or not be in docs? Can send a PR eventually to remove it.

**Comment by chasestarr** [comment]
Right, `clearOnEscape` does not have an effect unless `clearable` is true

**Comment by simPod** [comment]
But the prop `clearOnEscape` does not exists neither on `TextareaProps` or `BaseInputProps`. Is that a bug?

**Comment by chasestarr** [comment]
Here is the type def of `BaseInputProps` https://github.com/uber/baseweb/blob/master/src/input/types.js#L128

**Comment by simPod** [comment]
It is somehow not being propagated into the distribution. I'm on version 9.99.0 but in node_modules/baseui/input/index.d.ts there's this definition

```ts
export interface BaseInputProps<T> {
  'aria-errormessage'?: string;
  'aria-label'?: string;
  'aria-labelledby'?: string;
  'aria-describedby'?: string;
  adjoined?: ADJOINED[keyof ADJOINED];
  autoComplete?: string;
  autoFocus?: boolean;
  clearable?: boolean;
  disabled?: boolean;
  error?: boolean;
  positive?: boolean;
  id?: string;
  'data-baseweb'?: string;
  inputMode?: string;
  pattern?: string;
  inputRef?: React.Ref<T>;
  name?: string;
  onBlur?: React.FocusEventHandler<T>;
  onChange?: React.FormEventHandler<T>;
  onKeyDown?: React.KeyboardEventHandler<T>;
  onKeyPress?: React.KeyboardEventHandler<T>;
  onKeyUp?: React.KeyboardEventHandler<T>;
  onFocus?: React.FocusEventHandler<T>;
  overrides?: BaseInputOverrides<SharedProps>;
  placeholder?: string;
  required?: boolean;
  size?: SIZE[keyof SIZE];
  type?: string;
  value?: string | number;
  rows?: number;
  min?: number;
  max?: number;
  step?: number;
}
```

It's very different from the master. How is so?

**Comment by chasestarr** [comment]
Oh I linked the flow type file, it looks like it's missing from the ts types. We don't use ts at uber so we're not able to proactively catch issues there. Please open up a PR if you'd like to add it. I will update this issue title to reflect that task
