### ISSUE TITLE
Can't Override Tag Styles in Multi Select Component

### ISSUE THREAD

**Issue by JerHowden** [uber/baseweb#3768]
## Current Behavior

Tag in a Select with the `multi` prop does not take override styling on the website or my local environment.

<img width="584" alt="Screen Shot 2020-09-16 at 2 44 41 PM" src="https://user-images.githubusercontent.com/18561982/93384993-2c601d00-f82b-11ea-8a3a-866b8eb5da77.png">

## Expected Behavior

The Tag should be outlined and have the background color of Warning200

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.99.0  |
| React   | 16.13.1  |
| browser |  chrome  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
This is available as a nested override. Example here https://stackblitz.com/edit/react-sud3pn?file=src/example.js

We're looking into how to best document when this is the case. Thank you for opening the issue
