### ISSUE TITLE
Input type - number - not showing increment and decrement button in responsive view

### ISSUE THREAD

**Issue by png-prakash** [uber/baseweb#3775]
Hi

In chrome, not showing increment and decrement button not showing in input field for number format in mobile view. In firefox it showing properly

```
<Input
    size={SIZE.mini}
    type="number"
    name="input_qty"
    autoComplete="off"
    min="0"
    max={product.qty}
    onKeyPress={ e =>  e.preventDefault() }
    value={productQty}
    overrides={{
      Root: {
        style: () => {
          return { width: "75px" };
        }
      }
    }}
    onChange={e => setProductQty(e.target.value)} />
```

https://react-m5jiet.stackblitz.io/

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.99.0  |
| React   |   16.12.0      |
| browser |     Chrome    |

**Comment by chasestarr** [comment]
This looks like appropriate behavior for chrome users. See a default number input on mdn here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number
