### ISSUE TITLE
react-router StyledLink

### ISSUE THREAD

**Issue by austingreco** [uber/baseweb#3777]
It would be nice to be able to use the baseui style with a react-router `<Link>` element. Could we provide the style of StyledLink as an exportable function, or maybe export a wrapper which would allow you to pass in a `Link` component to be styled instead of `'a'`.

**Comment by sandgraham** [comment]
You can do this:
```js
import {Link} from "react-router-dom"
import {StyledLink} from "baseui/link"

export default () => <StyledLink $as={Link} to="/about">About</StyledLink>
```
Or check out [this example](https://stackblitz.com/edit/react-iungpy?file=src%2Fexample.js).

**Comment by adenta** [comment]
This tactic does not play nicely with typescript defs

**Comment by sandgraham** [comment]
@adenta - Since we use Flow internally we don't have coverage for a TS version of this. If you think we need to fix something on our end could you open a new issue for the errors you're seeing in TS?

**Comment by unnhao** [comment]
WOW, why can do that?
