### ISSUE TITLE
ContextMenu component

### ISSUE THREAD

**Issue by DiegoGrandeAlagon** [uber/baseweb#3781]
## ContextMenu component
I would like to create the contextMenu component based on the Popover. Does the library have any properties or components for that?
Thanks in advance

**Comment by chasestarr** [comment]
Hi @DiegoGrandeAlagon Can you please describe what you mean by a context menu? You can use baseui's `Menu` component inside of a `Popover` to do what I assume you're looking for

**Comment by DiegoGrandeAlagon** [comment]
Yes, that's the idea. My problem is that I need to open the Popover with the right-click event. A possible solution is to use the stateless component but I want to keep the rest of the properties (e.g. onClickOutside()). Any idea?

**Comment by chasestarr** [comment]
Here's how I would do it https://stackblitz.com/edit/react-3zoxj8?file=src/example.js

**Comment by DiegoGrandeAlagon** [comment]
Great solution!!!
