### ISSUE TITLE
[DatePicker] triggers Invalid DOM property `readonly`

### ISSUE THREAD

**Issue by RisingGeek** [uber/baseweb#3785]
DatePicker component gives the following warning - Invalid DOM property `readonly`. Did you mean `readOnly`?

## Current Behavior
Warning for `readonly` DOM property

## Expected Behavior
Warning should not be there

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | 9.101.0 |
| React   | 16.13.1 |
| browser | Chrome 85.0.4183.121 |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Can you please share a reproducing example? Use this to get started https://stackblitz.com/edit/react-gmsb66?file=src/example.js

**Comment by RisingGeek** [comment]
I am not getting the warning in Stackblitz. But, when I run the project locally and open datepicker component, I get the warning

**Comment by williamernest** [comment]
Feel free to reopen this issue if you can reproduce with a stackblitz, but there may be other things going on with your local environment that we can't diagnose.
