### ISSUE TITLE
Input: Typescript Type Missing new 'maxLength' prop

### ISSUE THREAD

**Issue by mckoon** [uber/baseweb#3790]
#2990 added a new 'maxLength' prop to the Input component.

The 'maxLength' prop is missing from the TypeScript definitions, preventing it from being used in TypeScript projects:
https://github.com/uber/baseweb/blob/master/src/input/index.d.ts#L37

## Current Behavior
TypeScript builds fail if 'maxLength' is used on an 'Input'.

```
Property 'maxLength' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Input> & Readonly<InputProps> & Readonly<{ children?: ReactNode; }>'.  TS2769
```

## Expected Behavior
TypeScript builds work.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.101.0  |
| React   | v16.13.1  |

- [X ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by MihirGH** [comment]
I'd like to take up this issue. I'll raise the PR shortly or will ask for help if stuck.
