### ISSUE TITLE
Feature: Modular and less opinionated usage

### ISSUE THREAD

**Issue by fabianlee1211** [uber/baseweb#3792]
## Feature description
Are there any plans on letting us install components individually in the future like what other UI libraries do, for example MaterialUI and ChakraUI? And also any possibility to not rely on `styletron` and overrides, and simply let us implement any styling system we want? 

It will be great to be able plug and play some incredible components like DatePicker / Timezone etc. with less overhead. I worked on a project using `styled-components` and I know the docs mentioned that we can use it along with `styletron`. Unfortunately, correct me if I'm wrong, it wasn't simple to override styles with `styled-components`. I had to somehow add `!important` to actually make styling work. I know using overrides / styletron are the suggested way but it is kind of blobbing the components with their syntax. I think these improvements will make Base Web more accessible and preferrable to other fellow devs, and reach more users as a result.

Thanks!

**Comment by chasestarr** [comment]
Hi @fabianlee1211. If I understand correctly, you can replace any sub-component through overrides as [described here](https://baseweb.design/guides/understanding-overrides/#override-the-entire-subcomponent). With that, I think whatever styling option would work fine.

There's no plan to create some styling abstraction to plugin other options. Besides personal preference, are there technical issues with styletron that you are blocked by?

**Comment by sandgraham** [comment]
We have no plans to support other styling utilities at the moment, though as Chase said, you can use overrides to work with parallel styling tools.

We also have no plans to publish components separately. That would entail a pretty large restructuring and I'm not sure what benefits it would actually confer.
