### ISSUE TITLE
Documentation sites for few previous versions aren't working

### ISSUE THREAD

**Issue by konradkalemba** [uber/baseweb#3806]
## Current Behavior

The following documentation sites for previous Base Web versions aren't working. 

1. https://v9-101-0.baseweb.design/
2. https://v9-100-0.baseweb.design/
3. https://v9-99-0.baseweb.design/
4. https://v9-98-0.baseweb.design/
5. https://v9-96-0.baseweb.design/

<details>
  <summary>Chrome error screenshot</summary>
  
  ![image](https://user-images.githubusercontent.com/8682104/94940279-94715d00-04d3-11eb-99ba-e7e95b7ab55a.png)
</details>

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Thanks for reporting. New deployments should be fixed now and I've published these missing versions.
