### ISSUE TITLE
Slider error onChange: Cannot read property 'getBoundingClientRect'

### ISSUE THREAD

**Issue by wamburu** [uber/baseweb#3811]
## Current Behavior

Slider throws
`Error in react-range@1.8.0/lib/utils.js Cannot read property 'getBoundingClientRect' of null` when trying to change value.

Repo: https://stackblitz.com/edit/react-y8yshw

This seems to be an issue with [`react-range >= v1.7.0` ]https://github.com/tajo/react-range/blob/a8d5a9d9562aa742995581c6e64b4f31a036fc72/src/utils.ts#L434) or maybe am just missing something that is not clear in the docs.  
## Expected Behavior

Smooth value change on sliding.

Works okay in version `=< 9.99.0`

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.102.0  |
| React   |   16.13.1      |
| browser |  Chromium 85.0.4183.121  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
I tested this a bit and it's only reproducible in stackblitz. Is it causing you issues in your application?

**Comment by wamburu** [comment]
Yes. Just redid it in a new react-app and it throws the error in the dev tools console.
Here is a repo to reproduce it locally https://github.com/wamburu/baseui-slider

**Comment by chasestarr** [comment]
Thank you for creating that repro case

**Comment by wamburu** [comment]
Thanks for the fix.

**Comment by ariannargesi** [comment]
I have the same issue here
so what is the solution?
