### ISSUE TITLE
[Progress Steps] Design update issues

### ISSUE THREAD

**Issue by sandgraham** [uber/baseweb#3820]
See comment here: https://github.com/uber/baseweb/pull/3703#issuecomment-698003566

> Here are a before and after picker of the progress steps in my app
> https://imgur.com/a/USOW6ui
> 
> this update made the margins much larger than they were before for steps we are not currently on.
> 
> Also if you view https://baseweb.design/components/progress-steps/ in dark mode, there is a weird, non-transparent black box surrounding the circles.

- Need to fix dark mode node backgrounds
- Margin between nodes seems a bit large

**Comment by akshatnitd** [comment]
@sandgraham Can I work on it?

**Comment by sandgraham** [comment]
@akshatnitd - Just assigned it to you -- thanks!

**Comment by adenta** [comment]
@chasestarr are the margin changes permanent? I think reverting them to be smaller when collapsed looks cooler (see screenshots).

**Comment by adenta** [comment]
@sandgraham just wanted to bump this one last time, that the margin changes should really be reverted, so the margins stay small while collapsed.

**Comment by sandgraham** [comment]
@adenta - I'll add this to our queue to double check and update the issue shortly.
