### ISSUE TITLE
Button round styling wrongfully uses 50% border radius

### ISSUE THREAD

**Issue by chimp1nski** [uber/baseweb#3824]
As far as I can see, the `<Button shape="round" />` styling isn't implemented correctly.
Instead of having rounded corners, the buttons is rendered in an ellipse.

## Current Behavior

`<Button shape="round" />` uses `border-radius: 50%` in order to round it's corners.
This results in the button rendering as an ellipse.

![image](https://user-images.githubusercontent.com/34653237/95985122-7cc79c00-0e24-11eb-9463-2c2e4e17048f.png)

## Expected Behavior

`<Button shape="round" />` should render a square button with "rounded" corners.

![image](https://user-images.githubusercontent.com/34653237/95985244-a7195980-0e24-11eb-880a-b0b49dfac30f.png)

## Your Environment

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Round is meant to be used with single icons. See [this example](https://baseweb.design/components/button#shapes) for different available shapes. There's a pill shape as well if you need horizontal buttons with rounded corners

**Comment by chimp1nski** [comment]
@chasestarr Hm ... so then "round" and "circle" are kind of redundant. As far as I can see from the docs and implementation "circle" is what you are describing while round is meant as "rounded" button. At least this is how I always implement it in my component libraries.

Thanks for your feedback and time though.
Consider reopening my PR if round is actually what I am thinking it is.

**Comment by sandgraham** [comment]
@chimp1nski - `circle` also locks in the height/width to have a 1:1 aspect ratio. This was added after `round`, which was initially only meant to be used with single icons. I'm not sure what your use case is but `pill` is good for wider content that you want to have rounded corners, and `circle` is good whenever you want a perfect circle (good for 1:1 aspect ratio content).

But if you have a new scenario that requires some other behavior please write it up here.

**Comment by chimp1nski** [comment]
@sandgraham Hi and thanks again for the reply and clarification. The scenario is fairly simple. Rounded corners (not pills just a ~0.25em radius) are widely used across various designs. Looking at the GitHub iOS App right now and it's actually all I can see 😅

I couldn't find any way so far to easily add this to baseui without custom css. That's why I thougt the rounded shape is made for that. 

If I find time on the weekend I could open another PR with an additional shape that enables rounded corners.

**Comment by sandgraham** [comment]
@chimp1nski - ah I think I see what you need. So we do have [some properties on the theme](https://github.com/uber/baseweb/blob/master/src/themes/shared/borders.js#L50) that allow you to configure border radii across the system. When you create your theme you can do something like this:
```js
import {createLightTheme} from "baseui"

const primitives = {/* your set of theme primitives */}

const theme = createLightTheme(primitives, {
  borders: {
    buttonBorderRadius: '.25em'
  }
})
```

I think that'll help. If you need even more control you might have to create an intermediary component that wraps our components and customizes the CSS further.

**Comment by chimp1nski** [comment]
Aah wow thanks for the hint. I am still wrapping my head around baseui. Really like it so far. Well I guess this solves my usecase. Thanks very much for taking your time!! Really appreciate it.
