### ISSUE TITLE
Select does not respond to clicks when it is placed as a child of Radio component

### ISSUE THREAD

**Issue by zebralight** [uber/baseweb#3827]
https://codesandbox.io/s/practical-sun-njcvr?file=/src/index.js
## Current Behavior
clicking on select does not yield a response when a child of Radio component.  A vanilla select element does respond as does the Input element as shown in the linked example.

## Expected Behavior
clicking on select should bring up options menu

## Your Environment
macos catalina

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.102.0  |
| React   |   16.14.0      |
| browser | Chrome 84.0.4147.135        |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Hi @zebralight I've personally never seen this pattern of nesting a select within a radio element. So we're probably not going to address this ourselves but feel free to submit a PR to fix
