### ISSUE TITLE
Components overwriting the device width

### ISSUE THREAD

**Issue by andersonms1** [uber/baseweb#3835]
Some components are overwriting the device with. And possible not accepting className object configurations. 

![](https://i.giphy.com/media/dhVA3hzgacTUNvMQz8/giphy.gif)

Running in smarthphones emulated by chrome dev tools.

Reproduced: https://stackblitz.com/edit/react-fyhjk8?file=src%2FApp.js

## Current Behavior

Component is trespassing device width.

## Expected Behavior

Component don`t grow bigger than device width.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | 9.102.0 |
| React   |    16.14.0     |
| browser |   Google Chrome: 86.0.4240.75 |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Hi try this https://stackblitz.com/edit/react-rqupua?file=src/example.js Learn more about overrides here: https://baseweb.design/guides/understanding-overrides/
