### ISSUE TITLE
Interactive elements inside of a StatefulTooltip do not receive focus

### ISSUE THREAD

**Issue by taksuparth** [uber/baseweb#3840]
## Current Behavior

Inside Modal, interactive elements wrapped inside StatefulTooltip is not getting focused while navigating via tab.
[Issue Demo](https://stackblitz.com/edit/react-hykhyi?file=package.json)

## Expected Behavior

Inside modal, every interactive element should get focused when navigating with tab.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.102.0  |
| React   |    v16.14.0     |
| browser |     Chrome    |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by hardikmodi1** [comment]
This is reproducible without Modal too. Here is the [link for the same](https://stackblitz.com/edit/react-hykhyi-nfy1hh?file=src/example.js). Button with tooltip is not working for the first time, we have to manually hover it to make it work with tab click

**Comment by tusharmoraye** [comment]
onBlur is getting triggered immediately after onFocus for the Button inside StatefulTooltip. Not sure where it is getting triggered.

**Comment by hardikmodi1** [comment]
react-focus-lock internally calls `document.body.focus()` if autoFocus is false. from popover component autoFocus is passed as false in first render. So body gets focused. from second render autoFocus is passed as true so it works as expected.
