### ISSUE TITLE
US Country code input is asked for every time even when it is already selected initially

### ISSUE THREAD

**Issue by alisahindev** [uber/baseweb#3846]
US Country code input is asked for every time even when it is already selected initially
https://stackblitz.com/edit/react-xtufax-jbel29?file=src/example.js

## Current Behavior
The US isoCode comes already selected when the component is created. When the user enters a phone number based on a usa isoCode, then there is no need to open the usa dropdown option again

## Expected Behavior
If the value entered with the selected value is the same, there is no need to ask again.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | 9.102.0  |
| React   |  16.13.1 |
| browser |   Chrome-Edge      |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

![image](https://user-images.githubusercontent.com/57685811/96706449-44353e80-139f-11eb-8d3c-7b13054022ad.png)

![image](https://user-images.githubusercontent.com/57685811/96706471-4c8d7980-139f-11eb-84a1-8709164badf1.png)

There is video record shows current behavior : [link](https://www.loom.com/share/ec3a225c4b62472b93190b4ae7a6714f)

**Comment by chasestarr** [comment]
The form autocomplete is a browser vender feature so not something we have much control over. I can't reproduce the behavior but my guess is that it is trying to focus the first available element. Does it behave the same on this example? https://stackblitz.com/edit/react-xtufax-emq48i?file=src/example.js

**Comment by enes-get-local** [comment]
it is not same behave. Let me explain how you can reproduce : 

1 - Open Chrome or Edge and go to address tab 
![image](https://user-images.githubusercontent.com/70728456/96880989-779ec880-1486-11eb-9a7f-93f6368561ad.png)
2 - Create new address record. Fill phone number and select country United States and save record.
![image](https://user-images.githubusercontent.com/70728456/96881187-ac128480-1486-11eb-835b-c3f6ce4ddba5.png)
3- Go to phone-input on baseui and select phone number that created just
![image](https://user-images.githubusercontent.com/70728456/96881530-0a3f6780-1487-11eb-94dd-2eb96148f6a6.png)

So US country code option trigger and open when you select number. 
![image](https://user-images.githubusercontent.com/70728456/96881701-35c25200-1487-11eb-8b00-18ee9fdc2f96.png)

 There is no need to open the US country code option again. It is already selected initially.

**Comment by sandgraham** [comment]
I was able to reproduce this - haven't had time to dig in.
