### ISSUE TITLE
Split the library into different packages

### ISSUE THREAD

**Issue by DiegoGrandeAlagon** [uber/baseweb#3849]
I'm developing a component library based on your library and I've noticed that the size of my package has increased a lot after installing BaseUI. I have thoroughly reviewed what dependencies are causing this, and have seen that the "timezone-support" package is 22MB in size.
Is there any way to remove this dependency or have you planned to split the library into different packages to choose which components are downloaded and which are not?

Thanks in advance

**Comment by chasestarr** [comment]
Bundlers should be able to tree-shake out unused dependencies. Can you confirm that you are getting this code even if you are not using the timezone selector component?

**Comment by tajo** [comment]
You don't even tree-shaking since our components live in separate subfolders. Unless you import `baseui/timezonepicker` somewhere, it should not get included in your project.

**Comment by MarcusMorba** [comment]
Thanks for the feedback. Can be closed.
