### ISSUE TITLE
Mobile touch effect on `RadioGroup` or its children is shown on the whole `RadioGroup` component

### ISSUE THREAD

**Issue by muhammadsammy** [uber/baseweb#3850]
https://baseweb.design/components/radio

## Current Behavior
Touch effect is shown for the whole the `RadioGroup` component and its children when it's touched (or any of its children)

![base_web](https://user-images.githubusercontent.com/35064832/96868837-dfe1b000-146e-11eb-8847-d3f05d35ebb0.gif)

## Expected Behavior
Mobile touch effect should only be for the component touched only.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.102.0  |
| React   |  16.13.1       |
| browser |  chrome for android and samsung web browser. didn't test firefox.       |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
It looks like you may have react-dev-tools open or some other tool. Can you reproduce with chrome dev tools closed?

**Comment by muhammadsammy** [comment]
Yes. I've found this issue on multiple real mobile devices.

![untitled](https://user-images.githubusercontent.com/35064832/96911422-1fc18b00-14a1-11eb-8ca8-6fe24978cb9b.gif)

**Comment by chasestarr** [comment]
Thank you for reporting. This is reproducible on android
