### ISSUE TITLE
Drag and Drop List (dnd-list) - does API provide a way to Add an Item programmatically ?

### ISSUE THREAD

**Issue by joe-oli** [uber/baseweb#3851]
I searched the API and all documentation, and there does not appear to be a way to Add an item after you set initialState ?

So in essence, I have to unmount the component, and remount it again, to achieve Addition. Is this the correct way of doing it ?

**Comment by chasestarr** [comment]
You'll need to use the stateless version and manage items within your own app's state https://baseweb.design/components/dnd-list/#drag-and-drop-basic-usage

**Comment by joe-oli** [comment]
Thank you, closing the issue, perhaps the documentation could be made clearer, to indicate the versions are equivalent. Somehow I was led to the stateful version, and thought that was the only way.
