### ISSUE TITLE
Documentation Enhancement // Menu Component

### ISSUE THREAD

**Issue by fadiabdelmessih** [uber/baseweb#3862]
Hi,

I hope this finds you well. First, thank you for creating a such beautiful component library. I've been playing with it for a while. However, I don't see anywhere in the documentation how to toggle on/off the menu component. Let's say that I have a button and I want to display a menu underneath the button on click. It seems that this use case is not documented or not possible. 

## Feature description

It would be nice if you could provide some examples on how to use the menus with buttons. It would be nice if there's an API similar to the following: 

```jsx
<Menu menuButton={<MenuButton>Open menu</MenuButton>} items={...items} /> 
```

If not how to achieve that.

Thank you so much.

**Comment by sandgraham** [comment]
Hi @fadiabdelmessih, you can find an example of how to combine a menu and a button here: https://baseweb.design/components/button/#as-a-dropdown.
