### ISSUE TITLE
[AppNavBar] Provide a way to independently determine currently active item

### ISSUE THREAD

**Issue by refrigeratorstory** [uber/baseweb#3863]
## Feature description
Until v9.102.0 there was a "isNavItemActive" property which would dictate which item should be considered active (a change was introduced in https://github.com/uber/baseweb/pull/3794). It allowed for overriding the "which item is currently active" logic, which was very useful for me.

Consider the following scenario where the header is given as follows: [Homepage, Content page, About us page]
- User is on Homepage and switches to Content page through the header. Content page is now active. Everything is working as expected.
- User is on Content page and clicks a link on the page (not in the header!) that takes him to X page (that isn't in the header). Now, the header should clear state and not have an active page! Instead, the last active page is used.

One could implement various work-around logic to solve this as it is. But this all would be unnecessarily tedious and convoluted. Therefore, I suggest bringing back the isNavItemActive prop which solves this in a very neat manner.

**Comment by houmark** [comment]
I second that, we were also using that function and it really complicates our code to have to work around it.

**Comment by chasestarr** [comment]
Sounds good. I can add this feature back this week
