### ISSUE TITLE
Support for Dark and Bright theme on the same page

### ISSUE THREAD

**Issue by koukalp** [uber/baseweb#3874]
Dear Baseweb team, 

Our design system uses a "split-screen design" - where the top part uses a dark theme and lower part uses a bright theme. This is possible with Baseweb, however, we hit a limitation reg. layers. This is also mentioned in your documentation - Baseweb expects to have exactly 1 BaseProvider in the root of the document. 

We achieved the split-screen design by having 2 BaseProviders - each having a different theme. However, now we can display neither modals (dialogues) nor popovers. 

I understand a "split-screen design" is opinionated and you might not want to support it. Nevertheless, how would you advise us to continue?
- Revert back to having 1 BaseProvider and extend our components to e.g. having an "inverted" mode?
- Continue with 2 BaseProviders, but how to allow displaying modals?
- Or something else?

Thank you very much for finding the time to answer my question

Bests

**Comment by sandgraham** [comment]
Howdy @koukalp - I would recommend having 1 BaseProvider (say set to LightTheme) and then a ThemeProvider nested within that which is passed the other theme.

Check out this example: https://stackblitz.com/edit/react-z833xj?file=public%2Findex.html

**Comment by koukalp** [comment]
Thank you - exactly what I was looking for. I missed the section in your docs: https://baseweb.design/guides/theming/#baseprovider
