### ISSUE TITLE
Inconsistent Tab Rendering w/ Nextjs and SSR

### ISSUE THREAD

**Issue by readywater** [uber/baseweb#3881]
I've been encountering a weird issue where tabs are rendering in inconsistently after deploying to heroku. I'm having a hell of a time figuring out why this would be happening, but i'm guessing it has something to do with the styletron engine.

The issue has never occurred in development, and only pops up when deploying to Heroku.

This issue ONLY applies to the tabs element in this component.

Visually, examples are here:
https://stage.stupidfits.com/
<img width="883" alt="Screenshot 2020-10-30 at 14 41 34" src="https://user-images.githubusercontent.com/202041/97711930-041c3d00-1abe-11eb-9d42-8161baf2400b.png">

and here:
<img width="666" alt="Screenshot 2020-10-30 at 14 42 19" src="https://user-images.githubusercontent.com/202041/97712016-1f874800-1abe-11eb-89d0-d0bea5998299.png">

## Current Behavior
Tab doesn't adopt styles from styletron.

```
// _document.js
export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);

    const stylesheets = styletron.getStylesheets() || [];
    return { ...initialProps, stylesheets };
  }

  render() {
    return (
      <Html>
        <Head>
          {this.props.stylesheets.map((sheet, i) => (
            <style
              className="_styletron_hydrate_"
              dangerouslySetInnerHTML={{ __html: sheet.css }}
              media={sheet.attrs.media}
              data-hydrate={sheet.attrs["data-hydrate"]}
              key={i}
            />
          ))}
```

```
// _app.js

const getHydrateClass = () =>
  document.getElementsByClassName("_styletron_hydrate_");

const styletron =
  typeof window === "undefined"
    ? new Server()
    : new Client({
        hydrate: getHydrateClass(),
      });

function App({ Component, pageProps, router }) {
  const [engine, setEngine] = useState(null);

  return (
    <>
      <DefaultSeo {...SEO} />
      <Provider
        options={{ site: process.env.HOST }}
        session={pageProps.session}
      >
        <StyletronProvider value={styletron} debugAfterHydration>
          <BaseProvider theme={DarkTheme}>
            <Header />
            <Transition location={router.pathname}>
              <Component
                {...pageProps}
                url={process.env.HOST}
                key={router.route}
              />
            </Transition>
          </BaseProvider>
        </StyletronProvider>
      </Provider>
    </>
  );
}

```

```
// Tabs implementation

const WithComments = (props) => {
  const [activeKey, setActiveKey] = React.useState("0");

  if (props.disable) return <>{props.children}</>;
  return (
    <Tabs
      activeKey={activeKey}
      fill={FILL.fixed}
      onChange={({ activeKey }) => {
        setActiveKey(activeKey);
      }}
      activateOnFocus
    >
      <Tab title="Anatomy">{props.children}</Tab>
      <Tab title="Comments">
        <CommentBox id={props.id} />
      </Tab>
    </Tabs>
  );

```

## Expected Behavior
Should just render as normal, styled tabs

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | "baseui": "^9.102.0", |
| React   |       16  |
| Next | "next": "^9.5.5", |
| browser |   Chrome, safari      |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by sandgraham** [comment]
Hi @readywater, do you think you can share a reproduction, either as a sandbox or a public repo?

**Comment by readywater** [comment]
> Hi @readywater, do you think you can share a reproduction, either as a sandbox or a public repo?

I can try to put together a repo tomorrow. Is this something your team has encountered before? It's confusing the hell out of me.

**Comment by sandgraham** [comment]
@readywater I haven't seen this, but the component was only released a few months ago so its possible there is an issue. My initial guess is it is in how you've got styletron configured (which isn't exactly straightforward on Next or with SSR), since we use the tabs on a couple different Next.js sites ourselves without issue. That said, if it only happens with `tabs-motion` then that sounds suspicious for different reasons. Ultimately a repro will allow us to dig in also.

**Comment by readywater** [comment]
Hey, apologies. Haven't had time to put together a reproduction repo yet, apologies. Just wanted to flag incase there's an auto close on the issue. 
To follow up on your comment @sandgraham, the main issue style wise is tabs-motion, so I'm curious about the different reason there. I have noticed though that there's also a rendering error with the file uploader which seems to have a similar manifestation — basically box height becomes zero.

One of my test users' profile pages seems to manifest there error consistently though:
https://stupidfits.com/u/coffeeandcardamom

Have noticed this in dev though:
```
react_devtools_backend.js:2273 Warning: Prop `id` did not match. Server: "tabs-271-tab-0" Client: "tabs-1-tab-0"
    in button (created by Context.Consumer)
    in DevConsumer (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in StyledTab (created by InternalTab)
    in InternalTab (created by Tabs)
    in div (created by Context.Consumer)
    in DevConsumer (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in StyledTabList (created by Tabs)
    in div (created by Context.Consumer)
    in DevConsumer (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in StyledRoot (created by Tabs)
    in Tabs (at [id].jsx:205)
    in main (at [id].jsx:164)
    in div (at [id].jsx:163)
    in div (at Layout.jsx:9)
    in div (at Layout.jsx:8)
    in Layout (at [id].jsx:108)
    in UserProfile (at _app.js:64)
    in div (at Transition.js:34)
    in Transition (at Transition.js:26)
    in div (created by TransitionGroup)
    in TransitionGroup (at Transition.js:25)
    in Transition (at _app.js:62)
    in ThemeProvider (created by BaseProvider)
    in div (created by Context.Consumer)
    in DevConsumer (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in StyledAppContainer (created by Context.Consumer)
    in LayersManager (created by BaseProvider)
    in BaseProvider (at _app.js:61)
    in DevProvider (at _app.js:60)
    in Provider (at _app.js:56)
    in App
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer
    in Root
```

**Comment by sandgraham** [comment]
@readywater - Clicking through the site (fun site btw) it seems like the tabs are rendering as expected? At least I don't see any issue in the linked-to pages.

The dev warning is annoying but haven't found a great fix yet. We need to generate a unique id for each tab for a11y purposes and in development sometimes they get mismatched and React can't reconcile. [Here is a thread if interested](https://github.com/facebook/react/issues/5867).

**Comment by readywater** [comment]
> @readywater - Clicking through the site (fun site btw) it seems like the tabs are rendering as expected? At least I don't see any issue in the linked-to pages.
> 
> The dev warning is annoying but haven't found a great fix yet. We need to generate a unique id for each tab for a11y purposes and in development sometimes they get mismatched and React can't reconcile. [Here is a thread if interested](https://github.com/facebook/react/issues/5867).

Ah, appreciate the reference and for checking the site out! Unfortunately it's still sticking around. Weirdly, one of the ways I'm able to "fix" it is by restarting the dyno on heroku, and doesn't always appear immediately but rather will appear after some time. I'm going to try and understand styltron a bit better and will follow up.

**Comment by readywater** [comment]
Okay, will there's some epic foolishness on my part.

The styletron engine was being instantiated separately in `_app` and `_document` and I hadn't noticed it in the imports.
I guess there was an occasional conflict in class naming when any given page rendered. Anyway, fixed now and appears to be working fine. 

Appreciate the support!
