### ISSUE TITLE
Missing documentation about theming

### ISSUE THREAD

**Issue by RobIsHere** [uber/baseweb#3913]
## Current Behavior

- At guides/theming the user is told to give "primitives" to "createTheme" for creating his new theme. The algorithm doing that is kept TOP SECRET. 
- The theme is working with color scales. But what component uses which scale is kept TOP SECRET. So the usual use case is: my designer told me that buttons should have color c. The user doesn't know if he should assign color c at primitive700 or 900 e.g. because he doesn't know which color scale entry components use by default. (I'm talking about theming the components in general, not about micromanaging color component by component with overrides)
- The user has to find out that you are using color scales by reading the source, or fast-forward to docs/tokens which is at the bottom, where introduction-stuff like this usually is placed if you want to keep it - you're guessing right - TOP SECRET ;)

## Expected Behavior

- guides/theming should contain a short description how the algorithm works and what primitive is assigned to which theme key - at least with some common examples like button or so
- there should be a description for common components like buttons telling the user which theme entry it's referring to
- It should be explained somewhere at theming that the ending 700 or 900 is a brightness value. 

- [ x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by sandgraham** [comment]
Top secret? The entire codebase is public and open sourced...

- There is no "algorithm" for how the primitive values are used. They are simply assigned to properties on the theme and then components use those theme properties. If you want to see what is assigned to what you can look at the source code. You can find our light theme assignments [here](https://github.com/uber/baseweb/tree/master/src/themes/light-theme) and our dark theme assignments [here](https://github.com/uber/baseweb/tree/master/src/themes/dark-theme). I think documenting these mappings would be unmaintainable and somewhat redundant.
- Check out the [interactive sandboxes at the top of each component's documentation](https://baseweb.design/components/button/). You will see a theme tab which allows you to mess around with related theme values. These aren't primitives though, which is what I think you are after.
- In terms of assigning your own colors to the various primitive scales, the number suffixes don't only correlate to brightness, but also saturation. I *thought* that was somewhat apparent from looking at the color scales but I agree a note in the guide would be useful on what the expectation is.

We have a project to add some more visual tooling around customizing the theme. That is tracked here: #3706.
