### ISSUE TITLE
Make JS calculations possible by using numeric values in theme

### ISSUE THREAD

**Issue by RobIsHere** [uber/baseweb#3919]
One of the really big advantages of CSS in JS is that it makes calculations easier.

The Problem: 
theme.sizing.scaleXXX (but also other values) are no numbers but strings with units. Therefore you can't use them as operand in javascript. You are forced to use the "calc()"-function like in dark old history.

Expected:
The theme contains the right types. Units are added automatically e.g. by styletron (Emotion automatically adds px to numbers, I don't know that much about styletrons capabilities). Ideally the preferred unit would be configurable (px or rem)

**Comment by sandgraham** [comment]
Duplicate: https://github.com/uber/baseweb/issues/512
