### ISSUE TITLE
Make typography size configurable by primitives and rem

### ISSUE THREAD

**Issue by RobIsHere** [uber/baseweb#3920]
At https://github.com/uber/baseweb/blob/master/src/themes/shared/typography.js#L17 there are used fixed px font sizes.

## Feature description
https://type-scale.com/ shows how you can adjust the font sizes by just providing a base size and a modular scale.
The base size and the modular scale should be additional primitives. All font sizes calculated based on them. 
So you can easily adjust the typography to your needs.

(ideally units should be rem instead because Px values do not scale at all when the browser font size is adjusted by peoble with eye problems)

**Comment by sandgraham** [comment]
You can set typographic values to be anything you want.
