### ISSUE TITLE
dnd list error in blitzjs

### ISSUE THREAD

**Issue by ivanthemeh** [uber/baseweb#3931]
I have installed a vanilla blitzjs app and used the base web recipe. I was testing some components and I noticed an issue with the dnd list. When I move the items I get an error.
```
Unhandled Runtime Error

TypeError: _this.ghostRef.current is null
Call Stack
List/_this.moveOtherItems
../../../node_modules/react-movable/lib/List.js (196:0)
List/_this.onMove
../../../node_modules/react-movable/lib/List.js (193:0)
List/_this.onMouseMove
../../../node_modules/react-movable/lib/List.js (176:0)
wrapperFn/frameId<
../../../node_modules/react-movable/lib/utils.js (84:0)
```

## Your Environment
macbook pro
OS Mojave

| Tech    | Version |
| ------- | ------- |
| Base UI | 9.105.0
| React   |   0.0.0-experimental-4ead6b530
| browser |  mozilla

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Hi, I'm not familiar with blitzjs. You may want to file a bug report with that project. If you can reproduce in codesandbox or create-react-app feel free to reopen
