### ISSUE TITLE
[Snackbar] Throws exception on iOS Safari <13.4

### ISSUE THREAD

**Issue by nudge** [uber/baseweb#3954]
Current Behaviour
---
Loading a page that uses Snackbar on iOS <13.4 causes an exception to be thrown.

Expected Behaviour
---
Using Snackbar should not throw exception.

Tech | Version
-- | --
Base UI | 9.104.0
React | 16.10.2
browser | iOS Safari 13.3.1, 12.4.8, 12.4.9, 13.3 , 12.4.1, 12.4.5, 13.2.3, 12.2 , 11.3, 13.1.3

Exception:

```
undefined is not a constructor (evaluating 'new window.ResizeObserver((function(e){var t=N(e,1)[0];return P(t.contentRect.height)}))')
```

Due to this line:
https://github.com/uber/baseweb/blob/7dbb240eb0c689f0ff223cbaa4da606d07d25a8f/src/snackbar/snackbar-context.js#L124

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#Browser_compatibility), `window.ResizeObserver` is only supported on IOS 13.4 and above. 

![baseweb-snackbar-ios13 3](https://user-images.githubusercontent.com/360201/100233565-363c8580-2f2a-11eb-8de8-fce602bd1ca5.gif)

**Comment by houmark** [comment]
We have reports of this error in Sentry from our production platform. This seems to also be a problem in Mac OS X 10.15.2 using Safari 13.0.4.

We are not sure what could be a workaround or fix? Were you able to work around it @nudge ?
