### ISSUE TITLE
Incorrectly rendered dates all titles

### ISSUE THREAD

**Issue by tonypee** [uber/baseweb#3957]
I have added baseweb datepicker into our app as a test, in the most basic way and the result is very unexpeced:
![image](https://user-images.githubusercontent.com/3086901/100295103-da7f0480-2fdc-11eb-9b6e-11eee5f37a8c.png)

the code is this
![image](https://user-images.githubusercontent.com/3086901/100295117-e8348a00-2fdc-11eb-9ad2-a81fe72111cf.png)

where const engine = new Styletron();

Our Environment

The app is lazy loaded into a larger app, which does use moment. I have explicitly imported moment in our sub app. Ill try matching the parent app's moment to the version used by baseweb

**Comment by chasestarr** [comment]
Hard to diagnose without more details. Can you please share a reproduction? Does this show up on every page load or just when hot-module-reloading?

**Comment by chasestarr** [comment]
Closing, but please reopen with a reproduction
