### ISSUE TITLE
File Uploader: Add option to show files preview or list of files after upload

### ISSUE THREAD

**Issue by niksmac** [uber/baseweb#3958]
## Feature description
Once the file is uploaded there is no feedback is provided form the UI. Even a list of files chosen or just replace the browser component with name of the chosen file would go good.

**Comment by tajo** [comment]
> Even a list of files chosen or just replace the browser component with name of the chosen file would go good.

You should be able to implement this with `onDrop` and setting some state?

**Comment by niksmac** [comment]
Is `onDrop` capable to identify the status of file upload?

**Comment by tajo** [comment]
No, that's up to you. This component is an empty shell, it doesn't upload or verify files.

**Comment by niksmac** [comment]
Got it, thanks.
