### ISSUE TITLE
[TableGrid] Nested Table Wraps on Expand

### ISSUE THREAD

**Issue by colinnielsen** [uber/baseweb#3959]
https://codesandbox.io/s/base-web-table-issue-qzcux?file=/src/example.js

## Current Behavior

I am having an issue with header rows wrapping on expand with table-grid.
This is a very similar spin-off to https://baseweb.design/components/table-grid/#nested-table
![image](https://user-images.githubusercontent.com/33375223/100554249-ae6bb980-3250-11eb-8211-e62f51c90689.png)

## Expected Behavior

I expect the table rows and headers to stay aligned once I expand the row.

## Your Environment

CodeSandbox

| Tech    | Version |
| ------- | ------- |
| Base UI | latest (9.105.0) |
| React   |  latest (17.0.1) |
| browser |   Chrome Version 87.0.4280.66 (Official Build) (64-bit)   |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by colinnielsen** [comment]
@gergelyke

**Comment by chasestarr** [comment]
Hi, this can be fixed by changing to `span 6` on L56 https://codesandbox.io/s/base-web-table-issue-forked-ffgvl?file=/src/example.js
