### ISSUE TITLE
Table sort icon is reversed

### ISSUE THREAD

**Issue by andriuss** [uber/baseweb#3962]
BaseWeb table sort icons look reversed compared to other systems I am familiar with.

### BaseWeb tables

**Semantic table** - https://baseweb.design/components/table-semantic/#table-builder-with-sorting
<img width="610" alt="Screenshot 2020-12-03 at 16 46 51" src="https://user-images.githubusercontent.com/6738026/101043965-87cabd00-3587-11eb-8ce2-1daa6c21fa31.png">

**Data table** - https://baseweb.design/components/data-table/
<img width="617" alt="Screenshot 2020-12-03 at 16 47 54" src="https://user-images.githubusercontent.com/6738026/101043976-8b5e4400-3587-11eb-9ebf-a74e21d9dedb.png">

**Grid table** - https://baseweb.design/components/data-table/
<img width="614" alt="Screenshot 2020-12-03 at 16 48 22" src="https://user-images.githubusercontent.com/6738026/101043987-8ef1cb00-3587-11eb-8340-6854bac682ff.png">

**Flex table** - https://baseweb.design/components/table/#table-with-sorting-by-a-column
<img width="432" alt="Screenshot 2020-12-03 at 16 48 43" src="https://user-images.githubusercontent.com/6738026/101044026-9a44f680-3587-11eb-8a54-b28ece9dab6f.png">

### Other systems
**macOS**
<img width="1003" alt="Screenshot 2020-12-03 at 16 52 58" src="https://user-images.githubusercontent.com/6738026/101044445-00ca1480-3588-11eb-95c6-1198f4194146.png">

**MaterialUI**
<img width="861" alt="Screenshot 2020-12-03 at 16 21 59" src="https://user-images.githubusercontent.com/6738026/101044479-0c1d4000-3588-11eb-9b9e-23c686ca9aa2.png">

**Google Drive**
<img width="1350" alt="Screenshot 2020-12-03 at 16 59 43" src="https://user-images.githubusercontent.com/6738026/101045469-fa886800-3588-11eb-844b-6e765480790b.png">

**Windows**
![2018-07-28T11 03 36 File Explorer - Details view of test files without showing tags -- publicvoit screenshots - scaled width 630](https://user-images.githubusercontent.com/6738026/101045082-b1381880-3588-11eb-91e5-83e75211d67d.png)

Should BaseWeb sort icon be reversed? Changed to the arrow?

**Comment by chasestarr** [comment]
I'm fine with switching it everywhere, but it tends to be ambiguous either way. Does the arrow indicate the direction towards larger values, or does it indicate whether the starting point is large/small? [Ubuntu](https://hackernoon.com/hn-images/1*_5DcgvmCi08au_t23fy5ig.png) for example follows the same rules as current base web tables. Aligning with windows and mac feels like a good compromise and a good reference to avoid further bikeshedding.

**Comment by andriuss** [comment]
As it's ambiguous either way it should not be a problem to switch (reverse) it.
I would vote for mac+windows+android+ios version for the icons as it covers ~97% of OS market share.

**Comment by andriuss** [comment]
Implemented in #4043
