### ISSUE TITLE
Consider Spinner Determinate to be a progress element

### ISSUE THREAD

**Issue by Deliaz** [uber/baseweb#3963]
There is an element [Spinner Determinate](https://baseweb.design/components/spinner/#spinner-determinate) and it lives under the **Spinner** section.
But from the semantic point, doesn't it act as a progress bar? What do you think about moving this component to the **Progress bar** page, as an "Oval (Circle) Progress", for example?

**Comment by tajo** [comment]
I had the same question but don't remember the reason? @chasestarr?

**Comment by chasestarr** [comment]
I think this is just a result of how our design team organized it in the specifications. I'm fine with aliasing it within the progress export or copying the example to the docs page
