### ISSUE TITLE
tabs-motion component's leading icon does not receive color and size props

### ISSUE THREAD

**Issue by manofporkbelly** [uber/baseweb#3966]
It does not seem possible to change the color or size of the leading Icon of the `tabs-motion` `Tab` component.

The documentation says to provide a `color` or `size` prop, but the Leading Icon does not respond. It does not seem possible to override just the Icon component either without overriding the entire `ArtworkContainer` component.

- Go to this sandbox: https://codesandbox.io/s/iru6h?module=src/example.js&file=/src/example.js:0-630
- Use this code, note the `color` prop on the `<Tab ... />` component, I've tried multiple different values like using `$theme.colors.negative` or trying to override the styles of the `ArtworkContainer`:
```
import * as React from 'react';
import {Tabs, Tab} from 'baseui/tabs-motion';
import {Check} from 'baseui/icon';

export default () => {
  const [activeKey, setActiveKey] = React.useState(0);
  return (
    <Tabs
      activeKey={activeKey}
      onChange={({activeKey}) => setActiveKey(activeKey)}
    >
      <Tab title="First" artwork={Check} color="negative">
        I must not fear.
      </Tab>
      <Tab title="Second" artwork={Check}>
        Fear is the mind-killer.
      </Tab>
      <Tab title="Third" artwork={Check}>
        Fear is the little-death that brings total obliteration.
      </Tab>
    </Tabs>
  );
};
```

## Current Behavior

The color and size of the Leading Icon do not change even when given props, different from what is written in the documentation. The only way to do it is overriding the entire component.

## Expected Behavior

The color of the Leading Icon of the `tabs-motion` `Tab` component should be able to respond to Baseweb's color variables.

## Your Environment

| Tech    | Version |
| ------- | ------- |
baseui | latest (9.106.0)
react | latest (17.0.1)
react-dom | latest (17.0.1)
react-scripts | latest (4.0.1)
styletron-engine-atomic | ^1.4.3 (1.4.6)
styletron-react | ^5.2.4 (5.2.7)
| browser |    Chrome Version 87.0.4280.88 (Official Build) (x86_64)     |

https://codesandbox.io/s/iru6h?module=src/example.js&file=/src/example.js:0-630

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Hi, the docs are referring to props passed to the component provided to the `artwork` prop. See this example for more detail https://codesandbox.io/s/base-web-leading-icon-forked-q3lyb?file=/src/example.js
