### ISSUE TITLE
`withWrapper` is exported but not defined with type

### ISSUE THREAD

**Issue by KendraTang** [uber/baseweb#3975]
As reproduced here:
https://codesandbox.io/s/upbeat-bas-obb1m?file=/src/App.tsx

## Current Behavior

This would actually work:
```js
import { withWrapper } from 'baseui';
```

But would have error with type checking:
```
Module '"../node_modules/baseui"' has no exported member 'withWrapper'.ts(2305)
```

## Expected Behavior

Do not show the error

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.106.1  |
| React   |  17.0.0   |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by rushilp2311** [comment]
Can I try working on this?
