### ISSUE TITLE
Is it possible to provide more icons?

### ISSUE THREAD

**Issue by bytrix** [uber/baseweb#3978]
## Feature description
There is only 28 icons that baseui provide, this is too few for me.

**Comment by houmark** [comment]
Consider using [React Icons](http://react-icons.netlify.com/) — tree shakes if used correctly and by that only increase your package size relative to the amount of icons you use from the many options.

And it works smoothly with BaseWeb.

**Comment by bytrix** [comment]
> Consider using [React Icons](http://react-icons.netlify.com/) — tree shakes if used correctly and by that only increase your package size relative to the amount of icons you use from the many options.
> 
> And it works smoothly with BaseWeb.

This is awesome, great thanks!
