### ISSUE TITLE
TypeScript Interface for TabOverrides['Tab'] in tabs-motion is missing $isActive

### ISSUE THREAD

**Issue by dheeraj-jn** [uber/baseweb#3989]
## Current Behavior

TypeScript Interface for [`TabOverrides['Tab']`](https://github.com/uber/baseweb/blob/master/src/tabs-motion/index.d.ts#L79) in tabs-motion is missing `$isActive`

### Sandbox

Notice the red line under `$isActive`:
https://codesandbox.io/s/compassionate-montalcini-edyvc?file=/src/App.tsx

## Expected Behavior

`TabOverrides` should look like this:

```typescript
interface TabOverrides {
  Tab?: Override<{
    $fill?: FILL;
    $orientation?: ORIENTATION;
    $focusVisible?: boolean;
    $isActive?: boolean
  }>;
...
```

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.106.2  |
| TypeScript   | v4.1.2  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by irvv17** [comment]
Did you solve this?

**Comment by irvv17** [comment]
Hi maybe this is not the best practice but its a tricky, and, TS it's Ok with this.

`const SidebarWrapper = themedStyled('nav', (props) => {
  return {
    display: props['$isOpen'] ? 'block' : 'none',
    // paddingTop: $theme.sizing.scale700,
    marginLeft: props['$theme'].sizing.scale800,
    marginRight: props['$theme'].sizing.scale800,
    [props['$theme'].mediaQuery.medium]: {
      display: props['$hideSideNavigation'] ? 'none' : 'block',
      maxWidth: '16em',
    },
  };
});`
