### ISSUE TITLE
[Bug] Dropdown's Select not aligned when Select component is used inside a Drawer

### ISSUE THREAD

**Issue by ELOUFIR** [uber/baseweb#4001]
## Current Behavior

Hi all, when I include Select inside a Drawer, i noticed that the Dropdown menu not aligned :

![Capture d’écran 2020-12-22 163704](https://user-images.githubusercontent.com/24244627/102905792-f2c72f80-4473-11eb-986c-595b78fbed12.png)

Reproducible example : [https://codesandbox.io/s/base-web-drawer-with-different-size-forked-x7k2d?file=/src/example.js](https://codesandbox.io/s/base-web-drawer-with-different-size-forked-x7k2d?file=/src/example.js)

## Expected Behavior

Normally it should be aligned.

## Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.106.3  |
| React   | v17.0.1        |
| browser |  Chrome v87.0.4280.88       |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by houmark** [comment]
I've seen this happening also, but the dropdown seems to slide off to the right by around the same amount of pixels in our `Drawer`.
