### ISSUE TITLE
Documentation for theme objects should clarify the object structure for certain properties

### ISSUE THREAD

**Issue by ajbogh** [uber/baseweb#4002]
## Current Behavior

Documentation for border200 (or other border properties) and radius200 doesn't differentiate whether the properties are objects or primitives.

```
theme.borders.border200
solid
1px
hsla(0, 0%, 0%, 0.08)
```

```
theme.borders.radius200
4px
```

## Expected Behavior

The documentation should explain the structure of the properties better.

```
theme.borders.border200
{ 
  borderColor: "hsla(0, 0%, 0%, 0.08)"
  borderStyle: "solid"
  borderWidth: "1px"
}
```

```
theme.borders.radius200
4px
```

## Your Environment

https://baseweb.design/guides/theming/#borders

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by ajbogh** [comment]
@tajo Please take a look at my comments in that diff. I believe there's an easier way to represent those objects.

**Comment by tajo** [comment]
Ah yea, that would simpler. But it's merged and we are not going to ever change these sub-properties so it doesn't really matter.

**Comment by ajbogh** [comment]
Do you have other components that have other object-based properties? While the issue related to the borders, it could certainly apply to all object-based properties.

**Comment by tajo** [comment]
Yea, I also updated it for fonts and some grid props.
