### ISSUE TITLE
[Datepicker] improve format string documentation

### ISSUE THREAD

**Issue by ajbogh** [uber/baseweb#4008]
Using appropriate letters from the date-fns documentation, it doesn't seem like the formatString functionality works.

## Current Behavior

With formatString set to 'EEEE, MMMM dd yyyy', documented in [the date-fns website](https://date-fns.org/docs/format), the text in the input box shows **"  31, 2020        "**

https://codesandbox.io/s/kgwib?module=src/example.js&file=/src/example.js

## Expected Behavior

The text input should show something like "Thursday, December 31 2020".

## Your Environment

https://codesandbox.io/s/kgwib?module=src/example.js&file=/src/example.js:355-373

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Something like this should bypass the masking feature https://codesandbox.io/s/base-web-datepicker-with-no-mask-forked-boz2c Please reopen if this did not resolve the issue

**Comment by ajbogh** [comment]
@chasestarr Could you please update the documentation to note that the mask feature should be null if the formatString is used if this is intentional functionality? 

Otherwise your suggestion of bypassing the mask would be a good fix in code. The user shouldn't be required to create hacks around the bug.

**Comment by chasestarr** [comment]
There this example: https://baseweb.design/components/datepicker#datepicker-with-no-mask How do you think it should be updated?

**Comment by ajbogh** [comment]
It seems like formatString is dependent on a custom mask being defined, or a null mask. For instance, the Datepicker with Custom Mask option includes a mask that matches the formatString. That seems silly to duplicate what the formatString already provided, but I understand it as a method of disabling the default mask string.

In the code you can detect that a custom formatString is provided and disable the default mask property, or disable the mask property altogether. There's no reason that I know of to include a mask if you've already included a formatString, because formatString is a more customizable mask itself.

Another option is to detect that a formatString is provided and require a custom mask property by issuing an error if one's not defined. Since the current code requires that they match, make them dependent on eachother when formatString is defined.

Another option is to simply document that formatString is dependent on the mask property being defined or null, not missing. This is a requirement that is not spelled out. It's implied by the examples, but the examples don't explain that the mask is necessary for the formatString property to work.

**Comment by chasestarr** [comment]
Thanks for the description. Reopened and clarified the title
