### ISSUE TITLE
Change indeterminate checkbox onClick behavior

### ISSUE THREAD

**Issue by AlexeyKriveniaUber** [uber/baseweb#4009]
As implemented here https://baseweb.design/components/checkbox#indeterminate-state we have the following behavior:

- the user sees parent checkbox with a `[-]` sign when some of child checkboxes are checked, but not all;
- when the user clicks on this checkbox - all child checkboxes are selected.

But `[-]` sign looks like reducing (not extending) the amount of selected options for a user.

An example is the list of emails in the Gmail Web UI.

As discussed with @chasestarr we can change standard behavior to make it the same as at Gmail Web UI.

Could you please change behavior at the examples below?
- https://baseweb.design/components/checkbox#indeterminate-state
- https://baseweb.design/components/table-semantic/#table-builder-with-toggles

**Comment by chasestarr** [comment]
Thank you for bringing up this issue. This follows default browser behavior so we won't update it on the documentation site. Please note that this is not hard-coded within baseui, so feel free to change it if the application requires

**Comment by AlexeyKriveniaUber** [comment]
As discussed we should leave functionality as is.
