### ISSUE TITLE
Add React 17 support

### ISSUE THREAD

**Issue by simPod** [uber/baseweb#4024]
## Feature description

Is there something blocking React 17 support or is it just a formality and we need to allow it in package.json?

Thanks!

**Comment by houmark** [comment]
We've been running React 17 in production for at least a month without Baseweb issues. There were a few minor issues, to begin with, but those have been corrected. I'm not aware of any React 17 specific bugs.

**Comment by chasestarr** [comment]
We're still on v16 at Uber so that's why it's not updated to latest. We run our unit and integration tests on both react 16 and 17 so it should be covered, but please open any issues if found

**Comment by skotsj** [comment]
```
"peerDependencies": {
    "react": ">= 16.8.0 < 17",

```

Build won't let me due to the above requirement, am I missing something?

**Comment by iansan5653** [comment]
Agree with @skotsj  - if it's tested and compatible with React 17, why not remove that limit?
