### ISSUE TITLE
Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by enes-get-local** [uber/baseweb#4026]
I need to override Tab button element with my custom button. I tried to use generally syntax here but it doesn't work.

[Here is my example
](https://codesandbox.io/s/base-web-tabs-forked-58htd?file=/src/example.js)

```
import * as React from "react";
import { Tabs, Tab } from "baseui/tabs-motion";

export default () => {
  const [activeKey, setActiveKey] = React.useState("0");
  return (
    <Tabs
      activeKey={activeKey}
      onChange={({ activeKey }) => {
        setActiveKey(activeKey);
      }}
      activateOnFocus
    >
      <Tab
        overrides={{
          Tab: {
            component: () => <button>Custom button</button>
          }
        }}
        title="Custom"
      >
        Content
      </Tab>

      <Tab title="Second">Content 2</Tab>
      <Tab title="Third">Content 3</Tab>
    </Tabs>
  );
};
```

It raise error : 

`Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.
`

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | 9.105.0  |
| React   |   16.13.1      |
| browser |    Chrome     |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Hi here's a fix. We need to forward the ref through to the overridded component. https://codesandbox.io/s/base-web-tabs-forked-fsel1?file=/src/example.js Please re-open if it doesn't work for you
