### ISSUE TITLE
[Drawer] showBackdrop prop has no effect

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#4030]
If `showBackdrop = false`, I expect the backdrop to not 'darken' the rest of the application. It looks to me that this prop never worked in the first place. Something like https://codesandbox.io/s/base-web-drawer-forked-vy3or?file=/src/example.js:229-230 works for now. A fix for this should essentially perform the same action that this override is doing but based on the `showBackdrop` prop

**Comment by mooreInteractive** [comment]
I'm going to see if I can apply a fix for this.

**Comment by chasestarr** [comment]
Thanks for fixing!
