### ISSUE TITLE
Combobox enhancers doesn't work

### ISSUE THREAD

**Issue by enes-get-local** [uber/baseweb#4034]
i m trying to override startEnhancer and EndEnhancer icons but nothing works.

[Live Demo](https://codesandbox.io/s/base-web-combobox-forked-kdvf2?file=/src/example.js)

```
 <Combobox
      value={value}
      onChange={(nextValue) => setValue(nextValue)}
      options={[
        { label: "AliceBlue", id: "#F0F8FF" },
        { label: "AntiqueWhite", id: "#FAEBD7" },
        { label: "Aqua", id: "#00FFFF" },
        { label: "Aquamarine", id: "#7FFFD4" },
        { label: "Azure", id: "#F0FFFF" },
        { label: "Beige", id: "#F5F5DC" }
      ]}
      mapOptionToString={(option) => option.label}
      overrides={{
        Input: {
          props: {
            overrides: {
              EndEnhancer: () => <span>$</span>,
              StartEnhancer: {
                component: () => <span>$</span>
              }
            }
          }
        }
      }}
    />
```

| Tech    | Version |
| ------- | ------- |
| Base UI | 9.105.0  |
| React   |   16.13.1      |
| browser |  Chrome       |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Hi give this a try. https://codesandbox.io/s/base-web-combobox-forked-8715j?file=/src/example.js Also, check out the "style overrides" explorer at the top of most component documentation pages here https://baseweb.design/components/combobox

**Comment by enes-get-local** [comment]
> Hi give this a try. https://codesandbox.io/s/base-web-combobox-forked-8715j?file=/src/example.js Also, check out the "style overrides" explorer at the top of most component documentation pages here https://baseweb.design/components/combobox

Thanks for response. i m checking style overrides but there is showing style overrides only. I can't still find a way mask toggle icons, clear icon... with my custom elements

**Comment by chasestarr** [comment]
Can you please share an example of what's not working?

**Comment by enes-get-local** [comment]
> Can you please share an example of what's not working?

I guess everything is works but  [https://baseweb.design/components/combobox](https://baseweb.design/components/combobox) this page is not telling us clearly what we have to do.

For example , in this demo, i activated clearable but i couldn't override clearIcon with my custom icon.
Or i can't find a way to change MaskToggleButton component. 

[Pls could you demonstrate in there 
](https://codesandbox.io/s/base-web-combobox-forked-ip7w5?file=/src/example.js)

**Comment by chasestarr** [comment]
Here is your example edited with clear icon overrides https://codesandbox.io/s/base-web-combobox-forked-m3qth?file=/src/example.js for more information on overrides, see here https://baseweb.design/guides/understanding-overrides/
