### ISSUE TITLE
Overrides Props as a function" warning does not provide guidance on what to do.

### ISSUE THREAD

**Issue by enjoylife** [uber/baseweb#4035]
Ran into the warning which informs that a function passed into the override props is about to be removed in the next version.

For the specific context, I was needing access to the onChange event occurring within the datepickers inner quick select components, e.g. knowing when a quick selection actually used.
https://codesandbox.io/s/base-web-datepicker-override-quickselect-onchange-w9tnv?file=/src/example.js
## Current Behavior
Warning is emitted `baseui:Overrides Props as a function will be removed in the next major version. ` But doesn't say what one can do to fix it.

## Expected Behavior
The warning provides guidance on alternative approaches.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.107  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Hi, thank you for creating a pull request to address this. The problem with this feature has lead to lots of problems with over-rendering components. I'd like to refrain from recommending this and there's no plans to support a version of it in the future. Apologies for closing

**Comment by enjoylife** [comment]
I'm not recommending to use the functional props, I'm saying the warning doesn't give guidance on what to do instead. If we are going to deprecate the behavior, we need to suggest alternative ways of accomplishing the same result.
And in general, error/warning messing should show what you can do to fix it. See https://medium.com/@rkuris/good-apis-cd861b8b70a3
