### ISSUE TITLE
Calendar format problem (DatePicker, StatefulDatePicker, Calendar)

### ISSUE THREAD

**Issue by Holzmichel41** [uber/baseweb#4046]
## Current Behavior

When integrating a component with reference to the calendar component (e.g. one of the components mentioned in the title) the corresponding calendar component shows only numbers and random letters. Moreover there is a bug with the input field by only showing the month but no year and day:

```
const Example = () => {

  const [date, setDate] = React.useState<Date|null>(new Date());
  
  return (
  <FormControl label="Date" caption="YYYY/MM/DD">
      <DatePicker
          value={date}
          onChange={({date}) => setDate(date as Date)}
      />
  </FormControl>
  );
}
```
![image](https://user-images.githubusercontent.com/47560723/106486569-12f5ff80-64b2-11eb-85a3-bdc2ab459190.png)

## Expected Behavior

The calendar component pops up as expected showing month and day descriptions correctly. The input field is showing the whole date.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | ^9.109.0  |
| React   | ^17.0.1 |
| browser |     Chrome, Safari    |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Can you please reproduce the error? Use this as a starting point https://codesandbox.io/s/vireh?module=src/example.js&file=/src/example.js:0-32

**Comment by Holzmichel41** [comment]
Unfortunately I am not able to reproduce the error. Inside the sandbox everything is working as expected, I can try whatever I want - no error. That's why I am so confused about it. And all other components from baseui package are working fine!
I tried the following steps within my application:

- Reinstalling the baseui package
- Using the standard baseui themes without adjustments
- Integrating the calendar component (copy pasted from the docs, without any changes) anywhere else inside the application and try it out

The error unfortunately remains.
Is there any idea what maybe could cause the problem or other steps I can try? Then I would focus on that.

**Comment by chasestarr** [comment]
I'm not quite sure why this is occurring. Can you reproduce with a minimal github repo?

**Comment by Holzmichel41** [comment]
I think I fixed the problem:

When starting the app at another workstation, the following error appeared immediately:
```Module not found: Can't resolve 'date-fns/_lib/format/longFormatters' from ./node_modules/@date-io/date-fns/build/index.esm.js```

So the solution was to manually install the ```date-fns``` package with ```npm install date-fns```. 
After restarting the app, everything was working as expected, also on my previous pc.
