### ISSUE TITLE
Pass id or name attribute to Tag component

### ISSUE THREAD

**Issue by zhenming91** [uber/baseweb#4048]
## Feature description

Maybe I am missing something, but I would like to access the clicked tags using an id attribute on the element. So that I can close the tags that are clicked. However, when passing `id` or `name` as props to `Tag`, it is not being recognised.

**Comment by chasestarr** [comment]
Hi, you'll need to use overrides as described here: https://baseweb.design/guides/understanding-overrides Here's an example https://codesandbox.io/s/base-web-tag-forked-33s3z?file=/src/example.js Feel free to reopen if this doesn't work
