### ISSUE TITLE
Style override not working for newer versions of TextArea component

### ISSUE THREAD

**Issue by milemilo** [uber/baseweb#4049]
I'm running into an issue overriding the Textarea component border color.

The sandbox provided in the baseweb docs for Textarea shows that using the **outline** style override does not actually update the outline color.  I also tried changing the Input's **borderColor** and that does not seem to work either.

https://codesandbox.io/s/base-web-textarea-forked-cktic?file=/src/example.js

For versions <= 9.104.0, seems to apply the style as expected.
For versions >= 9.1.05.0, **borderColor** / **outline** style overrides don't work.

```
<Textarea
      value={value}
      onChange={(e) => setValue(e.target.value)}
      placeholder="Controlled Input"
      clearOnEscape
      overrides={{
        InputContainer: {
          style: ({ $theme }) => ({
            outline: "red",
            backgroundColor: "lightGrey"
          })
        }
      }}
    />
```

![borderColor](https://user-images.githubusercontent.com/3640522/106531348-ab40b400-64b3-11eb-80b1-aa820c7d75d0.gif)

## Current Behavior

Overriding the Input **borderColor** does not actually change the Textarea border color.

## Expected Behavior

When overriding the Input border color, style should be applied.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | <= v9.104.0 👍  |  >= v9.105.0 👎  |
| React   |  latest  |
| browser |    Chrome Version 88.0.4324.96 (Official Build) (x86_64)     |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Apologies for the trouble @milemilo The behavior you depended on was actually a regression from earlier builds. See https://github.com/uber/baseweb/pull/3900. 9.105 release restored the behavior to previous. Here is an example of how to update your code https://codesandbox.io/s/base-web-textarea-forked-gq0rj?file=/src/example.js

**Comment by milemilo** [comment]
No worries, thank you for the quick response @chasestarr! Very much appreciated
