### ISSUE TITLE
[slider] Option to always show current value (like in versions prior to 9)

### ISSUE THREAD

**Issue by tvst** [uber/baseweb#4074]
### Background

The slider in BaseWeb up to version 9 used to look [like this](https://v8-18-0.baseweb.design/components/slider/):

<img width="594" alt="Screen Shot 2021-02-13 at 12 11 11 PM" src="https://user-images.githubusercontent.com/690814/107860574-c20cd200-6df4-11eb-85ee-582ad7fe0495.png">

Notice how the currently-selected value (60.0) is visible at all times. 

[Since version 9](https://baseweb.design/components/slider/), the slider thumb no longer shows the currently-selected value, unless you hover:
<img width="607" alt="Screen Shot 2021-02-13 at 12 13 19 PM" src="https://user-images.githubusercontent.com/690814/107860594-e8327200-6df4-11eb-8a9b-92a347f80338.png">

### Feature request

Add an option to always show the selected value. For example:

```
<Slider
      ...
      showThumbValue={true}
    />
```

or maybe something like:

```
    <Slider
      ...
      overrides={{
        ThumbValue: () => ({
           alwaysVisible: true,
        }),
      }}
    />
```

**Comment by ericsoco** [comment]
Comment from @williamernest: visually it seems a bit much to keep the `ThumbLabel` always visible:
![image (14)](https://user-images.githubusercontent.com/1127259/125842398-5178f3ba-5c98-4c0e-b074-a4ca24326a3d.png)

Agree, but this is not the case with more minimal label styling like in the [overrides example for "Custom ticks"](https://baseweb.design/components/slider/#custom-ticks).

```
  InnerThumb: () => null,
  ThumbValue: ({$value}) => (
    <div
      className={css({
        position: 'absolute',
        top: `-${theme.sizing.scale800}`,
        ...theme.typography.font200,
        backgroundColor: 'transparent',
      })}
    >
      {$value}m
    </div>
  ),
```

There are real use cases for always displaying the thumb value, i.e. being able to easily read the current value without interacting with the slider.

Also, wrt to being "visually a bit much"...at the risk of getting into a design flame war, the new styling on the label is already visually a bit much IMO ;)

Currently, [Slider is implemented](https://github.com/uber/baseweb/blob/master/src/slider/slider.js) in a way that makes it impossible to always display the value:
```
 const displayLabel =
  ((index && isHovered1) || (!index && isHovered0) || isDragged) &&
  !disabled;
return (
  <Thumb
    {...props}
    onMouseEnter={() => {
      if (index === 0) {
        setIsHovered0(true);
      } else {
        setIsHovered1(true);
      }
    }}
    onMouseLeave={() => {
      if (index === 0) {
        setIsHovered0(false);
      } else {
        setIsHovered1(false);
      }
    }}
```

I'd be open to cutting a PR if you have a suggested implementation.
