### ISSUE TITLE
Typing *, [, ( in search bar causes white space

### ISSUE THREAD

**Issue by apandora** [uber/baseweb#4080]
## Current Behavior
<img width="529" alt="Screen Shot 2021-02-19 at 3 15 17 PM" src="https://user-images.githubusercontent.com/67047780/108480502-048d4d80-72d2-11eb-9e70-93f408ac7d65.png">
<img width="528" alt="Screen Shot 2021-02-19 at 3 15 41 PM" src="https://user-images.githubusercontent.com/67047780/108480507-06571100-72d2-11eb-9b4a-4686146eb117.png">
<img width="569" alt="Screen Shot 2021-02-19 at 3 16 10 PM" src="https://user-images.githubusercontent.com/67047780/108480515-0820d480-72d2-11eb-8d77-028e6f853c6b.png">
<img width="551" alt="Screen Shot 2021-02-19 at 3 16 31 PM" src="https://user-images.githubusercontent.com/67047780/108480522-09ea9800-72d2-11eb-8924-37a1b346a21b.png">

 When you input the selected characters, it causes white page error

## Expected Behavior

 It should proceed without white space error

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.95.2  |
| React   |         |
| browser |   chrome, safari      |

- [X] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Hi, this has been fixed since v9.95.2. To test visit https://baseweb.design/components/data-table
