### ISSUE TITLE
Function components cannot be given refs error thrown when using `Blank` icon in User Items of AppNavBar

### ISSUE THREAD

**Issue by mattpodolak** [uber/baseweb#4082]
https://codesandbox.io/s/red-cdn-4hetq?file=/src/index.js

## Current Behavior

Throws the following error when you click the User Menu when a user menu item has the icon set to Blank :
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Context.Consumer`.
    at ListItem
    at MaybeChildMenu
```

## Expected Behavior

No error when you click the drop down

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.110.0  |
| React   |    17.0.1     |
| browser |   Chrome      |

- [x ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by advanderveer** [comment]
I'm running into the same issue but with any icon. @mattpodolak note that the warning wil disappear when the javascript is being build with ENV set to production.

**Comment by nikitastryuk** [comment]
Having the same issue

**Comment by xxtereshko** [comment]
Same issue

**Comment by docoder** [comment]
Same issue

**Comment by treyshedrick** [comment]
I am seeing this same log error any time I open the User Items.

**Comment by alexgorbatchev** [comment]
cc @williamernest
