### ISSUE TITLE
Case-sensitivity prop for creatable multi Select

### ISSUE THREAD

**Issue by ksnyder9801** [uber/baseweb#4097]
## Feature description

Select currently uses a [case-insensitive comparison against the current options and value](https://github.com/uber/baseweb/blob/v9.110.0/src/select/select-component.js#L867) to allow creating a new value. This makes it impossible to create both "abc" and "ABC" values.
Propose adding a `ignoreCase` (default true) prop to Select to toggle the .toLowerCase() behavior.

Even though default filterOptions also does a case-insensitive search, I don't think that needs to change based on this prop because there's already a prop to override the whole function.

**Comment by chasestarr** [comment]
This sounds good to me. Although the `filterOptions` could be replaced with a case-sensitive fn, this seems like it would be the most common alternative to the default.
