### ISSUE TITLE
overriding Tab panel 

### ISSUE THREAD

**Issue by wael-mohamed** [uber/baseweb#4102]
Tab panel on tabs (motion) has padding 16px by default which is difficult to edit

## Feature description
Can you please make the tab panel overridabale or remove the default padding

**Comment by RobIsHere** [comment]
See https://baseweb.design/components/tabs-motion/#tab-overrides

```
      <Tab
        overrides={{
          TabPanel: {
            style: {
              'padding': 0
          }},
        }}
        title="First"
      >
        Content 1
      </Tab>

```

**Comment by wael-mohamed** [comment]
Thanks for answering
I'm using this tab in different use case
I think if TabPanel were independent of Tab would be better
