### ISSUE TITLE
"disabled" prop on <Tab> missing in typescript definition

### ISSUE THREAD

**Issue by RobIsHere** [uber/baseweb#4104]
To disable a single tab page you have to override it. Because most of the components can be disabled by prop, this has been somewhat surprising.
```
          <Tab
            title="Message"
            overrides={{
              Tab: {
                props: { disabled: false },
              },
            }}>...</Tab>
```

## Feature description
Passing a disabled prop from <Tab /> to the underlying <button /> would solve this in a 2-liner, so you can conveniently

```
          <Tab
            disabled
            title="Message"
            >...</Tab>
```

**Comment by chasestarr** [comment]
I believe this is already supported here https://codesandbox.io/s/base-web-tabs-forked-3b9nb but please edit that sandbox to reproduce your issue

**Comment by RobIsHere** [comment]
You're right. Wrong diagnosis, sorry for the confusion. Only the typescript definition for disabled on Tab is missing, so I maybe thought it would be missing at all.

vscode complains:
```
Type '{ children: Element; title: string; disabled: boolean; }' is not assignable to type 'IntrinsicAttributes & TabProps & { children?: ReactNode; }'.
  Property 'disabled' does not exist on type 'IntrinsicAttributes & TabProps & { children?: ReactNode; }'.ts(2322)
```

and at https://github.com/uber/baseweb/blob/master/src/tabs-motion/index.d.ts#L93
the disabled?:boolean is missing

**Comment by chasestarr** [comment]
Good point. We don't use typescript at Uber so it sometimes lags behind the flow definitions. Are you interested in updating the TS definition?
