### ISSUE TITLE
Drag and Drop List: Adding horizontal orientation

### ISSUE THREAD

**Issue by Holzmichel41** [uber/baseweb#4105]
## Feature description
Is it possible to change the orientation of the drag and drop list from vertical to horizontal? I found a way to display the list in horizontal orientation by adding `overrides={{
      List: {
          style: {
              display: 'flex'
          }
      }
}}` to the `<List />` component.

But the drag and drop functionality works still in vertical orientation. 
Can I change this as well? If this is not possible, it would be a nice feature.

**Comment by tajo** [comment]
Hey, the underlying library https://github.com/tajo/react-movable doesn't support horizontal DnD lists (design decision to keep it simple) so we are not going to support it. You could try https://github.com/atlassian/react-beautiful-dnd instead.
