### ISSUE TITLE
Popover is not repositioning on anchor element change

### ISSUE THREAD

**Issue by hhvys** [uber/baseweb#4112]
## Current Behavior
Popover does not reposition when anchor element's height/width changes.  Here, dropdown does not change position as select's size increases. https://codesandbox.io/s/base-web-select-forked-yz5cc?file=/src/example.js

## Expected Behavior
It should reposition when anchor element's height/width changes. Currently, popover repositions itself when popper's height/width changes. Should do the same for anchor element as well.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.110.0  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by hetpatel33** [comment]
@chasestarr @gergelyke 
Facing the same issue, can we please fix this.
