### ISSUE TITLE
[Input] Disabled input text has low contrast in safari

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#4127]
Disabled Input component text is incorrect in Safari. Looks fine in other browsers.

<img width="1146" alt="Screen Shot 2021-03-16 at 4 29 42 PM" src="https://user-images.githubusercontent.com/5317799/111396130-b1fa4380-867b-11eb-90f3-5df5503cfd9b.png">

**Comment by houmark** [comment]
I've seen even white text in disabled fields in Safari. I think it was in number fields. We did a CSS `!important` overwrite on all disabled input type fields to fix it quickly but I honestly forgot to report it.
