### ISSUE TITLE
Question: Are you interested to give a try Creevey as Visual Regression tool?

### ISSUE THREAD

**Issue by wKich** [uber/baseweb#4128]
Hello there. I'm the author of [Creevey](https://github.com/wKich/creevey) the visual regression tool specially built for Storybook. 

The main features are:

- Use stories as tests, no more need to write explicit tests
- Allow write interaction tests
- Has fancy UI Runner with various ways to compare images
- Run tests without leaving Storybook
- Run browsers inside the docker
- Has tests hot-reload, change your story/test code without a full restart
- Cross-browser testing, built on top of Selenium
- And more...

If you see what something is missing for your use cases, please tell me. I'll be happy to collaborate with you.

Feel free to ask me anything.

**Comment by chasestarr** [comment]
Hi @wKich The tool looks good. We've made our own VRT system that works well for us and are not planning to change. Thank you for the suggestion.
