### ISSUE TITLE
Can not import `bpfrpt_proptype_WindowScroller` when using PhoneInput component

### ISSUE THREAD

**Issue by huyng12** [uber/baseweb#4129]
## Current Behavior
I am using [vite@^2.0.5](https://vitejs.dev/) (which is using Rollup) and when I import `PhoneInput` component, it fail to build.

```
10:03:50 PM [vite] new dependencies found: baseui/phone-input, updating...
 > node_modules/baseui/node_modules/react-virtualized/dist/es/WindowScroller/utils/onScroll.js:74:9: error: No matching export in "node_modules/baseui/node_modules/react-virtualized/dist/es/WindowScroller/WindowScroller.js" for import "bpfrpt_proptype_WindowScroller"
    74 │ import { bpfrpt_proptype_WindowScroller } from "../WindowScroller.js";
       ╵          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## Expected Behavior
The build stage should be done perfectly.

## Your Environment
| Tech    | Version |
| ------- | ------- |
| Base UI | v9.111.2 |
| React | v17.0.0 |
| Vite | v2.0.5 |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by huyng12** [comment]
I am working around by remove the line below and it works but it is temporary.
```js
import { bpfrpt_proptype_WindowScroller } from "../WindowScroller.js";
```

**Comment by chasestarr** [comment]
Hi, I believe this is related to https://github.com/bvaughn/react-virtualized/issues/1632 May want to follow up with vite or react-virtualized

**Comment by huyng12** [comment]
Thank you @chasestarr

**Comment by shunyue1320** [comment]
vite.config.ts

```js
export default defineConfig({
  plugins: [ reactVirtualized() ], // add
}


export function reactVirtualized() {
  return {
    name: "my:react-virtualized",
    configResolved() {
      const file = require
        .resolve("react-virtualized")
        .replace(
          path.join("dist", "commonjs", "index.js"),
          path.join("dist", "es", "WindowScroller", "utils", "onScroll.js"),
        );
      const code = fs.readFileSync(file, "utf-8");
      const modified = code.replace(WRONG_CODE, "");
      fs.writeFileSync(file, modified);
    },
  }
}
```

**Comment by koyta** [comment]
@shunyue1320 what is WRONG_CODE? 🤔

**Comment by a2441918** [comment]
> @shunyue1320 what is WRONG_CODE? 🤔

WRONG_CODE is the file which needs to be replaced.

**Comment by rabira-hierpa** [comment]
Tried @shunyue1320  method and i'm getting the error 

```shell
error when starting dev server:
TypeError: __require.resolve is not a function
```

**Comment by tony** [comment]
re: https://github.com/uber/baseweb/issues/4129#issuecomment-1208168306

I had to use single quotes in `WRONG_CODE` to get this to work (react-virtualized 9.21.1)
 
Before:

    const WRONG_CODE = `import { bpfrpt_proptype_WindowScroller } from "../WindowScroller.js";`

After:

    const WRONG_CODE = `import { bpfrpt_proptype_WindowScroller } from '../WindowScroller.js';`

**Comment by AgomohC** [comment]
> re: [#4129 (comment)](https://github.com/uber/baseweb/issues/4129#issuecomment-1208168306)
> 
> I had to use single quotes in `WRONG_CODE` to get this to work (react-virtualized 9.21.1)
> 
> Before:
> 
> ```
> const WRONG_CODE = `import { bpfrpt_proptype_WindowScroller } from "../WindowScroller.js";`
> ```
> 
> After:
> 
> ```
> const WRONG_CODE = `import { bpfrpt_proptype_WindowScroller } from '../WindowScroller.js';`
> ```

Hey, doing this crashes my application. Are there any processes you took before adding this snippet to your vite config file?

**Comment by tony** [comment]
> Hey, doing this crashes my application. Are there any processes you took before adding this snippet to your vite config file?

Do you have the full error (before and after switching out `WRONG_CODE`)?  I am interested to see it.

Nothing was done on my part aside from using the code at https://github.com/uber/baseweb/issues/4129#issuecomment-1208168306 and running vite to build the project again. Note: I didn't use `vite dev`, I closed vite and used `vite build` to test again. After doing that the error subsided.

**Comment by AgomohC** [comment]
> > Hey, doing this crashes my application. Are there any processes you took before adding this snippet to your vite config file?
> 
> Do you have the full error (before and after switching out `WRONG_CODE`)? I am interested to see it.
> 
> Nothing was done on my part aside from using the code at [#4129 (comment)](https://github.com/uber/baseweb/issues/4129#issuecomment-1208168306) and running vite to build the project again. Note: I didn't use `vite dev`, I closed vite and used `vite build` to test again. After doing that the error subsided.

It requested that I install node which was weird. I switched to react-virtuoso and was able to implement the feature.

**Comment by ASMAKHAN0987** [comment]
I am still having this error please help me guys my project is so important for me help me If you have any idea to resolve it error while updating dependencies:
Error: Build failed with 3 errors:
error: Cannot read directory "node_modules/...": The system cannot find the path specified.
error: Cannot read directory "node_modules/react-virtualized/dist/es/WindowScroller/utils/...": The system cannot find the path specified.
node_modules/react-virtualized/dist/es/WindowScroller/utils/onScroll.js:74:47: ERROR: Could not resolve ".../WindowScroller.js"
    at failureErrorWithLog (D:\MYLIFE\netflixClone\node_modules\esbuild\lib\main.js:1649:15)
    at D:\MYLIFE\netflixClone\node_modules\esbuild\lib\main.js:1058:25
    at D:\MYLIFE\netflixClone\node_modules\esbuild\lib\main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by gitmathub** [comment]
We also have the same error as described above.

**Comment by ASMAKHAN0987** [comment]
if you find any solution share it with me please

**Comment by mc-alt** [comment]
I was getting the same issue as @AndrejGajdos. I worked around it using the patch function in pnpm (https://pnpm.io/cli/patch)

My patch just deletes the problem line from the dependency
