### ISSUE TITLE
Next.js setup issues

### ISSUE THREAD

**Issue by sansdesign-albert** [uber/baseweb#4131]
## Current Behavior
After creating a new nextjs app from the typescript example and adding baseweb (or from the styletron example and adding typescript and baseweb), the app does not compile but instead returns `ReferenceError: document is not defined`.

#### Path A
1. `yarn create next-app --example with-typescript nextjs-typescript-first-baseweb-example`
2. `cd nextjs-typescript-first-baseweb-example`
3. Edit `pages/index.tsx` to use code from baseweb setup guide.
4. Restart app.
5. Compilation fails.

#### Path B

1. `yarn create next-app --example with-styletron nextjs-styletron-first-baseweb-example`
2. `cd nextjs-styletron-first-baseweb-example`
3. Edit and add as necessary (per nextjs docs) to convert to typescript.
4. Add baseweb code from setup to `pages/index.tsx`
5. Restart app.
6. Compilation fails.

## Expected Behavior
The app should compile.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.111.2  |
| React   | 17.0.1 |
| Next.js | 10.0.9 |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by sanjayrjs16** [comment]
Hi @sansdesign-albert ,

The issue primarily occurs as you might be using SSG or SSR in your app, as there is no document in the node environment (Only on browser), the page maybe SSG on build time (getStaticProps) or in request time with SSR (getServerSideProps).

Please refer the implementation in this repo:
https://github.com/tajo/nextjs-baseweb/blob/master/src/pages/_app.tsx

**Comment by tajo** [comment]
Created PR #4610 to link https://github.com/tajo/nextjs-baseweb (updated) in the setup section. That should get anyone started quickly without any issues.
