### ISSUE TITLE
TimePicker should include clearable option, similar to Select

### ISSUE THREAD

**Issue by ajbogh** [uber/baseweb#4132]
## Feature description

The TimePicker component should allow the user to delete or clear a selected option. 

When `clearable` is set to `true` and the value is undefined, then the TimePicker should start with "Select" as the default placeholder text, just like the Select dropdown.

The TimePicker should call the onChange callback with a null parameter when the user deletes the value.

The clearable option should also be activated with `escapeClearsValue`  and `deleteRemoves`, whether these are also implemented in the TimePicker props or passed to the Select as overrides.

**Comment by chasestarr** [comment]
Hi, all of the select parameters are available through overrides. Is this what you're thinking of? https://codesandbox.io/s/base-web-timepicker-forked-4gocv?file=/src/example.js

**Comment by ajbogh** [comment]
Yes, thanks. For some reason that wasn't working for me, it wouldn't call the onChange function. Perhaps a PEBKAC error on my part.
