### ISSUE TITLE
Doesn't have the proper types of styleron

### ISSUE THREAD

**Issue by enes-get-local** [uber/baseweb#4162]
My react project components is created with baseweb framework. I decided to use [bit.dev](https://bit.dev) to versioning and managing these all components.

In this process, i added an example component to my remote scope and tried to versioning. 

Basic example:
```
import React from 'react';
import { Block } from 'baseui/block';

const IconWrapper: React.FC<Props> = ({
  key,
  children,
  style,
  backgroundColor,
  onClick,
  cursor,
  className,
  width,
  id,
  height,
}) => {
  return (
    <Block
      key={key}
      className={className}
      display={'flex'}
      justifyContent={'center'}
      flexDirection={'row'}
      alignItems={'center'}
      width={width}
      height={height}
>
      {children}
    </Block>
  );
};
export default IconWrapper;
```
When i work with that i get error like this :
![image](https://user-images.githubusercontent.com/70728456/113349862-54cfe480-9341-11eb-8139-870324ffd9f7.png)

This error happen when work with components whic uses import from baseui. Seems that the baseui package doesn't have the proper types of styleron react

Any help with that ? 

| Tech    | Version |
| ------- | ------- |
| Base UI | 9.105.0  |
| React   |  16.13.1  |
| browser |         |

**Comment by chasestarr** [comment]
Try installing `yarn add @types/styletron-standard @types/styletron-react @types/styletron-engine-atomic @types/react @types/react-dom`

**Comment by enes-get-local** [comment]
> Try installing `yarn add @types/styletron-standard @types/styletron-react @types/styletron-engine-atomic @types/react @types/react-dom`

@chasestarr I have these packages already. You can see package.json below. 
[package.json .txt](https://github.com/uber/baseweb/files/6250741/package.json.txt)

**Comment by chasestarr** [comment]
I'm not familiar with bit.dev. You may want to ask for support with bit or typescript communities
