### ISSUE TITLE
[popover] The "onClickOutside" event does not work properly in a web component

### ISSUE THREAD

**Issue by gevgeny** [uber/baseweb#4181]
The `onClickOutside` event being fired when user clicks on a popover target or a content if the popover used inside a web component.
[Demo](https://codesandbox.io/s/base-web-popover-stateless-example-forked-8rxdf?file=/src/example.js)

The reason why it happens is [the event target](https://github.com/uber/baseweb/blob/v9.112.0/src/popover/popover.js#L254) of the `onDocumentClick` event. Such approach works only when the root element is `document`, for a popover which is rendered in a web component `event.target` returns whole web component host element. The solution which will work for web components as well is `event.composedPath`:
```js
const target = event.composedPath()[0];
```

## Expected Behavior
The `onClickOutside` should not be fired when user clicks on a popover target or a content 

## Your Environment
| Tech    | Version |
| ------- | ------- |
| Base UI | latest |
| React   |  latest       |
| browser |   any      |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Happy to accept a PR that fixes this for your needs. We don't have experience with web-components

**Comment by gevgeny** [comment]
@chasestarr I see. I am going to go deeper to find other problems which may be caused by Shadow DOM and then prepare a PR. One more such problem my team have found is related to the Select component: https://codesandbox.io/s/base-web-popover-stateless-example-forked-4ufvc?file=/src/example.js. Looks like this one may be also fixed by using `event.composedPath`.
Could you recommend me other places in the lib I should pay attention to for the fix?
