### ISSUE TITLE
Access to Colors

### ISSUE THREAD

**Issue by simPod** [uber/baseweb#4187]
I did not find it in docs but is there a way to access eg. default `gray400` color? Can't find any suitable export. Thank you!

https://github.com/uber/baseweb/blob/570b0c01a9c6c4d0b582baf7949e0c85c4ee3f5b/src/tokens/index.d.ts

**Comment by chasestarr** [comment]
Hi, here's an example of how to import: https://codesandbox.io/s/base-web-button-forked-fyp9e?file=/src/example.js

**Comment by simPod** [comment]
`import { colors } from "baseui/tokens";` got it. Thanks!
