### ISSUE TITLE
Using Snackbar with Promises skips even snackbars

### ISSUE THREAD

**Issue by simPod** [uber/baseweb#4189]
I'm using Snackbar with apollo client to show snackbar after a query/mutation is complete.

However, when I use it within `async` function after `awaiting` graphql mutation. The even snackbars are skipped.

I debugged internal queue and snackbars are enqueued and dequeued successfully, however they're not displayed properly for some reason.

## Current Behavior

I've created reproducible example here

https://codesandbox.io/s/react-apollo-multiple-mutations-forked-om1hs?file=/src/AppWithHooks.js

See `AppWithHooks.js` where this code is the core:

```ts
async () => {
  await performOperation({ variables: { type: "increment" } });

  let i = 1;
  enqueue({ message: i++ });
  enqueue({ message: i++ });
  enqueue({ message: i++ });
  enqueue({ message: i++ });
  enqueue({ message: i++ });
}
```

After promise return, only snackbars 1, 3 and 5 are shown. 2nd and 4th are skipped.

## Expected Behavior

After promise return snackbars 1-5 are shown.

## Your Environment

See playground

| Tech    | Version |
| ------- | ------- |
| Base UI | latest  |
| React   |  latest       |
| browser | latest Chrome |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by niksmac** [comment]
I also have this problem.
