### ISSUE TITLE
Uber is Unusable without Google Services

### ISSUE THREAD

**Issue by dm17** [uber/baseweb#4190]
I see two options, and we can split this bug up if needed:
1) Fix Uber app so it works without Google Services (harder)
2) Fix PWA (progressive web app) so you can:
-- change destination without canceling (and have to get out of the car to order a new Uber)
-- add stops
-- save at least 1 recent/home address

There are two primary reasons we need this - besides the fact that Uber announced a functioning PWA years ago on its engineering blog: 
1) lots of privacy conscious Android ROMs now have removed Google Services 
2) lots of people order Ubers from their computers for other people leaving their homes.

Thanks!

**Comment by chasestarr** [comment]
Hi, this issues page is only for the baseui project. Please file Uber issues through the app.

**Comment by dm17** [comment]
Not even worth it. They don't get attention clearly. Sorry for posting in the wrong place, though.
