### ISSUE TITLE
Themes are not working for Slider

### ISSUE THREAD

**Issue by Songhyun9** [uber/baseweb#4213]
## Current Behavior
<img width="572" alt="slider" src="https://user-images.githubusercontent.com/34291021/116986150-658cc500-ad08-11eb-9345-4655ec374836.png">

## Expected Behavior
color of sliders expected turn red(cf0000)
it is not working on my codes and also not working on https://baseweb.design/components/slider/

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.113.0  |
| React   |         |
| browser |     chrome    |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by akshatnitd** [comment]
I am working on it.
