### ISSUE TITLE
Tabs (Motion) - Not selected tab align not showing properly

### ISSUE THREAD

**Issue by png-prakash** [uber/baseweb#4267]
I have language toggle in my app. When I change language select tab not highlight properly. I checked old version of tabs (https://baseweb.design/components/tabs/) and this working fine. How to fix this issue?

Thanks

![tabs](https://user-images.githubusercontent.com/61315943/118921496-e62d0180-b955-11eb-9830-ac91b60cab16.png)

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.115.1   |
| React   |    17.0.2     |
| browser |       |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Can you please share a codesandbox reproduction? Try using this as a starting point https://codesandbox.io/s/6jpv3?module=src/example.js

**Comment by png-prakash** [comment]
> Can you please share a codesandbox reproduction? Try using this as a starting point https://codesandbox.io/s/6jpv3?module=src/example.js

https://codesandbox.io/s/base-web-tabs-forked-1zh8o?file=/src/example.js

**Comment by akshatnitd** [comment]
@chasestarr I am working on it.
