### ISSUE TITLE
How to use FileUploader

### ISSUE THREAD

**Issue by simPod** [uber/baseweb#4268]
I've stumbled upon https://baseweb.design/components/file-uploader/

I wonder how to use it in practice. When a file is dropped how to handle it? Would it be possible to add a better example?

Thanks!

**Comment by williamernest** [comment]
In the Basic Usage example ([https://baseweb.design/components/file-uploader/#file-uploader-basic-usage](https://baseweb.design/components/file-uploader/#file-uploader-basic-usage)) there's a comment for where the user can handle the file upload ` // handle file upload...`. There are also a lot of lifecycle props to help manage the full process (onDrop, onDropAccepted, onDropRejected, onDragStart, etc).
