### ISSUE TITLE
[select] select is not opening on first click after clearing value

### ISSUE THREAD

**Issue by ujaval403** [uber/baseweb#4285]
**Current Behaviour**
Select one of the options and clear it via clicking on the cross icon. Try to open the select again via clicking on select input area or open arrow. select in not getting opened. from the second click onwards it is working fine.

**Expected Behaviour**
Select should open in the first click in above scenario.

**Comment by houmark** [comment]
@DhruvilSutariya and @ujaval403 can you just send a virtual hug for reporting and fixing this? This has been bothering me for the longest time but never had the time to dig in and report it. Thank you!
