### ISSUE TITLE
StatefulTooltip + StatefulMenu

### ISSUE THREAD

**Issue by nathanburgess** [uber/baseweb#4291]
I'm unable to find anything in the docs about this but I'd like to be able to combine `StatefulPopover` and `StatefulTooltip`:

```js
<StatefulPopover content={menuContent}>
  <StatefulTooltip content="Click me for a menu">
    <Button>Menu</Button>
  </StatefulTooltip>
</StatefulPopover>
```

The code above will display the tooltip but the popover is disabled. If I make `StatefulTooltip` be the parent then the popover works but the tooltip doesn't.

**Comment by williamernest** [comment]
You'll need to put another filler element between them. The tooltip component uses a popover component in its implementation, so it looks like their colliding on the button, and the last one applied is winning out. By adding a filler span/div around the inner element, it should allow both popovers to behave appropriately. 

Example. 
https://codesandbox.io/s/base-web-popover-forked-639ln?file=/src/example.js

**Comment by nathanburgess** [comment]
> You'll need to put another filler element between them. The tooltip component uses a popover component in its implementation, so it looks like they're colliding on the button, and the last one applied is winning out. By adding a filler span/div around the inner element, it should allow both popovers to behave appropriately.
> 
> Example.
> https://codesandbox.io/s/base-web-popover-forked-639ln?file=/src/example.js

Awesome! Just what I was looking for, thanks so much.
