### ISSUE TITLE
onError is not called in avatar

### ISSUE THREAD

**Issue by hardikmodi1** [uber/baseweb#4306]
onError is not called in avatar component in some case. Reproducible in docs refresh the page 1-2 times.
<img width="1778" alt="Screenshot 2021-06-07 at 9 11 41 PM" src="https://user-images.githubusercontent.com/22965398/121049310-379e1300-c7d5-11eb-9e5c-ad448568dfa1.png">

## Current Behavior
When image does not exist, avatar component show the initials by setting the state in onError handler of image. But in some cases this handler is not called and avatar gets stuck with broken image and alt text

## Expected Behavior
It should show the initials in every case.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.116.0  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by smitpatel1010** [comment]
@chasestarr @gergelyke 
Facing the same issue, can we please fix this.

**Comment by hardikmodi1** [comment]
Found something related to this issue, this is may be due to SSR. https://rants.broonix.ca/nextjs-fallback-image. https://github.com/mui-org/material-ui/blob/HEAD/packages/material-ui/src/Avatar/Avatar.js material ui uses hook which internally create image instance with `new Image()` to make sure that it works with server side rendering.

**Comment by chasestarr** [comment]
Did this issue just start? Happy to review a PR if you all have ideas

**Comment by williamernest** [comment]
Safari 14.1.1 seems to have issues as well 
![image](https://user-images.githubusercontent.com/34519388/121214826-567fc200-c834-11eb-9291-524d2a3ac800.png)

**Comment by williamernest** [comment]
Fixed via #4326
