### ISSUE TITLE
Stateless Accordion with expand state bug

### ISSUE THREAD

**Issue by VigneshPeriasami** [uber/baseweb#4320]
## Current Behavior

Panel to toggle expanded state on each click.

In current behavior, if first click opens the Panel the second click on the same doesn't close the panel.

https://codesandbox.io/s/base-web-stateless-accordion-forked-xr5uj

**To reproduce, Open any panel and try closing the same, in the above sandbox code sample.**

## Expected Behavior
If the first click on the Panel opens, expectation is second click on the same panel to close it.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | 9.116.0 |
| React   |    v17.0.2     |
| browser |  Chrome       |

**Comment by tanoy009** [comment]
The bug is introduced in base-web versions 9.113 before this the component with the above setup works as expected
bug Fiddle: https://codesandbox.io/s/base-web-stateless-accordion-forked-x4bbq
Working on the fix. Will raise a PR Shortly

**Comment by williamernest** [comment]
Thanks for filing/catching this. 

Definitely a bug, the callbacks should be updating the the local state variables they're using change. https://github.com/uber/baseweb/pull/4322 will fix
