### ISSUE TITLE
[ProgressSteps] Font family not applied for title

### ISSUE THREAD

**Issue by png-prakash** [uber/baseweb#4328]
Font family not applied for progress-steps  title. I applied font family for button, normal text and progress-steps. I checked with font finder tool  in chrome.

**Button**
font-family (stack): aktiv-grotesk, sans-serif
Font being Rendered: sans-serif

**div**
font-family (stack): aktiv-grotesk, sans-serif
Font being Rendered: sans-serif

**Progress-steps title**
font-family (stack): aktiv-grotesk, sans-serif
Font being Rendered: Times New Roman

https://codesandbox.io/s/base-web-progress-steps-ongz5

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.116.0  |
| React   |    16.13.1     |
| browser |    Chrome     |

**Comment by williamernest** [comment]
Not sure why your example is using a different font-family string for the progress steps than it is for others`fontFamily: "Aktiv Grotesk",` but changing that to match the others yielded the expected results. 

https://codesandbox.io/s/base-web-progress-steps-forked-bypfn?file=/src/example.js

![image](https://user-images.githubusercontent.com/34519388/122475511-9d2e9400-cf79-11eb-847f-3e351ea5c2b2.png)
