### ISSUE TITLE
Menu component crashes when performing type-ahead with a component as label

### ISSUE THREAD

**Issue by houmark** [uber/baseweb#4331]
## Current Behavior

The `Menu` component `ListItem` label accepts a React component / React element/fragment as its value and we have been using that to render custom SVG icons (using the `react-icons` library) for menu options for a long time since there's no other simple way to render SVG icons to the left or right of the label value to our knowledge. 

Unfortunately, that has a side effect. If the user has the menu focused and uses the keyboard to type anything a type-ahead search is initiated and that search crashes as the Menu component attempts to perform a `toUpperCase` on the label, which it expects to be a string.

We may be using an undocumented feature here and while I would like to rewrite our use case to not crash but still render icons, I have not been able to find any documentation on how to do that. The profile version does not seem to be useful, as it will require an image path for the icon. I'm sure it's possible with some serious nested overrides, but maybe there could be interest in either correcting the comparison that fails to consider a component or adding additional options for the Menu component to render this type of stuff without breaking a typed search.

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.116.1  |
| React   |     v17    |
| browser |    Chrome     |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by williamernest** [comment]
Thanks for filing this issue. Can you provide a repro using codesandbox so we can investigate further?

**Comment by houmark** [comment]
Sure can: https://codesandbox.io/s/base-web-statefulmenu-forked-o48n3?file=/src/example.js

Reproduction steps:

1. Load the sandbox
2. Hover over the menu
3. Type on keyboard
4. Component will crash

Note "Item One" is wrapped to be a component output.

**Comment by houmark** [comment]
Stacktrace screen dump from above Codesandbox which was forked from the Baseweb documentation/playground:

![Image 2021-06-16 at 6 57 00 PM](https://user-images.githubusercontent.com/467330/122309866-bc271a80-ced4-11eb-8b57-bb90e5a707d5.jpg)

**Comment by williamernest** [comment]
I'm not sure your changes were saved/forked. The above URL shows 
`  return (
    <StatefulMenu
      items={[
        { label: "Item One" },
        { label: "Item Two" },
        { label: "Item Three" },
        { label: "Item Four" }
      ]}
    />
  );
}`

which does not produce an issue for me.

**Comment by houmark** [comment]
Sorry, I was sure it was forked. I see you attempted a crash fix, which I am totally happy with as a proper solution seems much more complex.

Just for good measure, I will post the sandbox reproduction example here again:
https://codesandbox.io/s/base-web-statefulmenu-forked-tgx7p?file=/src/example.js
