### ISSUE TITLE
ProgressSteps does not respect isCompleted prop

### ISSUE THREAD

**Issue by rabbitXIII** [uber/baseweb#4332]
## Current Behavior

Currently the ProgressSteps component passes through `isActive` prop, but calculates its own `isCompleted` prop for the child components ([link to code](https://github.com/uber/baseweb/blob/master/src/progress-steps/progress-steps.js#L36-L37)).  Whatever value is passed into Step's props is effectively thrown away when using ProgressSteps.
e.g.
```
const STEP_OVERRIDES: StepOverrides = {
  Content: {
    style: ({ $isCompleted, $isActive }: StyleProps) => {
      console.log($isCompleted);
      console.log($isActive);
      return {
        width: '300px',
      };
    },
  },
};
<ProgressSteps>
  <Step isCompleted={true} isActive={true} overrides={STEP_OVERRIDES}>{text}</Step>
</ProgressSteps>
```

In the overrides console logs, we will see `$isCompleted` is always false, and `$isActive` is always true.

## Expected Behavior

Since StepProps [type definition](https://github.com/uber/baseweb/blob/master/src/progress-steps/index.d.ts#L25-L32) exposes both `isActive` and `isCompleted` as a prop that consumers can use, I would expect to be able to set either `isActive` or `isCompleted` and control the Step component behavior.  Currently, only `isActive` is passed through.

If it is intended that we directly use the Step component to have control over the component, and ProgressSteps should not respect the child props, please feel free to close this issue.

Thanks!

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.112.0  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by williamernest** [comment]
It looks like `isCompleted` was designed to be supplied by the ProgressSteps component when used together, but the Step component can also be used by itself by the user supplying the isCompleted prop for completed steps.
