### ISSUE TITLE
Expose modal animation default duration

### ISSUE THREAD

**Issue by ussserrr** [uber/baseweb#4343]
## Feature description
I show modal dialogs for user to perform some tasks on an item in the list. After the query, when an item has updated/removed the corresponding React components are updating and the ease-out animation is abruptly stopping. This is a known React problem that every one is works around on their own. Currently, I use a simple delay via `setTimeout` (with a guessed approximate number 500ms) before closing the modal to let an animation to finish. So I have 2 questions:

1. Did you developed some practices to solve issues of this type?
2. What is a default duration of the modal animation? I see some Baseweb components are exposing their default timings to public API but I can't find one for the modal widget.

**Comment by williamernest** [comment]
1. We have handled this issue in the past using hooks to ensure that animations finish before removing the elements from the DOM (most recently in the accordion, where the inner content is removed when the panel is closed, but the element must stay until the animation is complete). 
2. The default duration of the modal is listed as the transitionDuration in our styled-components.js file, which for this component/animation is timing400, which is 400ms. 
https://github.com/uber/baseweb/blob/master/src/modal/styled-components.js#L109

You can override this values using our Overrides API, https://baseweb.design/guides/understanding-overrides/

**Comment by ussserrr** [comment]
Thank you for the answer. What if I don't need to override the default value but just use it? With TypeScript I cannot import from `baseui/modal/styled-components` as is because it doesn't have corresponding type definitions. Do you suggest to create the typings for this particular file manually? Or just use overrides anyway in any case? Components like Popover has constants `ANIMATE_IN_TIME, ...`, why not expose similar to that?

**Comment by williamernest** [comment]
The values are global theme values, and are provided via the Theme object which is typed.

**Comment by ussserrr** [comment]
I understand that `theme.animation.timing400` is a global typed constant. But it has nothing specific to modal. If in the next Baseweb version the default modal animation timeout will change to `timing500` the code will not reflect this. Compare:

```typescript
const onCancel = (args) => {
  setIsOpen(false);
  setTimeout(() => props.onCancel(args), theme.animation.timing400);  // no relation to modal
}
```

```typescript
import { ANIMATE_OUT_TIME } from 'baseui/modal';
...
const onCancel: CancelHandler = (args) => {
  setIsOpen(false);
  setTimeout(() => onCancelPassed(args), ANIMATE_OUT_TIME);  // this will automatically adjust to whatever is default in the Baseweb code base
}
```

**Comment by williamernest** [comment]
We can't use the theme value to set the local constant, so I don't see a huge value add here since users are allowed to override all values themselves with their own custom theme either through creating a theme or setting an override. This may make your specific use case easier, but it also would be another value that we would have to maintain outside of our Theme config which is generally not preferred. 

Another option to stay aligned is to listen for the transitionend event on the modal.
