### ISSUE TITLE
Semantic TableBuilder missing dividers and cell spacing support

### ISSUE THREAD

**Issue by Deliaz** [uber/baseweb#4366]
## Current Behavior

The latest change https://github.com/uber/baseweb/pull/4315 seems to break UI of tables built with `TableBuilder`. 
According to the [types](https://github.com/uber/baseweb/blob/master/src/table-semantic/types.js) TableBuilder doesn't support `size` and `divider` props which makes such tables non-customizable. 

Migration from 9.112.0 to 9.116.2 changed our table's size and borders, and I can't find a way to make it look `compact` again. 

## Your Environment
Base UI v9.116.2

**Comment by chasestarr** [comment]
Thank you for reporting. I'll take a look soon
