### ISSUE TITLE
`$error` argument of `style` function in Input overrides is not fed the error state from its parent FormControl

### ISSUE THREAD

**Issue by bbruneau** [uber/baseweb#4393]
Thanks for all your work! I'm really enjoying the api of BaseUI so far.

## Current Behavior

When setting `overrides` on an `Input` that is wrapper in a `FormControl`, if you try to access the `$error` argument of the `styles` function, it always returns `false`, even when the `error` prop of `FormControl` is populated.

Sandbox here:
https://codesandbox.io/s/base-web-formcontrol-forked-qun9k

Documentation (from above sandbox): 

`$error` is not passed to the `Input`
https://user-images.githubusercontent.com/3789983/125526476-e93bc136-5ade-443b-89c5-f5c71a63e646.mp4

## Expected Behavior

Since `$positive` is passed correctly from `FormControl` to `Input`, I would expect `$error` to be passed as well.

example of expected behavior:
https://user-images.githubusercontent.com/3789983/125526836-ac77165a-fd1e-476a-9e70-4d2211dfc299.mp4

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.116.3 (latest)  |
| React   |  v17.0.2 (latest)       |
| browser | Chrome for Mac        |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by williamernest** [comment]
Thanks for filing this issue. This was a bit tricky, but was related to the Input having the error prop as a default prop. The logic within the FormControl was to set the child element error prop if the prop was not already set.

**Comment by bbruneau** [comment]
Nice find! Thanks for looking into it!
