### ISSUE TITLE
unable to resolve dependency tree, React 17.0.2 

### ISSUE THREAD

**Issue by smilank3** [uber/baseweb#4395]
when 'npm install baseui',   i got following errors.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"17.0.2" from react-dom@17.0.2
npm ERR!   node_modules/react-dom
npm ERR!     react-dom@"^17.0.2" from the root project
npm ERR!     peer react-dom@">= 16.8.0 < 18" from baseui@9.116.3
npm ERR!     node_modules/baseui
npm ERR!       baseui@"*" from the root project
npm ERR!     3 more (react-input-mask, react-movable, react-range)
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   8 more (baseui, styletron-react, react-dropzone, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0-alpha" from react-virtualized@9.22.3
npm ERR! node_modules/baseui/node_modules/react-virtualized
npm ERR!   react-virtualized@"^9.21.1" from baseui@9.116.3
npm ERR!   node_modules/baseui
npm ERR!     baseui@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by williamernest** [comment]
Thanks for filing this. Can you provide a repo that reproduces the issue?

**Comment by akornato** [comment]
@williamernest it also happens in a fresh CRA as it uses React 17.0.2 now i.e.
```
npx create-react-app my-app
cd my-app
npm install baseui
```

**Comment by smilank3** [comment]
@akornato baseui use react 16.9.0. i just realized.

**Comment by arvind0598** [comment]
When does this codebase plan to update to React 17? It seems like its going to be hard to install for anyone who starts a fresh new project.
