### ISSUE TITLE
Support `weekStartsOn` prop in datepicker

### ISSUE THREAD

**Issue by hardikmodi1** [uber/baseweb#4409]
Need a way to change the start of week in date picker. Like instead of Sunday, we want to start the week from Monday, Tuesday as per user preference.

## Current Behavior
I checked the current implementation, and with this this can be achieved by passing `locale` to datepicker, but the problem is we have to pass entire locale object as typed here https://github.com/date-fns/date-fns/blob/master/src/locale/types.ts

Is there any other way we can achieve this?

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.116.3  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by hardikmodi1** [comment]
@tajo @chasestarr any suggestion for how we can achieve this, can raise a PR for the changes required for the same.

**Comment by chasestarr** [comment]
Hi, there's an example here showing how to import the date-fns locale that you need https://baseweb.design/guides/internationalization/#datepicker-localization-example
