### ISSUE TITLE
Flip-dial mode for DatePicker

### ISSUE THREAD

**Issue by zubin-uber** [uber/baseweb#4422]
The default calendar mode on `DatePicker` works well for short range selection (2 weeks, 1 month etc).
However, it becomes a little tedious when selecting larger date ranges (2 years, 5 years etc) 

The feature request below proposes a flip-mode for `DatePicker` which could reduce the number of clicks/scrolls required for a date selection. 

## Feature description
Below is a quick wireframe for a single date selection. Each element (`day`, `month`, `year`) is represented as a flip-dial. The advantage with the design is that it allows for a range of selection on each element with a single click. Anything outside the default range shown on the flip-dial requires the user to spin the dial using the Up/Down arrows at the end. 

<img width="409" alt="flip-dial" src="https://user-images.githubusercontent.com/74631174/127038868-a3f44fe3-6b51-4673-bbef-0feead776eda.png">

By selecting an appropriate default date, a date selection could be done in just 3 clicks. 

Date Range selection would work very similar, with two such selectors side by side for `start_date` and `end_date`

**Comment by williamernest** [comment]
Thanks for filing this issue. After discussion with design we won't be implementing this ticket as the selection is a little too complex for our date picker component. We will be adding #4430 to our backlog though.
