### ISSUE TITLE
Table Semantic bottom border disapers while scrolling content

### ISSUE THREAD

**Issue by andriuss** [uber/baseweb#4439]
Table Semantic header bottom border is hidden under scrollable content when used with `DIVIDER` type `horizontal`, `vertical` or `grid`.

https://user-images.githubusercontent.com/6738026/128344994-17ffc867-b80f-498d-b865-a7b1711dcd76.mov

https://codesandbox.io/s/base-web-table-with-scrolling-contents-forked-k5fol?file=/src/example.js

## Current Behavior
The header bottom border disappears while scrolling table content.

## Expected Behavior
The header bottom border does not disappear while scrolling table content.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v10.0.0 |
| React   | 16.4.0 |
| browser | Chrome 92 |

**Comment by reddysridhar53** [comment]
The issue happens because we are using `border-collapse: collapse`, changing this to separate and adding `border-spacing: 0` would solve it.

**Comment by andriuss** [comment]
> The issue happens because we are using `border-collapse: collapse`, changing this to `separate` and adding `border-spacing: 0` would solve it.

Do you have working sandbox example?
