### ISSUE TITLE
Need custom styles for Data Table component (Root prop -> style prop)

### ISSUE THREAD

**Issue by ridhdhish-dalalstreet** [uber/baseweb#4440]
## Feature description
In **Data Table** component I want to give **custom styles**. But I am unable to do that. Because in Data Table component there is no **prop called Root** that we can override. So if there is another way to give custom style then please provide it or implement that for Data Table component.

**Comment by williamernest** [comment]
`To facilitate a rich set of analysis features out-of-the-box, DataTable does not allow for overrides.` from https://baseweb.design/components/data-table/
