### ISSUE TITLE
How to set zIndex for select box in Drawer for show dropdown list?

### ISSUE THREAD

**Issue by png-prakash** [uber/baseweb#4449]
I have to set zIndex for Drawer because of my layout. If I set zIndex in Drawer not able show select box value. I checked all style overrides for Select box, but not able to set zIndex for Selectbox. How to fix this issue? Thanks

Here is my sample code
https://codesandbox.io/s/base-web-drawer-forked-xswhg?file=/src/example.js

**Comment by williamernest** [comment]
You have to set the zIndex value on the Popover Body elements 
```
        overrides={{
            Popover: {
              props: {
                overrides: {
                  Body: {
                    style: { zIndex: 11 }
                  }
                }
              }
            }
```
