### ISSUE TITLE
unstable_ModalBackdropScroll warning still on v10 which is the next major

### ISSUE THREAD

**Issue by simPod** [uber/baseweb#4453]
## Current Behavior

I'm getting

> Consider setting 'unstable_ModalBackdropScroll' prop to true to prepare for the next major version upgrade. 'unstable_ModalBackdropScroll' prop will be removed in the next major version but implemented as the default behavior.

Though I have been getting this warning on v9 already.

Now I'm on v10, which should be the next major version as in `prepare for the next major version upgrade` message and the warning is there still.

## Expected Behavior

No error

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v10.0.0  |
| React   | v17        |
| browser | Chrome latest        |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by williamernest** [comment]
v10 was an unscheduled release due to some large UI changes. v10 changes were pushed to v11 and are expected to roll out in March of 2022.
