### ISSUE TITLE
async options does not work with select

### ISSUE THREAD

**Issue by tasawar-hussain** [uber/baseweb#4463]
## Current Behavior

When fetching options from some api, the menu does not populates, but if we close and open again, the popover is populated.

https://codesandbox.io/s/base-web-select-with-async-options-forked-51fel?file=/src/example.js

## Expected Behavior

The popover should reflect the data populated from async calls correctly

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v10.0  |
| React   |     17    |
| browser |     chrome    |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

There is a bit similar issue, but in that case works for me, 
https://github.com/uber/baseweb/issues/3992

**Comment by williamernest** [comment]
Thanks for filing this issue. I'm not seeing an issue with the async select in your attached sandbox. Since the event is triggered by onInputChange, whenever you start to type the request is sent and I am seeing the results of that request populate the dropdown. Can you take a video or explain in detail exactly what you are doing and what is happening?

**Comment by tasawar-hussain** [comment]
@williamernest Thanks for looking into it. 
So the problem is when i type the api is called , and results are fetched, but not populated in the menu popover, when i click outside the select field, menu is closed , and when again clicked inside the select input, the result from API call seemed to be populated in the menu. here is the screencast, i am typing hello, but the menu is still empty , and when open that again, it has values

https://www.loom.com/share/3e39f4f8b52d497e869ab40ea8df6e02

**Comment by williamernest** [comment]
The results aren't populated in the menu because none of the results match the string you're typing in. If you type "sam" then a result will show up, but the string you type is being used to filter the list.

**Comment by tasawar-hussain** [comment]
Thanks for the answer. Now i got ot actually, in my case searching( bit complex) is performed on backend, and I just need to populate all the results in select field. So can i turn off the search or should I use another component. And i also need multi select and grouping.

**Comment by williamernest** [comment]
You'll want to specify your own filterOptions function that does nothing 
```      filterOptions={(opts) => opts}```

https://codesandbox.io/s/base-web-select-with-async-options-forked-xqdpt?file=/src/example.js
