### ISSUE TITLE
Select Dropdown Component should also receive isOpen and closeMenu props

### ISSUE THREAD

**Issue by 278kunal** [uber/baseweb#4478]
The Select Dropdown Component should also receive isOpen state and closeMenu function as props to control open and close behaviour of Dropdown component in Select.

The following is the use case which requires this:-
<img width="431" alt="Screenshot 2021-08-23 at 1 59 47 PM" src="https://user-images.githubusercontent.com/8478814/130416243-32b49e97-8b32-423d-91d7-b372339cde86.png">

In the above component, we need to close the Dropdown when the OK Button is clicked. However the current overrides for Select component does not receive any props to control/implement this behaviour.

## Feature description
Exposing the isOpen Select internal state and closeMenu function of Select component via props to Dropdown component would solve this.

Example documentation:-

```
overrides={{
        Dropdown: {
          component: ({isOpen, closeMenu}) => {
            return <button onClick={closeMenu}>OK</button>;
          }
        }
 }}
```

**Comment by chasestarr** [comment]
Hi @278kunal this looks very different than the standard Select component dropdown. You may want to consider creating your own component rather than reusing the Select
