### ISSUE TITLE
Allow override to remove padding in StyledNavigationList (ALIGN.center)

### ISSUE THREAD

**Issue by treyshedrick** [uber/baseweb#4479]
## Feature description

I am needing to remove the paddingLeft and paddingRight from a StyledNavigationList with an $align={ALIGN.center} prop. I have tried a Root override, but it does not seem to change anything. Is there any current way this can be done?

![Screen Shot 2021-08-23 at 9 51 52 AM](https://user-images.githubusercontent.com/35882658/130468640-9dc54451-ecec-40ec-b48b-bf25a9015ae2.png)

**Comment by chasestarr** [comment]
Imports with the `Styled...` prefix do not have overrides. They are created with styletron `withStyle` and can be customized with `withStyle` https://www.styletron.org/react#reusing-styled-components
