### ISSUE TITLE
Additional DOM elements being created with wrapper component(s)

### ISSUE THREAD

**Issue by jamiller619** [uber/baseweb#4480]
## Current Behavior
The sandbox contains two components. The left one uses the basic setup example from: https://baseweb.design/getting-started/setup to render a form input inside a "centered" div container. The right-side component is identical in JSX markup, with the obvious difference being the StyletonProvider and BaseProvider components simply return their children. Which is to illustrate the issue where additional DOM nodes are being created in the left-side example:

https://codesandbox.io/s/baseui-bug-vpols

## Expected Behavior
Given the example above, I would expect to see the div from the Centered component to be the direct descendant of the React root container, as is shown in the Expected component in the sandbox.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v10.1.0  |
| React   | v17.0.2  |
| browser | Chrome latest |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Hi @jamiller619 the additional divs are intentional and will not be removed from the base-provider element. They are defined here https://github.com/uber/baseweb/blob/master/src/layer/layers-manager.js#L161 There is no plan to change

**Comment by jamiller619** [comment]
@chasestarr Makes sense. I did look to see if it was mentioned somewhere, not hard enough I guess. But no worries, it's not an issue now that I know about it.
