### ISSUE TITLE
StyledLink is missing animateUnderline prop

### ISSUE THREAD

**Issue by hckhanh** [uber/baseweb#4603]
## Current Behavior

In the Base Web docs, I saw:

![image](https://user-images.githubusercontent.com/6380436/140252677-ff6e44a5-18b0-4a3a-ba23-fc899ad59702.png)

But when I try using it:

![image](https://user-images.githubusercontent.com/6380436/140252490-720c4a6f-b96a-411f-babf-56d71732566b.png)

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v10.5  |
| React   |   v17.0.2      |
| browser |    Edge     |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Hi, we don't use typescript at uber so apologies for some missing type definitions there. If you'd like to add it, please submit a change to this file https://github.com/uber/baseweb/blob/master/src/link/index.d.ts

**Comment by hckhanh** [comment]
Hi @chasestarr, I will make a PR for this. Thank you for your suggest.
Can you take a look about this issue? #4602
