### ISSUE TITLE
StatefulMenu is not working in IE11

### ISSUE THREAD

**Issue by vinay-thallam** [uber/baseweb#4604]
StatefulMenu is not rendering in IE. Tested the same using baseui version 9.115.0. Also downgraded till 9.104.0. But No luck.
Looks like IE support was removed from 9.115.1 as per the docs ( Refer: https://github.com/uber/baseweb/releases/tag/v9.115.1 ). Hence was expecting it to work with baseui versions below 9.115.1.

Any help with the info regarding last version with IE support is greatly appreciated. Thanks in advance

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.115.0  |
| React   |    17.0.2 |
| browser |      IE 11   |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by williamernest** [comment]
Our docs were updated when we noticed that IE11 was no longer working/supported. I'm not sure of the last version that IE11 was working correctly for all components. IE11 has always been a pain to test in, so it may have stopped working some time ago and it took a while for the docs to get updated.
