### ISSUE TITLE
DataTable DatetimeColumn

### ISSUE THREAD

**Issue by AgrisysDJE** [uber/baseweb#4673]
A StatefulDataTable with DatetimeColumn will error if filter is activated for the Date Category

Try to add filter for date range in the test category for this fork  
https://codesandbox.io/s/base-web-custom-line-height-forked-r0ghn

## Current Behavior
TypeError
date.getMonth is not a function
Is thrown

## Expected Behavior
some calander of sort to select range for filter

**Comment by chasestarr** [comment]
Hi, this is due to your usage of `Date.now`. This method returns a `number`, but the component expects a `Date`. Here is an edit of your sandbox using `new Date()` https://codesandbox.io/s/base-web-custom-line-height-forked-uyu0c?file=/src/example.js
