### ISSUE TITLE
Tables onRowClick functionality

### ISSUE THREAD

**Issue by TomasKomprs** [uber/baseweb#4682]
Hello,
I would like to see "onRowClick" prop for row/s in Table.

When you click anywhere on row. It will call an action, defined in the "onRowClick" prop.

For example:

`  <TableBuilder
      data={DATA}
      onRowClick={(prop) => console.log('some fn')}
    >`

**Comment by williamernest** [comment]
This is achievable using overrides 
```
  const overrides = {
    TableBodyRow: {
      props: (props) => ({
        ...props,
        onClick: (val) => console.log("row clicked")
      }),
      };
```

**Comment by glacjay** [comment]
@williamernest but how can I get row data?

**Comment by allencoded** [comment]
This should really be explained in the documentation

**Comment by allencoded** [comment]
Overrides are but not evert Table types appear to allow overrides. For example `StatefulDataTable` appears to not allow overrides.

https://github.com/uber/baseweb/blob/422abf105c5195effabba898b49a6734e40a2e43/src/data-table/types.ts#L99-L134

```
      <StatefulDataTable
        columns={columns}
        rows={rows}
      />
```

**Comment by williamernest** [comment]
DataTable and Table are different components, since DataTables are a lot more complex. 
https://baseweb.design/components/data-table/
```
To facilitate a rich set of analysis features out-of-the-box, DataTable does not allow for overrides.
```
