### ISSUE TITLE
Popover positions wrong on the first open

### ISSUE THREAD

**Issue by houmark** [uber/baseweb#4693]
## Current Behavior

Somewhere since v10.7.x Popover has started positioning itself wrong and overflowing the viewport on the first open. If you close and open the same popover again, it will position itself correctly.

The documentation site Popover has the same issue.

To reproduce:

Open https://baseweb.design/components/popover/

1. Do not click the button
2. Resize your browser window to be approximately 800px width
3. Change the padding in the demo `Block` to be 200px instead of 20px
4. Click the button, the popover will show outside the viewport
5. Click outside the popover to close it
6. Click the button again, the popover will show centered below and fits inside the viewport

## Expected Behavior

That the Popover avoids rendering outside the viewport as it used to.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v10.7.1  |
| React   |     Latest stable    |
| browser |      Chrome 97   |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by yuli-TG** [comment]
Same issue.

**Comment by yuli-TG** [comment]
Popover placements are not correct on the first open: 
https://baseweb.design/components/popover/#popover-available-placements.
