### ISSUE TITLE
Select component tether blocks input when rendered near the top of the page

### ISSUE THREAD

**Issue by nrakochy** [uber/baseweb#4736]
Hi there, and thanks for the great library

## Current Behavior

If the Select component is in a container that causes it to reposition the tether, it can cut off the input at the top of the view. This is reproducible on [the ootb Select example](https://baseweb.design/components/select) by shrinking the browser window.

<img width="773" alt="Screen Shot 2022-02-01 at 5 07 55 PM" src="https://user-images.githubusercontent.com/3740177/152068184-fcd7ae4c-c197-43db-a8e0-d851f87bd4c7.png">

## Expected Behavior

Perhaps an api to disable to tether repositioning? I tried to use `{ignoreBoundary: true/false}` but this cuts off the dropdown content, rather than rendering it over the container.

Or, other recommendations/existing apis which might alleviate this behavior? 

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | 10.8.0  |
| React   |   17      |
| browser |    Chrome     |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
I'm not sure if users resizing their desktop browser window while the dropdown is open is a common situation. Can you please create a codesandbox reproduction where ignoreBoundary is not sufficient, excluding the resize scenario?

**Comment by nrakochy** [comment]
Thanks for the note. I suspect my issue actually lies w/ a malformed `mountNode`, as I am trying to introduce Baseweb into an existing app w/ z-index + positioning assumptions. Will plan to add a repro

**Comment by nrakochy** [comment]
Thanks again for the response. I am not repro-ing in `CodeSandbox`, so will close it out
