### ISSUE TITLE
Weird Behavior in iframe when popover or modal is open

### ISSUE THREAD

**Issue by kmcgrady** [uber/baseweb#4743]
## Feature description

This is that cross between a bug and an enhancement. We have an iframe that loads an app running BaseWeb components. We operate more or less like a codesandbox or repl.it where users run apps in the iframe and can manipulate it externally. If a popover or modal is open on the app in iframe, any behavior on the parent frame conflicts with the app due to the focus lock. This causes a flicker as the conflicts are fighting for focus.

I think the easiest solution would be to use `react-focus-lock's` undocumented `crossFrame` property https://github.com/theKashey/react-focus-lock/issues/104 and setting it to false. It essentially ensures the component maintains focus within the iframe, but allow the parent window to take focus.

**Comment by chasestarr** [comment]
Hi @kmcgrady I think this sounds ok to me. Would you be interested in contributing this change?

**Comment by kmcgrady** [comment]
Hi @chasestarr ! Yes. I will get a change out this week!
