### ISSUE TITLE
Popover makes browser scroll to top in some situations

### ISSUE THREAD

**Issue by houmark** [uber/baseweb#4797]
## Current Behavior
In Chrome, please open the documentation page for Popover and click the button:
https://baseweb.design/components/popover/#popover-close-from-content

(edit: it seems browsers struggle to scroll to the element for the documentation website, so please find the section called "Popover Close from Content")

This popover has a button inside which seems to be the reason for the scroll behavior as most other popovers won't make the browser scroll.

At least on the first load, the browser will scroll to the top when opening the popover. If you have multiple buttons that open popover (which we do for a user menu in a list) then it will happen at least the first time either one is clicked.

Update: This seems to happen for any popover that has a focusable element inside, for example, an input or a button. Even the main demo/playground on the very top of the page does this when opened, but to notice it you have to scroll down a bit before clicking the button, to watch your browser scroll up on click/open of the popover. Since it stays in view that way, it's easy to miss that this has an undesirable effect if that element was further down the page.

## Expected Behavior

That the browser does not scroll. I think this is a regression from recent popover changes as we did not see this behavior in the past. Interestingly this does not seem to happen in for example Safari and no error is thrown.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v10.9.0  |
| React   |   Latest       |
| browser |     Latest stable Chrome    |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Thank you for the report. I believe this was introduced in this PR https://github.com/uber/baseweb/pull/4700
Working on the 10.7.1 docs page https://v10-7-1.baseweb.design/components/popover
Reproducible on the 10.7.3 docs page https://v10-7-3.baseweb.design/components/popover
