### ISSUE TITLE
Tabs Motion Horizontal Scroll Issue

### ISSUE THREAD

**Issue by laurengreenway** [uber/baseweb#4857]
## Current Behavior

When a user has a mouse with no horizontal scroll capability (e.g. ergonomic mouse), there is no way for them to scroll through tabs that are horizontally oriented. There are workarounds I can implement in my own project, however this seems like an issue with much broader impact than my own use case, so I thought it was worth surfacing.

## Expected Behavior

There should be a way to scroll through an overflowing list of tabs if the user is not able to scroll horizontally with their mouse.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v10.8.0 |
| React   |  17.0.2       |
| browser |  Chrome       |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Hi, holding shift + scrolling will scroll horizontally
