### ISSUE TITLE
Menu component captures keyboard focus and blocks moving within the tab-sequence

### ISSUE THREAD

**Issue by MarcusMorba** [uber/baseweb#4890]
## Current Behavior
When moving the focus via keyboard to the component (TAB), pressing TAB or Shift + TAB does not move the focus to the next/previous element in the tab-sequence.

## Expected Behavior
The user should be able to focus the previous/next UI-control in the TAB-sequence

## Your Environment
your example page: https://baseweb.design/components/menu/

| Tech    | Version |
| ------- | ------- |
| Base UI | v10.12.1  |
| React   |  of the above version |
| browser | chrome latest / Win 10 |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by MarcusMorba** [comment]
@chasestarr - THANKS!

**Comment by chasestarr** [comment]
Thank you for reporting
