### ISSUE TITLE
eslint-plugin-baseui v11.x wrong warning about <Spinner>  component

### ISSUE THREAD

**Issue by TodBob** [uber/baseweb#4908]
Hello,
With upgrade to BaseWeb v11.x and eslint-plugin-baseui v11.x Im getting eslint warning about `<Spinner> `component.

code:
`import { Spinner } from 'baseui/spinner';`

warning:
"
The "Spinner" component has been deprecated in favor of "StyledSpinnerNext". In v11 of baseui, "Spinner" will be removed and "StyledSpinnerNext" will be renamed to "Spinner". (baseui/deprecated-component-api)
"

Spinner docs:
https://baseweb.design/components/spinner/#spinner

Error code can be found here:
https://github.com/uber/baseweb/blob/master/packages/eslint-plugin-baseui/src/deprecated-component-api.js

**Comment by jonsadka** [comment]
Experiencing the same issue on my end
