### ISSUE TITLE
Accessibility feature: option to hide focus-indicator for mouse users

### ISSUE THREAD

**Issue by MarcusMorba** [uber/baseweb#5036]
The visible focus-indicator (outline) on focusable elements should be hidable for mouse users until a user begins to interact with keyboard (specifically, the tab key). Optionally - resuming mouse/touch input can hide outlines again.

## Feature description
Ideally this can be set as a global parameter and be overwritten on a per component base.
Example behaviour, please see https://github.com/mrmckeb/react-outline-manager

**Comment by MarcusMorba** [comment]
Guess this can be closed as $isFocusVisible is available already.

**Comment by odeta** [comment]
hi @MarcusMorba, how can I utilise the `$isFocusVisible` to hide the focus outline appearing after mouse click on the page select component in [this ](https://codesandbox.io/s/ktvc1u?module=src/example.js&file=/src/example.js)example (taken from the base UI docs for Pagination)? 

![image](https://user-images.githubusercontent.com/31925863/222001310-7fdc8b46-a73f-496b-89c8-d5e61d7d4850.png)

**Comment by MarcusMorba** [comment]
@odeta - I will try to find out next week(end). Unfortunately at the moment, I am overloaded with work, as I´m leaving a project this month and have to manage the handoff, final documentation, and millions of other things. SORRY.
 
@stackyism - could you help with an example? I tried chatGPT, but the given example does not work.
Would be very interesting to know what to prompt to getting working code.

Thanks in advance.

**Comment by MarcusMorba** [comment]
The ChatGPT example for my prompt "How can I use FocusVisible within react baseweb to hide focus indicator for mouse users in a component?"

import React from 'react';
import { Pagination, FocusVisible } from 'baseui';

function MyPagination() {
  return (
    <FocusVisible>
      {({ focusVisible }) => (
        <Pagination
          numPages={10}
          currentPage={1}
          onPageChange={() => {}}
          overrides={{
            Root: {
              style: {
                outline: focusVisible ? '2px solid blue' : 'none'
              }
            }
          }}
        />
      )}
    </FocusVisible>
  );
}

export default MyPagination;

**Comment by MarcusMorba** [comment]
Maybe your team can also use ChatGPT to improve and extend documentation. My personal impression on this, it helps a lot to speed up the documentation workflow and especially the quality of the copy, so others which are not involved so deep can understand what we are trying to express.

**Comment by MarcusMorba** [comment]
@odeta - the challenge here, for the "pagination pattern" is propably to control and customize the focusRing of the dropdown component with styleOverwrites. This page has some examples: https://baseweb.design/components/combobox/#focus-and-inputref
