### ISSUE TITLE
v12 requires styletron-react 6.1.0 which doesn't exist

### ISSUE THREAD

**Issue by jacquesg** [uber/baseweb#5061]
## Current Behavior

v12 requires styletron-react 6.1.0 which hasn't been released yet.

## Expected Behavior

Depends on a stable version, that has been released.

## Your Environment

N/A.

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
Thank you for reporting. Published here https://github.com/styletron/styletron/commit/cc7e51d5c4be869c71b313155ff72e7f292e7f49
