### ISSUE TITLE
Unable to view documentation for specific versions

### ISSUE THREAD

**Issue by jacquesg** [uber/baseweb#5063]
## Current Behavior

![image](https://user-images.githubusercontent.com/3534453/180966555-b7ac6d75-0784-4182-b16f-568a30308a9d.png)

## Expected Behavior

Page should display.

## Your Environment

N/A.

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
We removed publishing subdomains for every release, but you can go to any release commit and view the preview build https://github.com/uber/baseweb/pull/4888
