### ISSUE TITLE
Question, do we get a warning on code like the following, which doesn't have records?

### ISSUE THREAD

**Issue by Tranekahackedme** [uber/baseweb#5121]
Question, do we get a warning on code like the following, which doesn't have records?
```java
class X { 
  boolean equals(Object o) { return false; }
  static boolean foo() { return (new X()).equals(null); }
}
```
If we don't get a warning, how does that work?  If we do get a warning, then I guess the issue here is that there is no explicit `equals()` method to annotate for a record?

_Originally posted by @msridhar in https://github.com/uber/NullAway/issues/619#issuecomment-1176891589_

**Comment by chasestarr** [comment]
I believe this is meant for NullAway. Please follow up there
